dashpay/dash-wallet

wallet/res/values/styles.xml

- An additional Toolbar is shown when an Address is Selected.
- Added `windowActionModeOverlay` and `actionModeBackground` in the app's Theme Styles

Don't show additional toolbar in Address screen

---

wallet/AndroidManifest.xml
wallet/res/values/strings-extra.xml
wallet/res/values/styles.xml
wallet/src/de/schildbach/wallet/ui/InputParser.java
wallet/src/de/schildbach/wallet/ui/WalletUriHandlerActivity.java

1. Added prompt in Dash Wallet when another app requests the master public key or an address using `dashwallet://...` uri.
2. Used wallet.freshReceiveAddress() instead of wallet.currentReceiveAddress() for address requests.
#77

Improve security of handling `dashwallet://` uris

---

wallet/src/de/schildbach/wallet/ui/widget/KeyboardResponsiveCoordinatorLayout.java

- The app is crashing with a NPE when calling `viewToHide.setVisibility(View.VISIBLE)`, there is a 100ms delay when showing the QR button and this is the most probable cause of the issue. 
- Removing the delay causes an almost not noticeable flick of the button when it's being shown in the same time that the keyboard is being shown, however, to fix the crash is more important now while we can search for an alternative (non-trivial) in the future to have it not to flick without the possibility of a crash.

Removing delay when showing QR button in SendCoins screen

---

wallet/src/de/schildbach/wallet/ui/EncryptKeysDialogFragment.java

- This should address #104 by preventing updating the view when the dialog is not attached to the activity anymore.

Checking if DialogFragment is attached to activity.

---

wallet/src/de/schildbach/wallet/ui/UnlockWalletDialogFragment.java

- Added check to verify if `UnlockWalletDialogFragment` is added after the password verification was finished. The dialog can be dismissed during the verification (by device rotation, for instance) causing the callback respond in a null context.
- This should fix #110 & #112

Checking if Dialog is added after verifying password

---

wallet/res/values-es/strings-extra.xml
wallet/res/values-pt-rBR/strings-extra.xml
wallet/src/de/schildbach/wallet/ui/BackupWalletToSeedDialogFragment.java
wallet/src/de/schildbach/wallet/ui/EncryptNewKeyChainDialogFragment.java
wallet/src/de/schildbach/wallet/ui/RestoreWalletActivity.java
wallet/src/de/schildbach/wallet/ui/WalletActivity.java
wallet/src/de/schildbach/wallet/ui/widget/UpgradeWalletDisclaimerDialog.java
wallet/src/de/schildbach/wallet/util/ParcelableChainPath.java

- This PR prevents crashes when Wallet is being Upgraded and the onboarding dialogs get recreated by the system (device rotation, app coming from bg with low memory, etc).

Preventing Crash when Dialogs are recreated

---

wallet/src/de/schildbach/wallet/ui/WalletActivity.java

- Preventing sending the app to background when pressing back while the drawer menu is open.

Closing Drawer menu when pressing back

---

wallet/build.gradle
wallet/res/values/strings-extra.xml
wallet/res/values/strings.xml
wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java
wallet/src/de/schildbach/wallet/ui/TransactionsAdapter.java
wallet/src/de/schildbach/wallet/ui/send/SendCoinsFragment.java

There are two objectives:
Notify the user if a transaction was sent to only 1 peer (due to being connected to only 1 peer). Previously the app stated that "the payment has not been transmitted".
Simplify the various transaction statuses to include simplier InstantSend and allowed 0-conf (this is not yet included)

Transaction State Messages

---

build.gradle
sample-integration-android/build.gradle
wallet/build.gradle
wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java

The List of seed peers for MainNet and TestNet was added to dashj 0.14.4.7.
If the DNS seeders don't return any peers, dashj throws a PeerDiscoveryException.  The code added catches this exception and attempts to connect to the Seed Peers (about 300 masternodes).

Use Masternode List as Seed Peers if DNS seeders return no peers

---

wallet/src/de/schildbach/wallet/Configuration.java
wallet/src/de/schildbach/wallet/WalletApplication.java
wallet/src/de/schildbach/wallet/data/WalletLock.java
wallet/src/de/schildbach/wallet/ui/UnlockWalletDialogFragment.java
wallet/src/de/schildbach/wallet/ui/WalletActivity.java
wallet/src/de/schildbach/wallet/ui/preference/PinRetryController.java
wallet/src/de/schildbach/wallet/ui/send/SendCoinsFragment.java

This adds a 3 minute "timer" based on the secure time when a PIN is entered correctly.
This means that for 3 minutes the app will remained unlocked.  After 3 minutes the app will lock if the user switches to a new app or the device locks itself.  Not sure about the exact timing as I don't know how often the secure time value is updated in the app.  
The 3 minute timer is activated if:
1.  The app is unlocked on any activity with the unlock function
2.  The user sends coins (which requires a PIN) which now unlocks the app.
Other functions that require a PIN do not unlock the app, such as Backup and Viewing the recovery phrase.

Add Wallet Lock Timer

---

wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java

BlockchainServiceImpl:  Set min peers to send > 1
* Before: 0 minimum peers was possible (resulted in exception in dashj)
* If connected peers = 1, 2, 3, then send to that many peers
* If there are no connected peers, wait for 3

Resolve Delayed Sending from v5.18.3+

---

wallet/src/de/schildbach/wallet/WalletApplication.java
wallet/src/de/schildbach/wallet/ui/preference/PinRetryController.java

- Using `SharedPreferences.commit()` instead of `apply()` to save changes immediately.
- Removed unused method `resetWalletAndExit()` in `WalletApplication` class.
- Copying Set of PINs attempts to a new instance before saving it to preferences again to avoid android issue.
- Finishing activities using `finishAffinity()` instead of killing process.

Fix Wallet Wipe - Closing all activities gracefully.

---

wallet/res/values/strings-extra.xml
wallet/src/de/schildbach/wallet/WalletApplication.java
wallet/src/de/schildbach/wallet/ui/AbstractWalletActivity.java
wallet/src/de/schildbach/wallet/ui/preference/PinRetryController.java

Purpose:
Prevent Brute forcing by adding the code to reset the wallet after the PIN is entered incorrectly 8 times and also to allow for logging to show that the 
In WalletApplication, I removed the delete all files methods and replaced it with:
1.  Create a new wallet (nonencrypted)
2.  Replace current wallet (user forgot their PIN that encrypts it) with new wallet (nonencrypted)
This method will preserve all settings and logs (for diagnosis of problems and so we will know that the user wiped the wallet).
The other code that closes the app remains the same.  The user must restart the app and it will be as if it was a fresh install.  The user will need to enter the mandatory PIN.
The second part of this is to add the code that will wipe the wallet after the PIN is entered incorrectly 8 …

Fix wallet wipe

---

wallet/build.gradle

This will fail the Travis CI test due to a missing dashj-core-0.14.7.
This will also have merge conflicts with the Rebranding PR#136.

Use dashj 0.14.7

---

wallet/AndroidManifest.xml

- This is a requirement since Android 9 for apps that execute foreground services.

Added foreground service permission in Manifest

---

wallet/res/xml/shortcuts.xml

This will work for any flavor (production, testnet, etc).
The package id originally specified was for that of Bitcoin Wallet (Testnet)

Shortcuts:  set targetPackage to the application id of this app

---

.travis.yml

Changes were made to get the Travis CI tests to pass:
1.  Add a license hash to prevent travis from stalling
Other changes:
1.  Build tools set to 28
2.  Added licenses (though travis is supposed to approve them by default)

Update travis settings and fix licensing issue

---

build.gradle
common/build.gradle
sample-integration-android/build.gradle
uphold-integration/build.gradle
wallet/build.gradle

This is to have a single place for the DashJ version.

Use $dashjVersion for all modules instead of hard coded version

---

wallet/src/de/schildbach/wallet/ui/send/SendCoinsFragment.java

I found a bug with `SendRequest.ensureMinRequiredFee = false` -- it can result in dust for outputs which are rejected by the network.  Therefore, we need to check for dusty outputs after we complete the transaction `wallet.completeTx` with `TransactionOutput.isDust` and if dust is found, then recreate the transaction with `SendRequest.ensureMinRequiredFee = true`
DMD-882

Handle dust outputs when ensureMinRequiredFee=false

---

wallet/src/de/schildbach/wallet/ui/EnableFingerprintDialog.java
wallet/src/de/schildbach/wallet/util/FingerprintHelper.java

I'm unable to reproduce this issue but was able to fix it based on static code analysis.
In rare cases calling the {{fingerprintHelper.savePassword}} method can cause the FingerprintHelper.Callback() is fired immediately, therefore the initialization of _fingerprintView_ in } {{EnableFingerprintDialog.onCreateDialog}} had to be performed before calling {{fingerprintHelper.savePassword}}.
Also, I added some additional logs in order to easily identify the cause of {{fingerprintHelper.savePassword}} to fail in the future.

Preventing from NPE when the fingerprint error occurred

---

wallet/src/de/schildbach/wallet/ui/ProgressDialogFragment.java

Changing the dismiss() to dismissAllowingStateLoss() when dismissing the ProgressDialogFragment in order to avoid IllegalStateExceptions when the method is called after moving the app to background.

[DMD-951] Paper Wallet Sweep Failure Crash

---

wallet/res/values/strings-extra.xml
wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java
wallet/src/de/schildbach/wallet/ui/TransactionsAdapter.java
wallet/src/de/schildbach/wallet/ui/send/SendCoinsFragment.java
wallet/src/de/schildbach/wallet/ui/send/SweepWalletFragment.java

Address two issues:
1.  missing fiat values:  now we will show fiat values for all incoming transactions (pending) and transactions that are less then 3 hours old that are in blocks.  we will put a message in the transaction if the fiat value cannot be obtained (a received transaction doesn't follow 1)
2.  duplicate values - we will erase the previous value in the view and then in the case of a null exchangeRate, assign a value of "----".

DMD-901, 907 - Fix Missing Fiat Values and Duplicated Fiat Values

---

wallet/src/de/schildbach/wallet/ui/WalletActivity.java

Set currency to default if no currency is currently set
This allows the exchange rate activity to be used to select a currency
on devices without SIM cards.  Previously, the user selection would
be reset to USD (the default currency).

DMD-974 Can't change currency without Sim Card

---

wallet/src/de/schildbach/wallet/ui/WalletActivity.java

Added missing `super.onActivityResult(requestCode, resultCode, intent)` call to avoid `IllegalStateException `when showing the dialogs after `onSaveInstanceState` and other potential issues with WalletActivity.

DMD-1003 Autolock Announcment Dialog Crash - hotfix 1

---

wallet/src/de/schildbach/wallet/ui/FastestNetworkAnncmntDialog.java

Changed the way the FastestNetworkAnncmntDialog dialog is displayed in order to avoid IllegalStateException when showing it after onSaveInstanceState.

DMD-1003 Autolock Announcment Dialog Crash - hotfix 2

---

wallet/src/de/schildbach/wallet/ui/EncryptKeysDialogFragment.java
wallet/src/de/schildbach/wallet/ui/WalletActivity.java

Made the _Change spending PIN_ dialog cancelable and added the "Cancel" button when launched from the safety menu.

[DMD-761] Cancel out of the Change pin screen

---

wallet/src/de/schildbach/wallet/ui/send/SendCoinsFragment.java

After scanning a QR code which requires IS, the IS upgrade checkbox in Send Screen is checked automatically.

[DMD-959] QR Code | Instant Send Required

---

wallet/src/de/schildbach/wallet/ui/WalletActivity.java

Fixed the crash on Android 6 when BackupWalletDialogFragment.show() method is called before WalletActivity.onResume() causing IllegalStateException or RuntimeException to be thrown.

[DMD-952] Backup to File Crash after requesting permission (Android 6)

---

wallet/src/de/schildbach/wallet/ui/send/SendCoinsFragment.java

The app crashes when the user presses send when the exchange rate is invalid (null).

[DMD-1020] SendCoinsFragment:  Avoid NPE when exchangeRate is null when logging

---

common/src/main/res/values/colors.xml
wallet/beta/res/xml/shortcuts.xml
wallet/res/drawable/shortcut_request_coins.xml
wallet/res/drawable/shortcut_scan_qr.xml
wallet/res/drawable/shortcut_send_coins.xml
wallet/testNet3/res/xml/shortcuts.xml

Fixed the issue with the app from shortcuts - in never versions of Gradle the shortcut.xml have no access to ${applicationId} variable so it has to be hardcoded for each flavor. Also fixed the shortcuts icons.

[DMD-755] Fix the app shortcuts

---

wallet/src/de/schildbach/wallet/util/AddressUtil.java

When a user pastes a testnet address in to mainnet (address field or other place) the app will crash.

AddressUtil: Fix crash when checking a TestNet/DevNet address in MainNet

---

wallet/src/de/schildbach/wallet/ui/SetPinActivity.kt

This resolves the issue of seeing a blank recovery phrase after
restoring from a backup file after installing for the first time.

SetPinActivity:  Initialize seed after decrypting a backup file

---

.tx/config

This only changes the `.tx/config` file.
The project reference is changed to match a common project to share the translation databases with the iOS app.
https://www.transifex.com/dash/dash-mobile-wallets/

Transifex:  Use common dash-mobile-wallets project along with iOS

---

wallet/cpp/hashblock.cpp

In previous version of DashJ, this code was called everytime a block was processed from the blockchain.
```
public static byte[] x11Digest(byte[] input, int offset, int length)
{
byte [] buf = new byte[length];
for(int i = 0; i < length; ++i)
{
buf[i] = input[offset + i];
}
return x11Digest(buf);
}
```
This method was copying the block header into a new byte [] array.  Consider that in one second, the app may process up to 300 blocks.  This allocates 24KB of memory per second (until garbage collection occurs).  This is passed to the native or java x11 hash function and then gets de-referenced.
Now in a new PR on DashJ (https://github.com/dashevo/dashj/pull/59)
```
public static byte[] x11Digest(byte[] input, int offset, int length)
{
try {
return native_library_loaded ? x11_native(input, …
```

C++:  Add parameters to x11 native hash function

---

common/src/main/java/org/dash/wallet/common/Configuration.java
wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java
wallet/src/de/schildbach/wallet/ui/OnboardingViewModel.kt
wallet/src/de/schildbach/wallet/ui/RestoreWalletActivity.java
wallet/src/de/schildbach/wallet/ui/WalletActivity.java

Expected Behavior:
- Don’t show notifications if rescanning the blockchain (current behavior)
- Don’t show notifications if restoring from a recovery phrase or backup file (until 1 day ago)
- Do show notifications on new transactions received while the app is running (that are not in a block yet)
- Do show notifications on new transactions received since the app was last used.

Redesign:  Do not show transaction notifications when restoring from seed or file

---

wallet/res/layout/sync_status_pane.xml
wallet/src/de/schildbach/wallet/ui/WalletActivity.java

The restart button that appears in the red rectangle with the message "Unable to connect" and "Check your connection" does not cause the app to try to reconnect to the Dash Network.  The app does that on its own, therefore the button will be removed. [See NMA-29]

Remove Sync Restart button

---

wallet/res/layout/activity_recover_wallet_from_seed.xml
wallet/res/values/strings-extra.xml
wallet/src/de/schildbach/wallet/ui/OnboardingActivity.kt
wallet/src/de/schildbach/wallet/ui/RestoreWalletFromSeedActivity.kt
wallet/src/de/schildbach/wallet/ui/RestoreWalletFromSeedDialogFragment.java
wallet/src/de/schildbach/wallet/ui/RestoreWalletFromSeedViewModel.kt

Instead of having an error message that includes words like "MnemonicException" and "Bad password" when a user enters a recovery phrase that has errors, this PR will use the same error messages as the iOS app, which include "Bad recovery phrase", "%s is not a valid recovery phrase word" and "Recovery phrase must be 12 words"
Additional changes include converting the RestoreWalletFromSeedActivity class to be more similar to the OnboardingActivity, which includes similar view model.  Some methods were removed from the OnboardingViewModel and placed in the RestoreWalletFromSeedViewModel.

Redesign:  Add Friendly Recovery Phrase Error Messages (NMA-284)

---

wallet/src/de/schildbach/wallet/ui/send/SendCoinsFragment.java

ON = The user will always have to authenticate before sending a payment
OFF = The user will not have to authenticate to send a payment if they already authenticated it on the lock screen 
If entering the pay flow without authenticating, the user must authenticate before sending the payment (even if Spending Confirmation = OFF)
The default setting = ON

Spending Confirmation

---

wallet/src/de/schildbach/wallet/ui/TransactionResultActivity.kt
wallet/src/de/schildbach/wallet/ui/WalletTransactionsFragment.java
wallet/src/de/schildbach/wallet/util/TransactionUtil.java

This will display Sending instead of Processing on sent transactions.  This may disagree with iOS.

NMA-24 (ii) Fix status disagreements between tx history and details 

---

wallet/AndroidManifest.xml
wallet/res/layout/activity_view_seed.xml
wallet/res/values/strings-extra.xml
wallet/res/values/strings.xml
wallet/src/de/schildbach/wallet/livedata/DecryptSeedLiveData.kt
wallet/src/de/schildbach/wallet/ui/BackupWalletToSeedDialogFragment.java
wallet/src/de/schildbach/wallet/ui/CheckPinDialog.kt
wallet/src/de/schildbach/wallet/ui/CheckPinSharedModel.kt
wallet/src/de/schildbach/wallet/ui/CheckPinViewModel.kt
wallet/src/de/schildbach/wallet/ui/DecryptSeedSharedModel.kt
wallet/src/de/schildbach/wallet/ui/DecryptSeedViewModel.kt
wallet/src/de/schildbach/wallet/ui/DecryptSeedWithPinDialog.kt
wallet/src/de/schildbach/wallet/ui/SecurityActivity.kt
wallet/src/de/schildbach/wallet/ui/VerifySeedActivity.kt
wallet/src/de/schildbach/wallet/ui/ViewSeedActivity.kt
wallet/src/de/schildbach/wallet/ui/WalletActivity.java

The primary focus of this PR is to use the correct design for the flow of viewing the recovery phrase.  Previously the flow was the same as the verify recovery phrase flow.
Additionally, the dialog was changed on the Secure Now function:
**Implementation:**
The CheckPinDialog was extended with a new subclass called DecryptSeedWithPinDialog while trying to maximize code reuse.  DecryptSeedWithPinDialog can use a PIN or a fingerprint to decrypt the seed that is given to the ViewSeedActivity.
I chose to derive a new class from CheckPinActivity instead of using CheckPinActivity to verify the PIN and then have a secondary set of task and screens with progress bars to perform the seed decryption with the key.
The old dialogs for decrypting the seeds are left in the app for the Wallet Upgrade …

Redesign: Fix View Recovery Phrase Flow and other security related flows [NMA-299]

---

common/src/main/java/org/dash/wallet/common/Configuration.java
wallet/src/de/schildbach/wallet/ui/CheckPinDialog.kt
wallet/src/de/schildbach/wallet/ui/SecurityActivity.kt
wallet/src/de/schildbach/wallet/ui/SetPinActivity.kt

- CheckPinDialog: Enable fingerprint reading if !pinOnly
- Add enable_fingerprint preference to track state of the Fingerprint setting in Security
- SetPinActivity: Only ask user to set up fingerprint if it is enabled in Security settings

PIN finger print alignments to iOS [NMA-320]

---

wallet/res/layout/send_coins_content.xml

This unintended change was made by AndroidStudio during the work on Uphold redesign and it was missed during the review.

Fixed the crash when displaying SendScreenActivity

---

common/src/main/java/org/dash/wallet/common/data/CurrencyInfo.java
wallet/src/de/schildbach/wallet/rates/ExchangeRate.java
wallet/src/de/schildbach/wallet/ui/WalletActivity.java
wallet/src/de/schildbach/wallet/ui/send/SendCoinsFragment.java

Several Issues are being address:
1. Special case of BYR (old currency for Belarus-BY that is still in the locale information of older devices before 2017) did not exist in the price sources and this resulted in a crash after sending a transaction.  This crash was a result of the currency not being found in the price source list, which could also happen if the price sources were not available for a new user who just installed the app.  Code was added to treat BYR as BYN to successfully get an exchange rate.
2. Add a list of currency names for non ISO 4217 currencies that are returned by the price sources
3. Add a list of currency codes that should be treated as other codes for the purposes of getting the name.  This applies to non ISO 4218 currency codes that will have the same name as …

Redesign: Set Default Currency [NMA-243]

---

wallet/res/layout/enter_amount_fragment.xml
wallet/src/de/schildbach/wallet/ui/EnterAmountFragment.kt

Fixed by limiting the max number of decimal digits to 6 (number of decimals was already limited).

NMA-317 wallet crashes when try to specify too big amount to Receive

---

wallet/AndroidManifest.xml
wallet/res/layout/activity_welcome.xml
wallet/res/values-hdpi/dimens.xml
wallet/src/de/schildbach/wallet/WalletApplication.java
wallet/src/de/schildbach/wallet/ui/LockScreenActivity.kt
wallet/src/de/schildbach/wallet/ui/SetPinActivity.kt
wallet/src/de/schildbach/wallet/ui/TransactionResultActivity.kt
wallet/src/de/schildbach/wallet/ui/WelcomeActivity.kt

1. Avoid screen blinking when opening the LockScreenActivity from OnboardingActivity (or to be more precise when showing LockScreen after splash screen).
2. Fix the issue that the PIN keyboard is being covered by system navigation on Krip K6 device.
3. Align background positions of WelconeActivity and LockScreenActivity to make the screen transition more fluent.
4. Disable slide-in animation when showing the LockScreenActivity during regular use.
5. (TBA)

Polish up screen transitions and fix other clumsy UI/UX glitches

---

wallet/src/de/schildbach/wallet/ui/scan/ScanActivity.java

Crash stacktrace:
```
2020-01-29 20:35:38.342 32414-870/hashengineering.darkcoin.wallet_test E/AndroidRuntime: FATAL EXCEPTION: cameraThread
Process: hashengineering.darkcoin.wallet_test, PID: 32414
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:8198)
at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1467)
at android.view.ViewRootImpl.invalidateChild(ViewRootImpl.java:1462)
```

Fixed crash when launching QR code scanner on Android 10

---

wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java
wallet/src/de/schildbach/wallet/ui/WalletActivity.java

This addresses two crashes that were found when running the Prelaunch Report on Google
1.  Crash from adding a Spork Listener - solution was to remove it since it wasn't be used
2.  Crash from trying to get the Currency on a Locale that was invalid.  Not sure why this would be the case, but the default currency is set to USD in these cases.

Redesign: Fix crashes from prelaunch report [NMA-366]

---

wallet/res/layout/header_balance_fragment.xml
wallet/res/layout/home_content.xml
wallet/src/de/schildbach/wallet/ui/HeaderBalanceFragment.java

This will replace #344 since it was based on a PR that was updated and had many merge conflicts.

Avoid app bar resizing when hiding/showing wallet balance [v2]

---

wallet/src/de/schildbach/wallet/ui/ExchangeRatesFragment.java

`viewLifecycleOwner` is tied to when the fragment has (and loses) its UI (onCreateView(), onDestroyView()) whereas `this` is tied to the fragment's overall lifecycle (onCreate(), onDestroy()), which may be substantially longer.
It is better to use the `viewLifecycleOwner` but it has to be done in onViewCreated() instead of in onCreate()

NMA-432 Local Currency Crash

---

common/src/main/java/org/dash/wallet/common/InteractionAwareActivity.java
common/src/main/java/org/dash/wallet/common/InteractionAwareActivity.kt
common/src/main/java/org/dash/wallet/common/ResetAutoLogoutTimerHandler.java
uphold-integration/src/main/java/org/dash/wallet/integration/uphold/ui/UpholdAccountActivity.java
uphold-integration/src/main/java/org/dash/wallet/integration/uphold/ui/UpholdSplashActivity.java
wallet/src/de/schildbach/wallet/WalletApplication.java
wallet/src/de/schildbach/wallet/ui/BaseMenuActivity.kt
wallet/src/de/schildbach/wallet/ui/GlobalFooterActivity.kt
wallet/src/de/schildbach/wallet/ui/ReceiveActivity.kt
wallet/src/de/schildbach/wallet/ui/UpholdTransferActivity.kt
wallet/src/de/schildbach/wallet/ui/VerifySeedActivity.kt

Moved InteractionAwareActivity to 'common' module in order to be able to use it in other submodules (ie uphold-integration).
Fixed crash when manipulating UI elements after finishing Activity (in uphold-integration).

NMA-434 wallet crashes when send on uphold account and close uphold window

---

wallet/src/de/schildbach/wallet/ui/PaymentsActivity.kt
wallet/src/de/schildbach/wallet/ui/PaymentsPayFragment.kt

Fixed the issue on Android 10 with updating the status of 'Send to copied address' button in Payments/Send screen based on clipboard content.
Additionally, added observing the clipboard content in order to provide instant feedback if content of clipboard has changed.

NMA-445  Dash Address in Clipboard not detected in Payment Screen

---

wallet/res/layout/fragment_enter_pin.xml
wallet/src/de/schildbach/wallet/WalletApplication.java
wallet/src/de/schildbach/wallet/livedata/EncryptWalletLiveData.kt
wallet/src/de/schildbach/wallet/ui/AppUpgradeActivity.kt
wallet/src/de/schildbach/wallet/ui/CheckPinDialog.kt
wallet/src/de/schildbach/wallet/ui/CheckPinSharedModel.kt
wallet/src/de/schildbach/wallet/ui/OnboardingActivity.kt
wallet/src/de/schildbach/wallet/ui/SetPinViewModel.kt
wallet/src/de/schildbach/wallet/ui/SetupPinDuringUpgradeDialog.kt

Fixed 'IllegalStateException: Not encrypted' crash:
```
2020-03-19 14:27:38.419 11201-11321/hashengineering.darkcoin.wallet_test E/AndroidRuntime: FATAL EXCEPTION: backgroundThread
Process: hashengineering.darkcoin.wallet_test, PID: 11201
java.lang.IllegalStateException: Not encrypted
at com.google.common.base.Preconditions.checkState(Preconditions.java:511)
at org.bitcoinj.wallet.KeyChainGroup.checkPassword(KeyChainGroup.java:468)
at org.bitcoinj.wallet.Wallet.checkPassword(Wallet.java:1399)
at de.schildbach.wallet.ui.CheckWalletPasswordTask$1.run(CheckWalletPasswordTask.java:40)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:214)
at android.os.HandlerThread.run(HandlerThread.java:67) …
```

NMA-446 Crash after upgrade - IllegalStateException: Not encrypted

---

wallet/src/de/schildbach/wallet/ui/AppUpgradeActivity.kt

Fixed crash caused by showing CheckPinDuringUpgradeDialog after finishing AppUpgradeActivity

NMA-447 Check PIN during upgrade to v7 crash

---

wallet/src/de/schildbach/wallet/rates/ExchangeRate.java

This should resolve the exceptions seen on Chinese devices with android 6 and 7.
```
FATAL EXCEPTION: ControllerMessenger
Process: hashengineering.darkcoin.wallet, PID: 1206
java.lang.IllegalArgumentException: Unsupported ISO 4217 currency code: CNH
at java.util.Currency.<init>(Currency.java:40)
at java.util.Currency.getInstance(Currency.java:54)
at de.schildbach.wallet.rates.ExchangeRate.getCurrency(ExchangeRate.java:62)
at de.schildbach.wallet.rates.ExchangeRate.getCurrencyName(ExchangeRate.java:77)
at de.schildbach.wallet.ui.ExchangeRatesFragment$ExchangeRatesAdapter.onBindViewHolder(ExchangeRatesFragment.java:370)
at de.schildbach.wallet.ui.ExchangeRatesFragment$ExchangeRatesAdapter.onBindViewHolder(ExchangeRatesFragment.java:286)
at …
```

NMA-440 Fix Local Currency: Invalid Currency Crash

---

wallet/src/de/schildbach/wallet/util/FingerprintHelper.java

Detecting the fingerprint hardware (isHardwareDetected()) before calling hasEnrolledFingerprints() in order to avoid SecurityException. As suggested here: https://stackoverflow.com/questions/37780080/android-fingerprints-hasenrolledfingerprints-triggers-exception-on-some-samsung

NMA-471 Lock Screen Fingerprint Crash on Android 6

---

wallet/src/de/schildbach/wallet/WalletApplication.java
wallet/src/de/schildbach/wallet/ui/WalletActivity.java

Fixed:
```
Caused by: java.lang.IllegalStateException: 
at org.dash.wallet.integration.uphold.data.UpholdClient.getInstance (UpholdClient.java:128)
at org.dash.wallet.integration.uphold.ui.UpholdAccountActivity.loadUserBalance (UpholdAccountActivity.java:159)
at org.dash.wallet.integration.uphold.ui.UpholdAccountActivity.onResume (UpholdAccountActivity.java:143)
at android.app.Instrumentation.callActivityOnResume (Instrumentation.java:1413)
at android.app.Activity.performResume (Activity.java:7408)
at android.app.ActivityThread.performResumeActivity (ActivityThread.java:3858)
```
The UpholdClient was initialized in WalletActivity, which was causing the lack of initialization if the UpholdAccountActivity was oppened first.

NMA-469 Uphold Related Crashes

---

wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java

- Replace sync percentage calculation (use relative progress rather than absolute)
- broadcast `ACTION_BLOCKCHAIN_STATE `for Network Monitor (no other activity listens for this since https://github.com/dashevo/dash-wallet/commit/10f34a67a47de59c7e0d69a33fb8b2858aa3c07f, #339).  The network monitor needs to know when the blockchain tip has changed so it can display that last 50+ transactions.  It does not need the blockchain state itself (at least not until information about chainlocks needs to be displayed).
- Update blockchain state more regularly, possibly.  This may help the sync notification close more often.  The assumption is made that the `progress `and `doneDownload ` methods may not always trigger the blockchain state to be updated and the notification stays on for a longer …

NMA-453 Fix for Notification / Network Monitor do not update during sync process

---

build.gradle
wallet/cpp/dashj-bls/dashj-bls-signature-wrapper.cpp

This resolves some crashes when processing instantsend and chainlocks.
Another fix to dashj was to remove the infinite loop when the send transaction fails (added for 0.14 nodes, which are not common anymore on the network).

NMA-448 Fix InstantSend/Chainlocks crashes by Updating to dashj 0.17.1

---

wallet/src/de/schildbach/wallet/WalletApplication.java

Prevent Auto Logout functionality from trying to lock the app before wallet is initialized

NMA-480  Lock Screen Crash: Set Backup Reminder

---

wallet/src/de/schildbach/wallet/ui/PaymentsPayFragment.kt
wallet/src/de/schildbach/wallet/ui/WalletActivity.java

Some browsers such as Chrome put data in the clipboard as HTML text to keep formatting. The exact copied text can be easily extracted from such a data with `getText()` method.

NMA-484 Handle Addresses in HTML from Clipboard

---

wallet/src/de/schildbach/wallet/ui/LockScreenActivity.kt

Fixed the crash when starting regular (not background) service in `Activity.onStart()` method caused by bug in Android P

NMA-479 Lock Screen Crash: Starting Blockchain Service

---

wallet/res/layout/dialog_new_account_confirm.xml
wallet/res/values/strings-extra.xml
wallet/src/de/schildbach/wallet/ui/CreateUsernameActivity.kt
wallet/src/de/schildbach/wallet/ui/dashpay/ProcessingIdentityViewHolder.kt

- Added back the changes from 4ba7c39e incorrectly removed when resolving merge conflicts (#386)
- Changed the minimum required user name length from 4 to 3 characters
- Fixed the typo in account confirm message

QA result fixes

---

wallet/AndroidManifest.xml
wallet/src/de/schildbach/wallet/ui/PaymentsPayFragment.kt
wallet/src/de/schildbach/wallet/ui/SendCoinsQrActivity.java
wallet/src/de/schildbach/wallet/ui/SendingAddressesFragment.java
wallet/src/de/schildbach/wallet/ui/TransactionResultActivity.kt
wallet/src/de/schildbach/wallet/ui/WalletActivity.java
wallet/src/de/schildbach/wallet/ui/WalletUriHandlerActivity.java
wallet/src/de/schildbach/wallet/ui/send/PaymentProtocolFragment.kt
wallet/src/de/schildbach/wallet/ui/send/SendCoinsActivity.java
wallet/src/de/schildbach/wallet/ui/send/SendCoinsFragment.java
wallet/src/de/schildbach/wallet/ui/send/SendCoinsInternalActivity.java
wallet/src/de/schildbach/wallet/ui/send/SweepWalletFragment.java

Added SendCoinsInternalActivity being not exported version of SendCoinsActivity extended with ability to be authorised internally.
Closing the app if it was launched by external Intent.

NMA-473 Payment Request from another app gets stuck on Transaction Result Screen

---

wallet/res/layout/home_content.xml

The top is before, the bottom is after the change in this PR.

Home Screen: Center Dash Symbol

---

wallet/src/de/schildbach/wallet/WalletApplication.java
wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java

Always promote the `BlockchainServiceImpl` service to the foreground to avoid RemoteServiceException on Android 8 when `onCreate` takes too long.
An interesting discussin about this issue: https://stackoverflow.com/questions/44425584/context-startforegroundservice-did-not-then-call-service-startforeground
it seems that to completely get rid of this issue we will have to replace the AlarmManager based solution with the JobScheduler-based.
For now let's just see if this codes change anything.

NMA-485 Attempt to resolve RemoteServiceExceptions on Oreo

---

wallet/res/values/strings-extra.xml
wallet/src/de/schildbach/wallet/ui/dashpay/ProcessingIdentityViewHolder.kt

- Removed step 4 of username registration process to align with designs.
- Removed string for step 4 and it's access/usage from `ProcessingIdentityViewHolder`

fix: removed step 4 from ui of username registration.

---

wallet/src/de/schildbach/wallet/ui/CreateUsernameActivity.kt
wallet/src/de/schildbach/wallet/ui/dashpay/CreateIdentityService.kt

The UI freeze on the Create Username Screen, after pressing the Register Button.  The animation freezes in the next screen, possibly while the Create Identity Service is started.
Fixed a bug causing the `deriveKey(...)` and `decryptSeed(...)` methods in the `CreateIdentityService` to be executed on main thread.
My own tests and QA validation
N/A

[NMA-513]:  Username Registration Freeze (UI)

---

wallet/res/layout/nav_header_main.xml
wallet/res/layout/transaction_result_content.xml
wallet/res/layout/view_payment_request_details.xml

Crash on KitKat when displaying the transaction details or BIP70 transaction details.
Replaced `android:drawableStart` with `app:drawableStartCompat` in two `TextViews`
Displayed the transaction details screen and performed BIP70 payment on KitKat.
QA validation.
N/A

[NMA-526]: Transaction Details Crashes on Android 4.4

---

ui-redesign/src/main/res/drawable/aqua_green_button.xml
ui-redesign/src/main/res/drawable/medium_gray_button.xml
ui-redesign/src/main/res/drawable/transparent_button_golden_text.xml
ui-redesign/src/main/res/values/colors.xml
ui-redesign/src/main/res/values/styles.xml
wallet/AndroidManifest.xml
wallet/res/layout/activity_dashpay_user.xml
wallet/res/layout/activity_search_dashpay_profile_1.xml
wallet/res/layout/activity_search_dashpay_profile_root.xml
wallet/res/values/strings-extra.xml
wallet/src/de/schildbach/wallet/data/DashPayProfile.kt
wallet/src/de/schildbach/wallet/data/UsernameSearchResult.kt
wallet/src/de/schildbach/wallet/ui/DashPayUserActivity.kt
wallet/src/de/schildbach/wallet/ui/HeaderBalanceFragment.java
wallet/src/de/schildbach/wallet/ui/SearchUserActivity.kt
wallet/src/de/schildbach/wallet/ui/UserAvatarPlaceholderDrawable.kt
wallet/src/de/schildbach/wallet/ui/UsernameSearchResultsAdapter.kt
wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt

- Created layout for User representation when clicking on a result from user search, with its respective sections for sending/accepting contact requests. (`DashPayUserActivity`)
- Fixed small visual bug in `SearchUserActivity` where the results were being clipped at the end of the screen. (`activity_search_dashpay_profile…`)
- Added `fromDocument` method in `DashPayProfile` class to allow its creation from a Platform Document.
- Created `UserAvatarPlaceholderDrawable` class to show a default avatar image with the first letter of the username. This class is being used at home screen, search results and user screen. (`HeaderBalanceFragment`, `UsernameSearchResultsAdapter`, `DashPayUserActivity`)

Contact Request UI - Part 1

---

wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt

getStatus() fails with INTERNAL (internal error 80-90% of the time)

Fix platform availability

---

wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java

Avoid crash if the BlockchainServiceImpl was started before wallet initialization.
This should basically never happen but we've got a few such crashes in the Google Play console.
Added wallet initialization checking in _BlockchainServiceImpl.onStartCommand_ and _BlockchainServiceImpl.onCreate_

NMA-517 Blockchain Service Start Crash (wallet not initialized)

---

wallet/src/de/schildbach/wallet/ui/DashPayUserActivity.kt
wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt

Prevents sending a Contact Request to users which ids have less than 44 characters since DashPay Contract requires this specific length for now. This code will be removed after the DashPay Contract is upadet to allow contact request to such users since they're valid users.

Handling toUserId length error

---

wallet/res/values/strings-extra.xml
wallet/src/de/schildbach/wallet/ui/dashpay/ContactSearchResultsAdapter.kt
wallet/src/de/schildbach/wallet/ui/dashpay/ContactsActivity.kt

Modify **ContactsActivity** to show only pending contact requests when the user clicks "view all".
This should be merged after #440

NMA-332 View Pending Requests | Incoming (UI)

---

wallet/build.gradle
wallet/res/layout/contact_request_row.xml
wallet/res/layout/dashpay_profile_row.xml
wallet/res/layout/notification_contact_request_received_row.xml
wallet/src/de/schildbach/wallet/ui/DashPayUserActivity.kt
wallet/src/de/schildbach/wallet/ui/SearchUserActivity.kt
wallet/src/de/schildbach/wallet/ui/UsernameSearchResultsAdapter.kt
wallet/src/de/schildbach/wallet/ui/dashpay/ContactSearchResultsAdapter.kt
wallet/src/de/schildbach/wallet/ui/dashpay/ContactsActivity.kt
wallet/src/de/schildbach/wallet/ui/dashpay/NotificationsActivity.kt
wallet/src/de/schildbach/wallet/ui/dashpay/NotificationsAdapter.kt
wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt

Add functionality to Accept buttons to accept a contact request
There are many screens that have an Accept Button:
1. Notifications Screen - when the request is accepted, the contact request should change into a contact. 
2. Contacts Screen  - when the request is accepted, the contact request should be removed from the Contact Requests section and appear in the My Contacts section (screen refresh)
3. Contact Requests Screen - when the request is accepted, the contact request should disappear
4. DashPay User Screen - when the request is accepted, the Accept and Ignore Buttons should disappear.  Returning to the previous screen should show the current state of the request (no accept or ignore buttons)
known issues:
1. There are periodic failures from platform (UNAVAILABLE)
2. The Home …

NMA-330: DashPay:  Accept Contact Request

---

.deploy/deploy.sh

Added missing $ prefix when assigning variable causing the deploy directory to be named `DEPLOY_TYPE` instead of DashPay/master

Fix issue with automatic deploy of evonet-develop branch

---

wallet/AndroidManifest.xml
wallet/src/de/schildbach/wallet/WalletApplication.java
wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java
wallet/src/de/schildbach/wallet/service/BlockchainSyncJobService.kt

Using JobScheduler instead of AlarmManager to trigger periodic blockchain sync on Android 8.0 and 8.1

Another attempt to fix the KRIP crash on Android 8.0/8.1

---

common/src/main/java/org/dash/wallet/common/InteractionAwareActivity.java
wallet/src/de/schildbach/wallet/ui/AbstractWalletActivity.java
wallet/src/de/schildbach/wallet/ui/RestoreFromFileActivity.kt
wallet/src/de/schildbach/wallet/ui/SetPinActivity.kt

NMA-412
Hide the view of any screen in the app when shown in the recent app list.  This uses the FLAG_SECURE flag when an activity is paused, and removes this flag when the activity is resumed.

Hide contents on app task list

---

wallet/res/anim/slide_out_right.xml
wallet/src/de/schildbach/wallet/ui/VerifySeedActivity.kt
wallet/src/de/schildbach/wallet/ui/VerifySeedBaseFragment.kt
wallet/src/de/schildbach/wallet/ui/VerifySeedConfirmFragment.kt
wallet/src/de/schildbach/wallet/ui/VerifySeedItIsImportantFragment.kt
wallet/src/de/schildbach/wallet/ui/VerifySeedSecureNowFragment.kt
wallet/src/de/schildbach/wallet/ui/VerifySeedWriteDownFragment.kt

Add the back button to the VerifySeed related screens, with animation that is the opposite of going forward in the screens.
None

Add back button to Passphrase Screen (NMA-456)

---

wallet/src/de/schildbach/wallet/ui/LockScreenActivity.kt

NMA-587
Lock Screen issues
1. Remove overlap of PIN keyboard with navbar
2. Remove gap for navbar on Krip Devices
none

Fix LockScreen Keyboard Placement

---

wallet/src/de/schildbach/wallet/WalletApplication.java
wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java

This is a new way of fixing the crash when the BlockchainServiceImpl started before wallet initialization (#448)
NMA-594

Cancel scheduled blockchain sync when wiping the wallet

---

wallet/README.md

"This project is forked from [bitcoinj] https://bitcoinj.github.io/" - now bitcoinj will appear as a link, I think that was the original intention.

Fixing link formatting typo: [text](URL)

---

wallet/res/layout/activity_main.xml
wallet/src/de/schildbach/wallet/ui/widget/KeyboardResponsiveCoordinatorLayout.java

NMA-609 Missing Footer

---

wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java

Original order: DNS Seeders, DMN Masternode List, Hard coded Seeds which are Masternodes
New Order:  DMN Masternode List, Hard coded Seeds which are Masternodes, DNS Seeders (will only be used if the previous two return less than 16 total nodes)
None
None

Change order that is used to connect to peers (DNM, seeds, dns seeders)

---

wallet/res/drawable/ic_dash_round.xml
wallet/res/layout/transaction_row.xml
wallet/src/de/schildbach/wallet/ui/MainActivity.kt
wallet/src/de/schildbach/wallet/ui/MainActivityViewModel.kt
wallet/src/de/schildbach/wallet/ui/TransactionsAdapter.java
wallet/src/de/schildbach/wallet/ui/WalletTransactionsFragment.java
wallet/src/de/schildbach/wallet/ui/dashpay/TransactionsViewModel.kt
wallet/src/de/schildbach/wallet/ui/dashpay/WalletBalanceBasedLiveData.kt
wallet/src/de/schildbach/wallet/ui/dashpay/WalletBalanceLiveData.kt

NMA-603 | (Contacts in) Transaction History | Home Screen

---

common/src/main/java/org/dash/wallet/common/Configuration.java
wallet/res/xml/file_provider.xml
wallet/src/de/schildbach/wallet/Constants.java
wallet/src/de/schildbach/wallet/ui/EditProfileActivity.kt
wallet/src/de/schildbach/wallet/ui/dashpay/EditProfileViewModel.kt

Base on https://developer.android.com/training/camera/photobasics#kotlin
and https://medium.com/@quiro91/sharing-files-through-intents-part-2-fixing-the-permissions-before-lollipop-ceb9bb0eec3a
https://dashpay.atlassian.net/browse/NMA-418
https://github.com/dashevo/dash-wallet/pull/528

Fixed the crash when taking picture on KitKat

---

wallet/src/de/schildbach/wallet/ui/send/SendCoinsFragment.java

Not loading user from a scanned QR if the wallet has no registered user.

NMA-640 | Scan QR Code | Backward Compatibility

---

wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt

N/A - This is a critical bug fix.  Contact Requests were not showing up on the Notifications or Contacts Screens, nor was there a Notification on the home screen.  This was due to the updateContactRequests and related code not saving a blank profile to the database if it was not found on Platform.
This bug originated from this PR: https://github.com/dashevo/dash-wallet/pull/528/commits/9e77c31f5a7ea1432d9c51977401e5dbdee9e8c9, which was a fix to a problem where non-empty profiles were replaced with blank profiles.

DashPay: missing profiles

---

wallet/AndroidManifest.xml
wallet/proguard.cfg
wallet/src/de/schildbach/wallet/data/ImgurUploadResponse.kt
wallet/src/de/schildbach/wallet/ui/EditProfileActivity.kt
wallet/src/de/schildbach/wallet/ui/dashpay/EditProfileViewModel.kt

Fixed KotlinReflectionInternalError: Could not compute caller for function: public constructor ImgurUploadResponse crash

Fixed Imgur upload crashes

---

wallet/res/values/strings-extra.xml
wallet/src/de/schildbach/wallet/ui/AbstractBindServiceActivity.java

Fixed the `IllegalArgumentException: Service not registered` crash found by QA on Android 4.4.
Fix base on https://stackoverflow.com/a/48589803/795721
NMA-589 Spanish/Krip Issues: Dash Pay Features

IllegalArgumentException: Service not registered crash

---

wallet/src/de/schildbach/wallet/ui/BackupWalletDialogFragment.java
wallet/src/de/schildbach/wallet/ui/send/SweepWalletFragment.java

NMA-685 (Backup to File)
NMA-552 (Import Private Key)
This PR should fix some of the most common crashes with the app.
N/A
N/A

Fix failure message crashes

---

wallet/src/de/schildbach/wallet/data/DashPayContactRequestDao.kt
wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt

NMA-715
Originally, the app would always get the most recent contact request during a query, but this will modify it so that if it does get a contact request that we already have, then it is ignored.  Additionally, after a short period of time of receiving a contact request, it won't be included in future queries.
as a result, the contacts updated listeners won't be triggered every 15 seconds, when there are no new contact requests.

DashPay: Only add new ContactRequests to the db/listeners

---

wallet/src/de/schildbach/wallet/ui/EditProfileActivity.kt

NMA-762
This should prevent the edit profile screen from forgetting changes made to the profile before saving.
None
None

NMA-762: DashPay:  Fix Edit Profile - forgets any changes

---

common/src/main/java/org/dash/wallet/common/Configuration.java
wallet/res/layout/activity_search_dashpay_profile_1.xml
wallet/res/values/strings-extra.xml
wallet/src/de/schildbach/wallet/ui/AboutActivity.kt
wallet/src/de/schildbach/wallet/ui/CreateUsernameActivity.kt
wallet/src/de/schildbach/wallet/ui/MainActivity.kt
wallet/src/de/schildbach/wallet/ui/MoreFragment.kt
wallet/src/de/schildbach/wallet/ui/SearchUserActivity.kt
wallet/src/de/schildbach/wallet/ui/dashpay/ContactsFragment.kt
wallet/src/de/schildbach/wallet/ui/dashpay/NotificationsActivity.kt
wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt
wallet/src/de/schildbach/wallet/ui/invite/InviteFriendActivity.kt
wallet/src/de/schildbach/wallet/ui/widget/KeyboardResponsiveConstraintLayout.java

To allow for QA testing before all invitation features are completed, I would like to be able to show/hide the entry points.
Acceptance Criteria
- The invitation entry points should be hidden by default
- Invitation notifications should be suppressed if the entry points are hidden
- The user should be able to show/hide the entry points after shaking the device in the About screen
Screens affected
- Contacts Screen (with no contacts)
- Search User Screen (before clicking on the search box)
- Search User Screen (after entering a search with no results)
- More Screen
- Notifications Screen
About Screen show say “Developer mode activated” and “Developer mode deactivated” when the screen is shaken.  Activated means that the Invite UI appears at all of the 5 above screens.  Deactivated means …

NMA-818 DashPay:  Hide Invite Entry Points

---

wallet/src/de/schildbach/wallet/ui/dashpay/utils/ProfilePictureDisplay.kt

Changed the custom signature of profile pictures in order to avoid image pulsing when refreshing the data

NMA-828  Home Screen | Pulsing Profile Picture

---

wallet/src/de/schildbach/wallet/ui/send/SendCoinsFragment.java

NMA-797
The app crashed after scanning the wallet's own QR code.  This is like trying to pay ourselves as a contact.

NMA-797: DashPay: Prevent Crash when Scanning Own QR Code

---

common/src/main/java/org/dash/wallet/common/Configuration.java
wallet/src/de/schildbach/wallet/ui/HeaderBalanceFragment.java
wallet/src/de/schildbach/wallet/ui/MainActivity.kt
wallet/src/de/schildbach/wallet/ui/RestoreWalletActivity.java
wallet/src/de/schildbach/wallet/ui/RestoreWalletFromFileViewModel.kt
wallet/src/de/schildbach/wallet/ui/RestoreWalletFromSeedViewModel.kt
wallet/src/de/schildbach/wallet/ui/dashpay/NotificationCountLiveData.kt
wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt

Restoring a wallet is from a file or recovery phrase
Consider all old notifications as Earlier instead of new

NMA-830: DashPay: Don't Show notifications when restoring until after sync is finished

---

build.gradle
wallet/build.gradle

* Our libs are now on maven central
This should be transparent from the user.  Get the dashj-*-android libraries from Maven Central instead of JCenter/bintray

build: Remove bintray (NMA-821)

---

wallet/src/de/schildbach/wallet/ui/send/PaymentProtocolFragment.kt

This will prevent the Lock Screen from appearing when a BIP70 payment request is performed by another app.

fix: remove Lock Screen from Tx Details Screen after BIP70 request (NMA-944)

---

wallet/src/de/schildbach/wallet/ui/OnboardingActivity.kt
wallet/src/de/schildbach/wallet/ui/RestoreWalletFromSeedActivity.kt
wallet/src/de/schildbach/wallet/ui/SetPinActivity.kt
wallet/src/de/schildbach/wallet/ui/backup/RestoreFromFileActivity.kt

As of v7.2.4, it was possible to finish onboarding and from the Home Screen return to the Onboarding screen.

fix: prevent returning to onboarding screen after finishing onboarding (NMA-941)

---

build.gradle
wallet/build.gradle

Building dashpay branch produces "Could not find org.dashj:dashj-core:0.18-SNAPSHOT." error.
Fixed by moving sonatype repository from wallet level to the allprojects scope since most modules are referencing dashj.

fix: dashpay sonatype repo

---

wallet/src/de/schildbach/wallet/ui/CheckPinDialog.kt
wallet/src/de/schildbach/wallet/ui/DecryptSeedWithPinDialog.kt
wallet/src/de/schildbach/wallet/ui/LockScreenActivity.kt
wallet/src/de/schildbach/wallet/ui/ViewSeedActivity.kt

fix: close pin authentication dialog for view recovery phrase on autologout (NMA-952)

---

common/src/main/java/org/dash/wallet/common/AutoLogoutTimerHandler.java
common/src/main/java/org/dash/wallet/common/InteractionAwareActivity.java
liquid-integration/src/main/java/org/dash/wallet/integration/liquid/ui/BuyDashWithCreditCardActivity.kt
liquid-integration/src/main/java/org/dash/wallet/integration/liquid/ui/BuyDashWithCryptoCurrencyActivity.kt
liquid-integration/src/main/java/org/dash/wallet/integration/liquid/ui/LiquidBuyAndSellDashActivity.kt
liquid-integration/src/main/java/org/dash/wallet/integration/liquid/ui/LiquidSplashActivity.kt
liquid-integration/src/main/java/org/dash/wallet/integration/liquid/ui/WebViewActivity.kt
liquid-integration/src/main/res/layout/dialog_buy_dash.xml
sample-integration-android/build.gradle
uphold-integration/src/main/java/org/dash/wallet/integration/uphold/ui/UpholdAccountActivity.java
uphold-integration/src/main/java/org/dash/wallet/integration/uphold/ui/UpholdSplashActivity.java
wallet/src/de/schildbach/wallet/WalletApplication.java

Disabling wallet timer while in the CustomTab or webview so that the Linking Process or buy/sell can complete.

[NMA-954] Turning off uphold/liquid auto logout

---

.github/workflows/dashwallet.yml
.github/workflows/manual_distribution.yml

Changed run_number which is local to a workflow to run_id which is global to the repo. Changed test group to real QA group.
https://github.com/dashevo/dash-wallet/pull/741

Github Actions fixes: github run_id instead of run_number and correct test group

---

.github/workflows/dashwallet.yml
.github/workflows/manual_distribution.yml

run_id isn't an incremental number, but just a unique random number, so we shouldn't use it. Changed back to run_id for manual workflow. For dash wallet workflow, we can leave base build number 70000 for all builds.
https://github.com/dashevo/dash-wallet/pull/743
https://github.com/dashevo/dash-wallet/pull/741

Github Actions fix: reversing to run_number

---

wallet/AndroidManifest.xml

NMA-997
Documentation related to the Strandhogg v1 fix indicates that all activities or `application` need the `taskAffinity=""` value set.
If we do this, will some of our `magical` fixes to get around a new task being created with intents from other apps (web browsers, custom tabs, invites) still be necessary?
When this is merged into the `dashpay` branch, there may be other activities with `taskAffinity=""` that could be changed.

refactor: set application taskAffinity="" instead of each activity (NMA-997)

---

.github/workflows/manual_distribution.yml
wallet/src/de/schildbach/wallet/ui/SendCoinsQrActivity.java
wallet/src/de/schildbach/wallet/ui/send/SendCoinsActivity.java
wallet/src/de/schildbach/wallet/ui/send/SendCoinsInternalActivity.java

There are many ways to initiate a payment flow.
We found that from the Lock Screen, after pressing Scan to Pay and scanning a QR code, then the Lock Screen was displayed again.
In this particular payment flow, the Lock Screen should not be displayed.

fix: keep payment flow unlocked if activated from Lock Screen (NMA-1011)

---

wallet/src/de/schildbach/wallet/ui/AdvancedSecurityActivity.kt

It seems like this issue was already fixed for view recovery phrase screen, but not for advanced security. I used the same code to keep it consistent.
https://github.com/dashevo/dash-wallet/pull/706

[NMA-978] Advanced Security / View Recovery Phrase AutoLogout Issue

---

liquid-integration/src/main/java/org/dash/wallet/integration/liquid/ui/BuyDashWithCreditCardActivity.kt
liquid-integration/src/main/res/layout/activity_webview_quick_exchange.xml

Show the close button again after making a purchase from Liquid.
remove the use of findViewById since we are using view bindings.

fix: enable the close button after a purchase (NMA-1014)

---

wallet/src/de/schildbach/wallet/ui/LockScreenActivity.kt

The fix there it to ensure that LockScreenActivity has the correct state in the `isLocked` field.
Then MainActivity can use this field that will have the correct value to determine how to handle an invite.

fix: update locked state when activity is created and app is locked

---

sample-integration-android/build.gradle

* this prevents a build error with Gradle 6.7.1
* Enable Sample Integration app builds
* Resolve CI/Manual Distribution build failures

fix: build sample-integration-android with SDK 30

---

wallet/res/values/strings-extra.xml
wallet/src/de/schildbach/wallet/ui/explore/ExploreTestNetFragment.kt

Change behavior.  Copy next Address to clipboard before activating faucet link.

feat: copy address on button click then do faucet link - NMA-1081

---

wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt

After using an invite and before the app was restarted, some security preferences were not available.  Initialize SecurityGuard when it is needed, rather than as a member field of PlatformRepo.

Bugfix: incomplete received contact requests, 

---

wallet/src/de/schildbach/wallet/ui/dashpay/work/SendInviteWorker.kt

On Android 6, `StandardCharsets.UTF_8.toString()` is rendered as "java.nio.charset.CharsetICU[UTF-8]" which results in this crash:
```
Non-fatal Exception: java.nio.charset.IllegalCharsetNameException
java.nio.charset.CharsetICU[UTF-8]
java.nio.charset.Charset.checkCharsetName (Charset.java:201)
java.nio.charset.Charset.forName (Charset.java:295)
java.net.URLEncoder.encode (URLEncoder.java:57)
de.schildbach.wallet.ui.dashpay.work.SendInviteWorker.createDynamicLink (SendInviteWorker.java:126)
de.schildbach.wallet.ui.dashpay.work.SendInviteWorker.doWorkWithBaseProgress (SendInviteWorker.java:103) 
```

Bugfix:  dashpay android 6 invite creation failure (NMA-1096)

---

.github/workflows/dashwallet.yml
.github/workflows/manual_distribution.yml

Fixing ruby action in github actions pipelines.
`actions/setup-ruby` isn't maintained anymore and needs to be replaced with `ruby/setup-ruby`.

fix: migrating from actions/setup-ruby to ruby/setup-ruby

---

common/src/main/java/org/dash/wallet/common/ui/BaseBottomSheetDialogFragment.kt
wallet/src/de/schildbach/wallet/ui/TransactionsFilterDialog.kt
wallet/src/de/schildbach/wallet/ui/VerifySeedWarningDialog.kt
wallet/src/de/schildbach/wallet/ui/receive/ReceiveDetailsDialog.kt
wallet/src/de/schildbach/wallet/ui/send/ConfirmTransactionDialog.kt

Move **_BaseBottomSheetDialogFragment_** from `wallet` to `common` module to make it accessible throughout the app

refactor: move BaseBottomSheetDialogFragment to common module

---

features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/SearchFragment.kt

The `merchant info screen` should be automatically displayed for the first time only when we enter the Merchant search

fix: remove automatic display of merchant info screen in ATM search

---

wallet/src/de/schildbach/wallet/ui/EnterAmountFragment.kt
wallet/src/de/schildbach/wallet/ui/ExchangeRatesActivity.java
wallet/src/de/schildbach/wallet/ui/ExchangeRatesFragment.java
wallet/src/de/schildbach/wallet/ui/SettingsActivity.kt

After making a payment with non-default currency, opening the currency selector again shows the wrong currency.
The way I see it, the problem here is that we have a bunch of code in the `ExchangeRatesFragment` to decide which currency to show as selected. Because this code is independent of the one in the Enter Amount screen, it can get unsynchronized and we will have different currencies.
To prevent this problem from occurring again, we should move the responsibility of deciding selected currency to the caller of `ExchangeRatesFragment`, it itself should not make this decision unless no currency is specified. This way, whichever currency the caller has as default, `ExchangeRatesFragment` will have as selected.

[NMA-1105] Currency selector problems

---

features/exploredash/src/main/java/org/dash/wallet/features/exploredash/repository/ExploreRepository.kt
wallet/src/de/schildbach/wallet/ExploreSyncWorker.kt
wallet/src/de/schildbach/wallet/WalletApplication.java

Sync worker fails to run sometimes with a firebase error “client is offline” even though the connection is present.
It's not 100% clear what is the problem, but it might be related to the usage of `await()` method from the `kotlinx-coroutines-play-services`, even though this issue was apparently [fixed a while ago](https://github.com/firebase/firebase-android-sdk/issues/2385). I moved all of the firebase data fetching methods from `await()` back to `addListenerForSingleValueEvent` just in case this is the problem.
Another possibility is that this is simply due to connection problems, hence I've added an exponential backoff retrying policy.

[NMA-1115] (Explore Dash) Possible fix for sync worker issues

---

wallet/src/de/schildbach/wallet/ui/SettingsActivity.kt

If a user in the US tries to change the default currency immediately after the installation, it will get reset back to USD after exiting the settings. This happens because `onResume` method is called in `MainActivity` and it triggers country detection again (this only happens in DashPay for some reason).
`detectUserCountry` will not run if `exchangeCurrencyCodeDetected` is set. This property is used to detect unintended changes in the currency and show a dialog asking which one to keep. We can set it preemptively after the user changed the default currency, assuming that if it's changed explicitly, we don't need to confirm it with a dialog.

[NMA-1100] the local currency is not changed in the first time after installation

---

common/src/main/java/org/dash/wallet/common/ui/enter_amount/AmountView.kt
integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/ui/CoinbaseBuyDashFragment.kt

Toggling between dash and fiat causes input to have ".00" ending which prevents further input.
Another issue I've noticed is that when toggling, dash amount sometimes gets small fractions added or substructed.
- Allow formatting input without a fractional part if it's not needed.
- Since we're anchoring to Dash when toggling between dash and fiat, I changed the logic to keep dash amount static instead of calculating it from the fiat input.

[NMA-1111] Enter Amount fixes

---

features/exploredash/src/main/java/org/dash/wallet/features/exploredash/data/ExploreDataSource.kt
features/exploredash/src/main/java/org/dash/wallet/features/exploredash/data/MerchantDao.kt
features/exploredash/src/test/java/org/dash/wallet/features/exploredash/MerchantAtmDataSourceTest.kt

Merchants are sorted Physical -> Both -> Online in the All tab when location is enabled, while Physical and Both should be in the same group. This is a side effect of sorting Online -> Both -> Physical for the case when location is disabled.
Fixed by explicitly specifying the sort order for the Physical merchants.

[NMA-1138] (Explore Dash) Fix: All tab ordering

---

common/src/main/java/org/dash/wallet/common/ui/FancyAlertDialog.kt
wallet/src/de/schildbach/wallet/ui/FancyListFragment.java
wallet/src/de/schildbach/wallet/ui/LockScreenActivity.kt

There is a crash in `LockScreenActivity.getLockScreenViewModel` which is related to Hilt:
```
Fatal Exception: java.lang.IllegalArgumentException
SavedStateProvider with the given key is already registered
androidx.savedstate.SavedStateRegistry.registerSavedStateProvider (SavedStateRegistry.java:111)
androidx.lifecycle.AbstractSavedStateViewModelFactory.create (AbstractSavedStateViewModelFactory.java:84)
dagger.hilt.android.internal.lifecycle.HiltViewModelFactory.create (HiltViewModelFactory.java:109)
```
This is probably happening because in the FancyAlertDialog, `LockScreenViewModel` is initialized with fragment as an owner instead of an activity.
Replaced initializations with activity as owner.

[NMA-1123] Bugfix: lockscreen viewmodel crash

---

features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/ExploreViewModel.kt
wallet/src/de/schildbach/wallet/WalletApplication.java

When the user switches the filter tab, e.g. from All to Online, the results of the All tab are still showing for a short while before Online results are loaded. This might introduce some confusion.
Clearing search results immediately after switching a tab.
Additionally, I've changed `ExistingWorkPolicy` to `Keep` for the explore sync worker so that the ongoing work doesn't get interrupted (which seems to be a cause of failed synchronization in some cases).

[NMA-1145] (Explore Dash) Clearing results on switching filter tab

---

features/exploredash/src/main/java/org/dash/wallet/features/exploredash/data/AtmDao.kt
features/exploredash/src/main/java/org/dash/wallet/features/exploredash/data/ExploreDataSource.kt
features/exploredash/src/main/java/org/dash/wallet/features/exploredash/data/MerchantDao.kt
features/exploredash/src/main/java/org/dash/wallet/features/exploredash/data/model/AtmFTS.kt
features/exploredash/src/main/java/org/dash/wallet/features/exploredash/data/model/MerchantFTS.kt
features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/ExploreMapFragment.kt
features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/ExploreViewModel.kt
features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/ItemDetails.kt
features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/SearchFragment.kt
features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/adapters/SearchHeaderAdapter.kt
features/exploredash/src/test/java/org/dash/wallet/features/exploredash/MerchantAtmDataSourceTest.kt
wallet/build.gradle
wallet/src/de/schildbach/wallet/data/AppDatabaseMigrations.kt

We want to show a full details card for `both` merchants even if opened from the Online tab.
Additionally, when details are opened and then the user goes back to the search screen, the search query is erased but search results are still filtered.
The last fix is grouping in the Online tab, which was by name but should be by the distance.
- Removed all conditions that limit the full details card from opening in `FilterMode.Online` and only left checks for `MerchantType.Online`.
- Now setting search text explicitly when transitioning to the SearchResults screen mode.
- Changed grouping in Online tab to be by a Pythagorean formula like in all the other cases.

[NMA-1141 && NMA-1139 && NMA-1153] Explore Dash fixes

---

wallet/src/de/schildbach/wallet/ui/CheckPinDialog.kt

There is a crash if CheckPinDialog is created during a wait period from entering the incorrect PIN.

fix: use context parameter instead of calling requireContext

---

features/exploredash/src/main/java/org/dash/wallet/features/exploredash/data/model/Atm.kt
features/exploredash/src/main/java/org/dash/wallet/features/exploredash/data/model/Merchant.kt
features/exploredash/src/main/java/org/dash/wallet/features/exploredash/data/model/SearchResult.kt
features/exploredash/src/main/java/org/dash/wallet/features/exploredash/repository/AssetExploreRepository.kt
features/exploredash/src/main/java/org/dash/wallet/features/exploredash/repository/ExploreRepository.kt

Speed-up data preloading by reusing Moshi and Scanner instances (~70% faster)

[NMA-1171] Preload the Dash Explore data and disable remote sync (hotfix) - optimization

---

common/src/main/java/org/dash/wallet/common/ui/BaseDialogFragment.kt
wallet/src/de/schildbach/wallet/WalletApplication.java
wallet/src/de/schildbach/wallet/ui/ResetWalletDialog.kt

There is a crash in the `OnboardingActivity` on the "Wallet is permanently locked" screen, when the user tries to initiate a reset dialog. It happens because `BaseDialogFragment` is annotated as `@AndroidEntryPoint`, while the `OnboardingActivity` isn't.
A couple of changes are made:
- We could annotate `OnboardingActivity` as `@AndroidEntryPoint`, however, the fact that the `BaseDialogFragment` is annotated creates various side effects around the app (like this bug). It's better to avoid  `@AndroidEntryPoint` in the dialogs, so I have removed it and made related changes.
- Given that the `BaseDialogFragment` is obsolete and unnesasary (`DialogFragments` are dismissed automatically now), I have uncoupled the `ResetWalletDialog` from it.

[NMA-1190] fix: Hilt crash in OnboardingActivity

---

wallet/src/de/schildbach/wallet/ui/AboutActivity.kt

There is a small bug that prevents text on the About screen from being copied. `ClipboardManager` gets text from itself instead of a TextView.

fix: copying text on the About screen

---

common/src/main/java/org/dash/wallet/common/services/analytics/AnalyticsConstants.kt
features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/ExploreFragment.kt
features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/dialogs/ExploreDashInfoDialog.kt

Track with Firebase click events from Explore Dash Portal and Dialog Info screens

feat: track firebase events from explore dash portal and info screens

---

wallet/res/values/strings-extra.xml
wallet/src/de/schildbach/wallet/ui/OnboardingActivity.kt
wallet/src/de/schildbach/wallet/ui/OnboardingViewModel.kt
wallet/src/de/schildbach/wallet/ui/SetPinActivity.kt
wallet/src/de/schildbach/wallet/ui/SetPinViewModel.kt

v6 and v5 wallets will go to the Set Pin screen during the upgrade process if the app doesn't have a PIN set.

fix: finish onboarding if upgrading with unencrypted wallet

---

wallet/src/de/schildbach/wallet/ui/WalletActivity.java

To avoid NRE in the `onCreate` code, the viewModel should be initialized early on.

fix: initializing MainViewModel earlier in WalletActivity

---

wallet/src/de/schildbach/wallet/AutoLogout.java

After entering the Liquid or Uphold screens, the autologout timer was accelerated.
Each time `startTimer` was called, a new timer was created.  The fix is to prevent creating a new timer if one is active.
None

fix: autologout in Exchange integrations (NMA-1307)

---

common/src/main/java/org/dash/wallet/common/ui/dialogs/AdaptiveDialog.kt

A progress dialog is sometimes crashing if dismissed while not attached to an activity.

[NMA-1303] Fix: 'not assosiated with a fragment manager' crash

---

common/src/main/res/values/colors.xml
integrations/crowdnode/src/main/java/org/dash/wallet/integrations/crowdnode/api/CrowdNodeApi.kt
integrations/crowdnode/src/main/java/org/dash/wallet/integrations/crowdnode/model/ApiStatuses.kt
integrations/crowdnode/src/main/res/layout/fragment_portal.xml
integrations/crowdnode/src/main/res/values/styles.xml
integrations/crowdnode/src/test/java/org/dash/wallet/integrations/crowdnode/CrowdNodeApiAggregatorTest.kt

There is a problem with 7.5.0 (beta) -> 7.5.1 upgrade scenario: because of the changes in ApiStatuses, the old online status is restored into a wrong value.
Added a check for this specific case + some tests.
The base `bugfix-crowdnode-7.5.2` branch is checked out of 7.5.1 tag. We can release it as a hotfix with some other possible fixes.

[NMA-1312] (CrowdNode) Fix for the invalid online state

---

integrations/crowdnode/src/main/java/org/dash/wallet/integrations/crowdnode/api/CrowdNodeApi.kt
integrations/crowdnode/src/main/java/org/dash/wallet/integrations/crowdnode/ui/CrowdNodeViewModel.kt
wallet/src/de/schildbach/wallet/ui/staking/StakingActivity.kt

If `CrowdNodeApi` was already initialized, it does not restore the correct sign-up status after the wallet wipe.
Triggering sign-up status restore manually when needed.

[NMA-1318] fix: restoring CrowdNode status even when already initialized

---

integrations/crowdnode/src/main/java/org/dash/wallet/integrations/crowdnode/transactions/FullCrowdNodeSignUpTxSet.kt
wallet/build.gradle
wallet/src/de/schildbach/wallet/ui/transactions/TransactionResultViewBinder.kt

During the development of the new Transaction Details screen, the logic for displaying the total amount was changed to show the amount only.
We want to revert that to show the amount + fee as it is now in production.
CrowdNode total amount calculation will also include fees.

fix: reverting transaction total amount + fee changes

---

integrations/crowdnode/src/main/java/org/dash/wallet/integrations/crowdnode/ui/CrowdNodeViewModel.kt
integrations/crowdnode/src/test/java/org/dash/wallet/integrations/crowdnode/CrowdNodeViewModelTest.kt
wallet/build.gradle

Since we're calling `recheckState` now to rescan the status of CrowdNode, the viewModel state needs to be updated after it.

[NMA-1324] fix: updating CrowdNode account address in viewModel after recheckState

---

wallet/src/de/schildbach/wallet/ui/staking/StakingActivity.kt

If the `VerifySeedActivity` opened from CrowdNode, we want to go back to CrowdNode and not the home screen when it's closed.

[NMA-1356] Return to StakingActivity from VerifySeedActivity

---

build.gradle
integrations/crowdnode/build.gradle
wallet/build.gradle

There are some crashes related to `java.time` library, we need a correct version of desugaring library to avoid them.

fix: setting desugaring library version to 1.1.5 to avoid crashes

---

common/src/main/java/org/dash/wallet/common/ui/dialogs/AdaptiveDialog.kt
common/src/main/java/org/dash/wallet/common/ui/dialogs/OffsetDialogFragment.kt
wallet/src/de/schildbach/wallet/ui/main/WalletFragment.kt

Fix for https://support.dash.org/a/tickets/15911
This issue happens due to fixes for the `AdaptiveDialog` crashes. Because the state of activity isn't `RESUMED` by the time the app returns from the `ScanActivity`, the dialogs isn't shown.
We can replace this check with `activity.lifecycleScope.launchWhenResumed` which should work just as well for the crashes and resolve this issue.

fix: Error dialog on invalid QR code

---

integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/ui/CoinbaseConvertCryptoFragment.kt
integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/viewmodels/ConvertViewViewModel.kt

We need to clear entered dash/fiat amount from the shared viewModel after navigating back from the Convert Crypto fragment.

[NMA-1383] "You will receive" remains after reopen Convert Crypto

---

build.gradle
common/src/main/java/org/dash/wallet/common/WalletDataProvider.kt
integrations/crowdnode/src/main/java/org/dash/wallet/integrations/crowdnode/api/CrowdNodeBlockchainApi.kt
wallet/src/de/schildbach/wallet/WalletApplication.java
wallet/src/de/schildbach/wallet/transactions/WalletTransactionObserver.kt

A listener in WalletTransactionObserver seemed to be the problem after doing analysis and many, many tests
https://github.com/dashevo/dashj/pull/178

fix: improve sync speeds for wallet restoration/rescan

---

wallet/src/de/schildbach/wallet/livedata/RecoverPinLiveData.kt
wallet/src/de/schildbach/wallet/ui/RestoreWalletFromSeedActivity.kt
wallet/src/de/schildbach/wallet/ui/RestoreWalletFromSeedViewModel.kt

We don't want capital letters to appear when typing a recover phrase.
Some android devices were capitalizing the first word.  This results in a new wallet.

fix: restore passphrase should not allow capital letters

---

common/src/main/java/org/dash/wallet/common/ui/payment_method_picker/PaymentMethod.kt
integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/ui/CoinbaseServicesFragment.kt
integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/viewmodels/CoinbaseActivityViewModel.kt
integrations/coinbase/src/main/res/values-ar/strings.xml
integrations/coinbase/src/main/res/values-de/strings.xml
integrations/coinbase/src/main/res/values-el/strings.xml
integrations/coinbase/src/main/res/values-es/strings.xml
integrations/coinbase/src/main/res/values-fa/strings.xml
integrations/coinbase/src/main/res/values-fil/strings.xml
integrations/coinbase/src/main/res/values-fr/strings.xml
integrations/coinbase/src/main/res/values-id/strings.xml
integrations/coinbase/src/main/res/values-it/strings.xml
integrations/coinbase/src/main/res/values-ja/strings.xml
integrations/coinbase/src/main/res/values-ko/strings.xml
integrations/coinbase/src/main/res/values-nl/strings.xml
integrations/coinbase/src/main/res/values-pl/strings.xml
integrations/coinbase/src/main/res/values-pt/strings.xml
integrations/coinbase/src/main/res/values-ru/strings.xml
integrations/coinbase/src/main/res/values-sk/strings.xml
integrations/coinbase/src/main/res/values-th/strings.xml
integrations/coinbase/src/main/res/values-tr/strings.xml
integrations/coinbase/src/main/res/values-uk/strings.xml
integrations/coinbase/src/main/res/values-zh-rTW/strings.xml
integrations/coinbase/src/main/res/values-zh/strings.xml
integrations/coinbase/src/main/res/values/strings.xml

If there is a payment method but buying from it isn't allowed, we want to show a different error dialog. Currently, "No payment methods" error is shown.

[NMA-1413] (Coinbase) Show different error dialog in case of unusable payment method

---

build.gradle
common/src/main/java/org/dash/wallet/common/Configuration.java
integrations/coinbase/build.gradle
integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/Constants.kt
integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/di/CoinBaseModule.kt
integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/network/RemoteDataSource.kt
integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/network/ResponseResource.kt
integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/repository/CoinBaseRepository.kt
integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/repository/remote/CustomCacheInterceptor.kt
integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/repository/remote/HeadersInterceptor.kt
integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/repository/remote/TokenAuthenticator.kt
integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/service/CoinBaseClientConstants.kt
integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/service/CoinBaseServicesApi.kt
integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/service/CoinBaseTokenRefreshApi.kt
integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/ui/CoinbaseConvertCryptoFragment.kt
integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/ui/CoinbaseServicesFragment.kt
integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/ui/convert_currency/model/BaseIdForFaitDataUIState.kt
integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/utils/CoinbaseConfig.kt
integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/viewmodels/CoinbaseActivityViewModel.kt
integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/viewmodels/CoinbaseBuyDashOrderReviewViewModel.kt
integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/viewmodels/CoinbaseBuyDashViewModel.kt
integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/viewmodels/CoinbaseConversionPreviewViewModel.kt
integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/viewmodels/CoinbaseConvertCryptoViewModel.kt
integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/viewmodels/CoinbaseServicesViewModel.kt
integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/viewmodels/EnterTwoFaCodeViewModel.kt
integrations/coinbase/src/test/java/org/dash/wallet/integration/coinbase_integration/CoinBaseRepositoryTest.kt
integrations/crowdnode/build.gradle
wallet/build.gradle
wallet/src/de/schildbach/wallet/ui/buy_sell/BuyAndSellViewModel.kt
wallet/src/de/schildbach/wallet/ui/buy_sell/IntegrationOverviewViewModel.kt

Base ids of currencies are required for making swaps with them. The request to get base ids returns 100kb of data and often times out, so we want to cache them.
- Added caching for Coinbase network layer in general.
- Added custom cache for the `assets/prices` endpoint.
- Added datastore config for Coinbase and began to move some prefs in there.

feat(coinbase): cache base id values [NMA-1402]

---

sample-integration-android/AndroidManifest.xml

Android 11 requires apps that want to interact with other apps to declare visibility queries explicitly.
https://developer.android.com/training/package-visibility/declaring
- Added `dash` queries element to the integration sample manifest.

fix: integration sample on Android 11+

---

features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ExploreSyncWorker.kt
wallet/res/layout/activity_about.xml
wallet/src/de/schildbach/wallet/WalletApplication.java
wallet/src/de/schildbach/wallet/ui/more/AboutActivity.kt

We want a button to force the Explore sync process for testing convenience.
- Added a button in the About screen that triggers the sync. Hidden in mainnet builds.

feat(explore): force sync button for TestNet builds [NMA-1446]

---

common/src/main/java/org/dash/wallet/common/transactions/filters/CoinsReceivedTxFilter.kt
integrations/crowdnode/src/test/java/org/dash/wallet/integrations/crowdnode/CrowdNodeTxFilterTest.kt

There is a bug that leads to internal transactions with an amount that matches the CrowdNode API amount to be considered a possible CrowdNode response.
- Only check for possible CrowdNode responses if it's an incoming transaction.

fix: crowdnode transaction grouping

---

features/exploredash/src/main/java/org/dash/wallet/features/exploredash/di/ExploreDashModule.kt
wallet/src/de/schildbach/wallet/WalletApplication.java

When the wallet is reset, Explore prefs are not cleared. This causes the data to be empty in some cases because the saved timestamp is higher than the preloaded db or remote timestamp.
- Clear Explore prefs when the wallet is reset.

fix: clearing Explore prefs on wallet reset

---

features/exploredash/src/main/java/org/dash/wallet/features/exploredash/data/model/purchase/PurchaseGiftCardResponse.kt

Proguard removes the data field from `PurchaseGiftCardResponse` class.
- Assign default `Data` instance to the `data` field.

fix: retain gift card response in release builds

---

build.gradle
common/build.gradle
common/src/main/java/org/dash/wallet/common/data/BaseConfig.kt
features/exploredash/build.gradle
features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ExploreDatabase.kt
features/exploredash/src/main/java/org/dash/wallet/features/exploredash/repository/ExploreRepository.kt
features/exploredash/src/main/java/org/dash/wallet/features/exploredash/utils/ExploreConfig.kt
features/exploredash/src/test/java/org/dash/wallet/features/exploredash/ExploreDatabaseTest.kt
features/exploredash/src/test/java/org/dash/wallet/features/exploredash/ExploreViewModelTest.kt
integrations/coinbase/build.gradle
integrations/crowdnode/build.gradle
integrations/crowdnode/src/test/java/org/dash/wallet/integrations/crowdnode/CrowdNodeApiAggregatorTest.kt
integrations/crowdnode/src/test/java/org/dash/wallet/integrations/crowdnode/CrowdNodeBalanceConditionTest.kt
wallet/build.gradle

Some Explore tests are broken in dashdirect branch after migrating to DataStore.
- Made `BaseConfig` methods `open` for mocking
- Replaced `runBlocking` with `runTest` since calling one `runBlocking` inside another causes a deadlock.

fix(dashdirect): restore tests

---

common/src/main/java/org/dash/wallet/common/ui/enter_amount/AmountView.kt
common/src/main/java/org/dash/wallet/common/ui/enter_amount/EnterAmountFragment.kt
wallet/src/de/schildbach/wallet/ui/send/SendCoinsFragment.kt

If the exchange rate is null, our Send button is disabled and then even if we enable it, send won't work.
- Allow send if the exchange rate is missing.

fix: allow send if exchange rate is missing [NMA-1506]

---

.deploy/exploredata.rb
common/src/main/res/values/strings.xml
features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/dashdirect/dialogs/GiftCardDetailsViewModel.kt
features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/dashdirect/dialogs/PurchaseGiftCardConfirmDialog.kt
wallet/build.gradle
wallet/res/values/strings.xml
wallet/src/de/schildbach/wallet/Constants.java
wallet/test/de/schildbach/wallet/util/viewModels/MainViewModelTest.kt

Given some timing issues DashDirect API has, we want to retry in the case PaymentStatus request returns an error. Subsequent requests might return a different result.
- Initial delay increased to 1s
- Ticker delay increased to 1.5s
- Retry counter added for 3 retries in the case of an error

chore(dashdirect): retries in case of error

---

common/src/main/java/org/dash/wallet/common/Configuration.java
features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ExploreDatabase.kt
features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ExploreSyncWorker.kt
features/exploredash/src/main/java/org/dash/wallet/features/exploredash/di/ExploreDatabaseModule.kt
features/exploredash/src/main/java/org/dash/wallet/features/exploredash/repository/ExploreRepository.kt
wallet/src/de/schildbach/wallet/Constants.java

Old Explore databases aren't being deleted after a sync.
- Timestamp suffix and associated logic is removed
- Journal mode set to TRUNCATE to avoid creating write-ahead logging files
- Previous database files are cleaned up before an update

fix(explore): cleanup old databases

---

build.gradle
wallet/src/de/schildbach/wallet/ui/more/masternode_keys/MasternodeKeysViewModel.kt

* The last byte was always set to zero (0x00)
Fix the HPMN Operator private / public keypair rendering in base64 format.

fix: render the platform private/public key (base64) correctly

---

integrations/uphold/src/main/java/org/dash/wallet/integration/uphold/ui/UpholdPortalFragment.kt
wallet/src/de/schildbach/wallet/data/BuyAndSellDashServicesModel.kt

Until some business questions are settled, we want to disable Topper. 
- Disable Topper entry points.
- Return old functionality for Buy Dash button in the Uphold portal.

chore: disable Topper

---

common/src/main/java/org/dash/wallet/common/ui/enter_amount/EnterAmountFragment.kt
wallet/src/de/schildbach/wallet/ui/send/SendCoinsFragment.kt

When the user launches Send screen from the locked state, the balance info can still be leaked because we show an "Insufficient funds" error and block the Continue button.
- Don't show the error until the user authenticates.
- Don't block the button until the user authenticates (except for zero amount).

fix: avoid leaking balance info by error message or continue button

---

wallet/build.gradle
wallet/src/de/schildbach/wallet/WalletApplication.java
wallet/src/de/schildbach/wallet/service/CoinJoinService.kt
wallet/src/de/schildbach/wallet/service/platform/PlatformSyncService.kt
wallet/src/de/schildbach/wallet/ui/dashpay/CreateIdentityService.kt
wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt

This will open up DashPay functions by "faking it until we make it".  Mocking is done in the `dashpay` libraries
https://github.com/dashpay/android-dpp/pull/40
https://github.com/dashpay/android-dashpay/pull/73

feat(dashpay): use mock state repository

---

common/build.gradle
features/exploredash/build.gradle
integrations/coinbase/build.gradle
integrations/crowdnode/build.gradle
integrations/uphold/build.gradle
sample-integration-android/build.gradle
wallet/AndroidManifest.xml
wallet/build.gradle
wallet/src/de/schildbach/wallet/service/BootstrapReceiver.java
wallet/src/de/schildbach/wallet/ui/main/WalletActivity.java

Target Android 13 and ask user to approve of notifications

Feature android 13

---

build.gradle

chore: update to dashj 19.0.6-SNAPSHOT

---

.deploy/prepare_changelog.sh
fastlane/Fastfile

- The language list in `prepare_changelog` is amended to reflect our top 7
- Fetch the current `version_code` to avoid failure during metadata update

chore: improvements for the publish pipeline

---

wallet/res/layout/fragment_request_username.xml
wallet/res/layout/fragment_username_voting_info.xml
wallet/res/values/strings.xml
wallet/src/de/schildbach/wallet/ui/main/MainViewModel.kt
wallet/src/de/schildbach/wallet/ui/username/voting/RequestUserNameViewModel.kt
wallet/src/de/schildbach/wallet/ui/username/voting/RequestUsernameFragment.kt
wallet/src/de/schildbach/wallet/ui/username/voting/UsernameVotingInfoFragment.kt

The user should be informed if the request was NOT successful
The user should not be able to submit a request unless they have 0.1 Dash 
The user should still be able to view the one-time info screens on first entry

NMA-1503 : Error Handling

---

integrations/uphold/src/main/java/org/dash/wallet/integration/uphold/ui/UpholdPortalFragment.kt
wallet/src/de/schildbach/wallet/data/BuyAndSellDashServicesModel.kt

feature(uphold): activate topper by reverting (#1186)

---

wallet/src/de/schildbach/wallet/ui/ImportSharedImageActivity.kt

Importing an image with private key QR causes a crash due to wrong `message` param.
- Pass the correct `messageId` and string format arguments.
- Apply ktlint.

fix: import QR private key

---

wallet/res/layout/home_content.xml
wallet/res/layout/shortcut_button.xml
wallet/src/de/schildbach/wallet/ui/widget/ShortcutsPane.kt

In some languages, shortcut text doesn't fit and is cut off.
- Increase shortcut bar height slightly to fit 2 lines of text.
- Make the label adjustable between 10 and 12 sp.
before / after

fix: adjust font size for the shortcut text

---

wallet/src/de/schildbach/wallet/ui/transactions/TransactionResultViewBinder.kt

`TransactionResultViewBinder` has some extra code related to setting the icon that should be removed.
- Remove all icon-setting code except for updateIcon

fix(dashpay): only set tx icon in updateIcon method 

---

wallet/src/de/schildbach/wallet/service/BlockchainStateDataProvider.kt

fix: update calculation of MN rewards post v20 activation

---

integrations/crowdnode/src/main/res/values/strings-crowdnode.xml

Fix "How CrowdNode staking works"

fix: correct grammar on How CrowdNode staking works dialog

---

wallet/res/values/strings-extra.xml

Change the explore menu item subtitle text to remove "150k merchants" line.

fix: explore menu subtitle

---

wallet/src/de/schildbach/wallet/ui/main/WalletActivity.java
wallet/src/de/schildbach/wallet/ui/main/WalletActivityExt.kt

* fix crash when request disable battery opt dialog is cancelled
Some code is moved to `WalletActivityExt` which will make it a little easier to merge with DashPay.

refactor: move explainer dialogs to WalletActivityExt

---

common/src/main/java/org/dash/wallet/common/data/entity/BlockchainState.kt
integrations/crowdnode/src/main/java/org/dash/wallet/integrations/crowdnode/api/CrowdNodeApi.kt
integrations/crowdnode/src/main/java/org/dash/wallet/integrations/crowdnode/model/WithdrawalLimit.kt
integrations/crowdnode/src/main/java/org/dash/wallet/integrations/crowdnode/ui/dialogs/WithdrawalLimitsInfoDialog.kt
integrations/crowdnode/src/main/java/org/dash/wallet/integrations/crowdnode/ui/portal/TransferFragment.kt
integrations/crowdnode/src/main/java/org/dash/wallet/integrations/crowdnode/utils/CrowdNodeConfig.kt
integrations/crowdnode/src/main/res/values/strings-crowdnode.xml
integrations/crowdnode/src/test/java/org/dash/wallet/integrations/crowdnode/CrowdNodeApiAggregatorTest.kt
wallet/src/de/schildbach/wallet/WalletApplication.java
wallet/src/de/schildbach/wallet/database/dao/BlockchainStateDao.kt
wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java
wallet/src/de/schildbach/wallet/service/BlockchainStateDataProvider.kt
wallet/src/de/schildbach/wallet/ui/more/ToolsFragment.kt
wallet/src/de/schildbach/wallet/ui/more/ToolsViewModel.kt

Limit WD to once per block.  Still WiP

feat(crowdnode): limit withdrawals to once per block

---

integrations/crowdnode/src/main/res/values/strings-crowdnode.xml

Change some text to match iOS and latest designs.
https://github.com/dashpay/dashwallet-ios/pull/628/files#diff-598223494c00a23f8cee97c4e2cbd7073a5cbb3fbc5ceb94cdcb661e7978a375R309

chore: update crowdnode text for per block withdrawal limits

---

build.gradle
wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java
wallet/src/de/schildbach/wallet/service/BlockchainStateDataProvider.kt

Resolve the issue where "Syncing..." appears for a long time:

fix: eliminate race condition when updating BlockchainState

---

wallet/AndroidManifest.xml
wallet/build.gradle
wallet/res/layout/activity_settings.xml
wallet/res/values/strings.xml
wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java
wallet/src/de/schildbach/wallet/service/CoinJoinService.kt
wallet/src/de/schildbach/wallet/ui/EditProfileActivity.kt
wallet/src/de/schildbach/wallet/ui/SettingsViewModel.kt
wallet/src/de/schildbach/wallet/ui/dashpay/CropImageActivity.kt
wallet/src/de/schildbach/wallet/ui/dashpay/HistoryHeaderAdapter.kt
wallet/src/de/schildbach/wallet/ui/main/MainViewModel.kt
wallet/src/de/schildbach/wallet/ui/main/WalletFragment.kt

* Support Android 13 (images)
* Refactor to use ActivityResultLauncher

fix(dashpay): update image permissions for Android 13 and fix camera

---

build.gradle
wallet/src/de/schildbach/wallet/service/BootstrapReceiver.java

* only rescan transactions for masternode key usage on upgrade
DashJ has the actual fix to the bug
https://github.com/dashpay/dashj/pull/241

fix: prevent rescan blockchain failure on old wallets

---

integrations/uphold/ERRORS.md
integrations/uphold/src/main/java/org/dash/wallet/integrations/uphold/api/UpholdClientExt.kt
integrations/uphold/src/main/java/org/dash/wallet/integrations/uphold/data/UpholdApiException.java
integrations/uphold/src/test/java/org/dash/wallet/integrations/uphold/UpholdClientTest.kt
integrations/uphold/src/test/java/org/dash/wallet/integrations/uphold/UpholdErrorTest.kt

Change API endpoint for obtaining withdrawal capabilities.

fix(uphold): use crypto_withdrawals capability for transfer permission

---

wallet/src/de/schildbach/wallet/data/InvitationLinkData.kt
wallet/src/de/schildbach/wallet/database/entity/BlockchainIdentityData.kt
wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java
wallet/src/de/schildbach/wallet/ui/dashpay/CreateIdentityService.kt
wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt
wallet/src/de/schildbach/wallet/ui/dashpay/work/SendInviteWorker.kt
wallet/src/de/schildbach/wallet/ui/transactions/TxResourceMapper.java

Refactor some naming to AssetLock
Use v20 asset lock transactions instead of the v19 version
dashj: https://github.com/dashpay/dashj/pull/244
android-dashpay: https://github.com/dashpay/android-dashpay/pull/74

feat(dashpay): use v20 assetlocks

---

wallet/res/values/strings-extra.xml
wallet/res/values/strings.xml
wallet/src/de/schildbach/wallet/service/CoinJoinService.kt
wallet/src/de/schildbach/wallet/ui/coinjoin/CoinJoinLevelFragment.kt
wallet/src/de/schildbach/wallet/ui/coinjoin/CoinJoinLevelViewModel.kt
wallet/src/de/schildbach/wallet/ui/dashpay/CreateIdentityService.kt
wallet/src/de/schildbach/wallet/ui/main/MainActivity.kt
wallet/src/de/schildbach/wallet/ui/main/MainViewModel.kt
wallet/src/de/schildbach/wallet/ui/main/WalletActivityExt.kt
wallet/src/de/schildbach/wallet/util/TimeUtils.kt

feat(dashpay): add timeskew support to CoinJoinService and warning dialogs

---

wallet/src/de/schildbach/wallet/service/CoinJoinService.kt
wallet/src/de/schildbach/wallet/util/TimeUtils.kt

…Service threads
Fixes a problem with internet is not available that would crash the CoinJoin related threads.

fix(coinjoin): prevent timeskew exceptions from stopping CoinJoin

---

wallet/src/de/schildbach/wallet/WalletApplication.java

This fixes a crash that one user had 900+ times.  
If the wallet file becomes corrupted, the backup wallet file is restored, but during that process `wallet` is null and will result in an NPE when the blockchain is reset.

fix: prevent NPE after corrupt wallet requires backup restoration

---

common/src/main/java/org/dash/wallet/common/ui/PaymentHeaderView.kt
common/src/main/res/drawable/animated_circular_progress_indictator.xml
common/src/main/res/drawable/circular_progress_indicator.xml
common/src/main/res/values/strings.xml
wallet/build.gradle
wallet/res/layout/activity_settings.xml
wallet/res/layout/mixing_status_pane.xml
wallet/res/values/strings.xml
wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java
wallet/src/de/schildbach/wallet/service/CoinJoinService.kt
wallet/src/de/schildbach/wallet/service/ForegroundService.kt
wallet/src/de/schildbach/wallet/ui/SettingsActivity.kt
wallet/src/de/schildbach/wallet/ui/main/MainActivity.kt
wallet/src/de/schildbach/wallet/ui/main/MainViewModel.kt
wallet/src/de/schildbach/wallet/ui/main/WalletActivityExt.kt
wallet/src/de/schildbach/wallet/ui/main/WalletFragment.kt
wallet/src/de/schildbach/wallet/ui/more/SettingsViewModel.kt
wallet/src/de/schildbach/wallet/ui/send/SendCoinsFragment.kt
wallet/src/de/schildbach/wallet/ui/send/SendCoinsViewModel.kt
wallet/src/de/schildbach/wallet/util/TimeUtils.kt

fix(dashpay): improve progress UI for mixing and otherfixes timeskew progress

---

common/src/main/java/org/dash/wallet/common/util/GenericUtils.kt
integrations/coinbase/src/main/java/org/dash/wallet/integrations/coinbase/model/PaymentMethods.kt
integrations/coinbase/src/main/java/org/dash/wallet/integrations/coinbase/repository/CoinBaseRepository.kt
integrations/coinbase/src/main/java/org/dash/wallet/integrations/coinbase/service/CoinBaseServicesApi.kt
integrations/coinbase/src/main/java/org/dash/wallet/integrations/coinbase/viewmodels/CoinbaseBuyDashViewModel.kt
integrations/coinbase/src/main/java/org/dash/wallet/integrations/coinbase/viewmodels/CoinbaseConvertCryptoViewModel.kt
integrations/coinbase/src/main/java/org/dash/wallet/integrations/coinbase/viewmodels/CoinbaseServicesViewModel.kt
integrations/coinbase/src/main/java/org/dash/wallet/integrations/coinbase/viewmodels/CoinbaseViewModel.kt
integrations/coinbase/src/main/java/org/dash/wallet/integrations/coinbase/viewmodels/TransferDashViewModel.kt
integrations/coinbase/src/test/java/org/dash/wallet/integrations/coinbase/TestUtils.kt
integrations/coinbase/src/test/resources/payment_methods.json
wallet/src/de/schildbach/wallet/service/NetworkState.kt
wallet/src/de/schildbach/wallet/ui/main/MainViewModel.kt

payment-methods v2 is being shut down.
- Upgraded to payment_methods v3.
- Related changes.
- Disabled auth limits check since `auth_limits` is null
- Removed unneeded `Build.VERSION_CODES.N` checks 
- [] I have added or updated relevant unit/integration/functional/e2e tests

chore(coinbase): upgrade to payment methods v3

---

wallet/androidTest/de/schildbach/wallet/database/DatabaseMigrationTest.kt
wallet/schemas/de.schildbach.wallet.database.AppDatabase/19.json
wallet/src/de/schildbach/wallet/database/AppDatabase.kt
wallet/src/de/schildbach/wallet/database/AppDatabaseMigrations.kt
wallet/src/de/schildbach/wallet/database/entity/BlockchainIdentityData.kt
wallet/src/de/schildbach/wallet/di/DatabaseModule.kt
wallet/src/de/schildbach/wallet/service/WalletFactory.kt
wallet/src/de/schildbach/wallet/ui/OnboardingViewModel.kt
wallet/src/de/schildbach/wallet/ui/main/MainActivity.kt
wallet/src/de/schildbach/wallet/ui/main/MainViewModel.kt

Handle migration for the database and wallets
https://github.com/dashpay/dashj/pull/252

feat(dashpay): support upgrades over Dash Wallet for database and wallet

---

features/exploredash/src/main/java/org/dash/wallet/features/exploredash/data/ctxspend/model/GetMerchantResponse.kt
features/exploredash/src/main/java/org/dash/wallet/features/exploredash/data/explore/model/SearchResult.kt
features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/ctxspend/CTXSpendViewModel.kt
features/exploredash/src/main/res/values/strings-explore-dash.xml

feat: prepare dashspend for production

---

wallet/src/de/schildbach/wallet/WalletApplication.java
wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java
wallet/src/de/schildbach/wallet/ui/CheckPinDialog.kt
wallet/src/de/schildbach/wallet/ui/TransactionResultViewModel.kt
wallet/src/de/schildbach/wallet/ui/transactions/TransactionDetailsDialogFragment.kt
wallet/src/de/schildbach/wallet/ui/transactions/TransactionResultActivity.kt

fix: repair several causes of crash after activty or dialog is destroyed

---

integrations/crowdnode/src/main/java/org/dash/wallet/integrations/crowdnode/api/CrowdNodeWorker.kt
wallet/src/de/schildbach/wallet/ui/widget/ShortcutsPane.kt
wallet/test/de/schildbach/wallet/util/viewModels/MainViewModelTest.kt

fix: specify crowdnode worker foreground service type

---

build.gradle
wallet/src/de/schildbach/wallet/ui/main/WalletActivityExt.kt

fix(coinjoin): fix ANR when coinjoin system starts

---

build.gradle
wallet/AndroidManifest.xml
wallet/build.gradle
wallet/res/layout/dialog_confirm_transaction.xml
wallet/res/layout/fragment_payments_pay.xml
wallet/src/de/schildbach/wallet/Constants.java
wallet/src/de/schildbach/wallet/database/dao/DashPayContactRequestDao.kt
wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java
wallet/src/de/schildbach/wallet/service/platform/PlatformService.kt
wallet/src/de/schildbach/wallet/ui/CreateUsernameActivity.kt
wallet/src/de/schildbach/wallet/ui/EditProfileActivity.kt
wallet/src/de/schildbach/wallet/ui/InviteHandlerViewModel.kt
wallet/src/de/schildbach/wallet/ui/SearchUserActivity.kt
wallet/src/de/schildbach/wallet/ui/dashpay/ContactsFragment.kt
wallet/src/de/schildbach/wallet/ui/dashpay/CreateIdentityService.kt
wallet/src/de/schildbach/wallet/ui/dashpay/DashPayViewModel.kt
wallet/src/de/schildbach/wallet/ui/dashpay/HistoryHeaderAdapter.kt
wallet/src/de/schildbach/wallet/ui/dashpay/NotificationsLiveData.kt
wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt
wallet/src/de/schildbach/wallet/ui/main/MainActivity.kt
wallet/src/de/schildbach/wallet/ui/main/MainViewModel.kt
wallet/src/de/schildbach/wallet/ui/main/WalletActivityExt.kt
wallet/src/de/schildbach/wallet/ui/more/MoreFragment.kt
wallet/src/de/schildbach/wallet/ui/payments/PaymentsPayFragment.kt
wallet/src/de/schildbach/wallet/ui/username/voting/RequestUserNameViewModel.kt
wallet/src/de/schildbach/wallet/ui/username/voting/WelcomeToDashPayFragment.kt

fix(dashpay): fix various UI issues

---

build.gradle
common/src/main/java/org/dash/wallet/common/services/analytics/AnalyticsConstants.kt
wallet/build.gradle
wallet/src/de/schildbach/wallet/di/AppModule.kt
wallet/src/de/schildbach/wallet/payments/SendCoinsTaskRunner.kt
wallet/src/de/schildbach/wallet/service/platform/PlatformSyncService.kt
wallet/src/de/schildbach/wallet/ui/dashpay/EditProfileViewModel.kt

* Add firebase events
* refactor 1 line

feat(dashpay): add more events

---

wallet/src/de/schildbach/wallet/WalletApplication.java
wallet/src/de/schildbach/wallet/database/entity/UsernameRequest.kt
wallet/src/de/schildbach/wallet/service/platform/PlatformSyncService.kt
wallet/src/de/schildbach/wallet/ui/dashpay/CreateIdentityService.kt
wallet/src/de/schildbach/wallet/ui/dashpay/HistoryHeaderAdapter.kt
wallet/src/de/schildbach/wallet/ui/dashpay/work/GetUsernameVotingResultOperation.kt
wallet/src/de/schildbach/wallet/ui/main/WalletTransactionsFragment.kt
wallet/src/de/schildbach/wallet/ui/more/MoreFragment.kt
wallet/src/de/schildbach/wallet/ui/username/voting/RequestUserNameViewModel.kt
wallet/src/de/schildbach/wallet/ui/username/voting/RequestUsernameFragment.kt
wallet/src/de/schildbach/wallet/ui/username/voting/VotingRequestDetailsFragment.kt

fix(dashpay): username request voting period bugs

---

common/src/main/java/org/dash/wallet/common/ui/text/InputWrapper.kt
wallet/CHANGES
wallet/build.gradle
wallet/res/layout/activity_about.xml
wallet/res/values-de/strings-dashpay.xml
wallet/res/values-el/strings-dashpay.xml
wallet/res/values-es/strings-dashpay.xml
wallet/res/values-fa/strings-dashpay.xml
wallet/res/values-fil/strings-dashpay.xml
wallet/res/values-fr/strings-dashpay.xml
wallet/res/values-id/strings-dashpay.xml
wallet/res/values-it/strings-dashpay.xml
wallet/res/values-ja/strings-dashpay.xml
wallet/res/values-ko/strings-dashpay.xml
wallet/res/values-nl/strings-dashpay.xml
wallet/res/values-pl/strings-dashpay.xml
wallet/res/values-pt/strings-dashpay.xml
wallet/res/values-ru/strings-dashpay.xml
wallet/res/values-sk/strings-dashpay.xml
wallet/res/values-tr/strings-dashpay.xml
wallet/res/values-uk/strings-dashpay.xml
wallet/res/values-zh-rTW/strings-dashpay.xml
wallet/res/values-zh/strings-dashpay.xml
wallet/res/values/strings-extra.xml
wallet/src/de/schildbach/wallet/service/platform/PlatformSyncService.kt
wallet/src/de/schildbach/wallet/ui/dashpay/EditProfileViewModel.kt
wallet/src/de/schildbach/wallet/ui/main/WalletActivityExt.kt
wallet/src/de/schildbach/wallet/ui/more/AboutActivity.kt
wallet/src/de/schildbach/wallet/ui/username/voting/RequestUserNameViewModel.kt
wallet/src/de/schildbach/wallet/ui/username/voting/RequestUsernameFragment.kt

Dashpay 11.0.3 fixes

---

build.gradle
wallet/build.gradle
wallet/res/layout/activity_about.xml
wallet/res/values/strings-extra.xml
wallet/res/values/strings.xml
wallet/src/de/schildbach/wallet/service/platform/PlatformSyncService.kt
wallet/src/de/schildbach/wallet/ui/dashpay/CreateIdentityService.kt
wallet/src/de/schildbach/wallet/ui/dashpay/work/BroadcastUsernameVotesWorker.kt
wallet/src/de/schildbach/wallet/ui/more/AboutActivity.kt
wallet/src/de/schildbach/wallet/ui/username/voting/RequestUserNameViewModel.kt

* use dashj 21.1.3 which removes a redundant mnlistdiff check
* Add platform version to About

fix sync stuck 31

---

wallet/res/values/strings-dashpay.xml

fix: update wifi warning for mixing fees

---

integrations/coinbase/src/main/java/org/dash/wallet/integrations/coinbase/model/CoinbaseErrorResponse.kt
integrations/coinbase/src/main/java/org/dash/wallet/integrations/coinbase/repository/CoinBaseRepository.kt
integrations/coinbase/src/main/java/org/dash/wallet/integrations/coinbase/ui/EnterTwoFaCodeFragment.kt
integrations/coinbase/src/main/java/org/dash/wallet/integrations/coinbase/viewmodels/EnterTwoFaCodeViewModel.kt
integrations/coinbase/src/main/res/navigation/nav_coinbase.xml
wallet/proguard.cfg

Coinbase `send` request with 2fa fails because it uses different `idem` from the original, non-2fa request
- Keep original `idem` for 2fa request
- Some refactoring to remove `Resource` return value

fix: coinbase 2fa send error

---

common/src/main/java/org/dash/wallet/common/data/ExchangeRatesConfig.kt

```
java.lang.IllegalStateException: There are multiple DataStores active for the same file: files/datastore/exchange_rates_config.preferences_pb. You should either maintain your DataStore as a singleton or confirm that there is no two DataStore's active on the same file (by confirming that the scope is cancelled).
at androidx.datastore.core.SingleProcessDataStore$file$2.invoke(SingleProcessDataStore.kt:168)
at androidx.datastore.core.SingleProcessDataStore$file$2.invoke(SingleProcessDataStore.kt:163)
at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
at androidx.datastore.core.SingleProcessDataStore.getFile(SingleProcessDataStore.kt:163)
at androidx.datastore.core.SingleProcessDataStore.readData(SingleProcessDataStore.kt:380)
at …
```

fix: make ExchangeRatesConfig a singleton
