dashpay/dash-wallet

wallet/src/de/schildbach/wallet/Constants.java
As described on Slack - I found the issue - when used TestNet flavor application still works on MainNet. Here is a fix.
=> Fixed issue with the broken TestNet configuration in _testNet3 flavor.

sample-integration-android/res/layout/sample_activity.xml, sample-integration-android/src/de/schildbach/wallet/integration/sample/SampleActivity.java, wallet/AndroidManifest.xml, wallet/src/de/schildbach/wallet/Constants.java, wallet/src/de/schildbach/wallet/ui/InputParser.java, wallet/src/de/schildbach/wallet/ui/WalletUri.java, wallet/src/de/schildbach/wallet/ui/WalletUriHandlerActivity.java, wallet/src/de/schildbach/wallet/ui/send/SendCoinsActivity.java, wallet/src/de/schildbach/wallet/ui/send/SendCoinsFragment.java
Added the Inter App Communication based on iOS specification: https://dashpay.atlassian.net/wiki/spaces/DOC/pages/136118304/iOS+Wallet+URL+Scheme
(https://dashpay.atlassian.net/browse/DMD-46)
In order to simplify testing and show sample usage, the relevant section has been added to sample-integration project:
=> Inter App Communication

wallet/res/values-es/strings-extra.xml, wallet/res/values-pt-rBR/strings-extra.xml, wallet/res/values/strings-extra.xml, wallet/src/de/schildbach/wallet/Constants.java, wallet/src/de/schildbach/wallet/ui/EncryptKeysDialogFragment.java, wallet/src/de/schildbach/wallet/ui/EncryptNewKeyChainDialogFragment.java, wallet/src/de/schildbach/wallet/ui/WalletActivity.java
- EncryptNewKeysDialog not cancellable anymore.
- Asking to encrypt wallet whenever it's not.
=> Making it mandatory to encrypt the Wallet

wallet/src/de/schildbach/wallet/data/ExchangeRatesProvider.java
This will use the api from Coinhills.com to obtain the VES exchange rate, then it will remove the VEF exchange rate obtained from BitcoinAverage.com.
Question(s):  
1.  Will it be a problem to remove an exchange rate that people may be using in the app?  Perhaps the app returns to the default of USD?
=> Obtain the VES exchange rate from coinhills.com to replace VEF

wallet/src/de/schildbach/wallet/ui/send/RequestWalletBalanceTask.java
This will add three block explorers
Insight
Dash.org
Chainz
as backups for electrum servers for getting UTXO's (Unspent Transaction Outputs) for an address associated with a private key.
First the app will try one electrum server (and there is only 1 to try at this point).  If that fails, then it will try each of the three block explorers in the above order.
If none of these work, then the paper wallet sweep doesn't function.
=> Paper Wallet Sweep:  Use block explorers as a backup for utxo's

wallet/res/values/values.xml, wallet/src/de/schildbach/wallet/Configuration.java, wallet/testNet3/res/values/values.xml
* Set insight as the default for mainnet and testnet
* Remove obsolete block explorers
* Put testnet list in testnet res/values.xml
=> Update block explorer lists

wallet/res/xml/file_provider.xml, wallet/src/de/schildbach/wallet/ui/ArchiveBackupDialogFragment.java
The Bitcoin Wallet devs solved this a while ago.
=>  Fix for archiving during backup to file process

wallet/src/de/schildbach/wallet/Configuration.java, wallet/src/de/schildbach/wallet/WalletApplication.java, wallet/src/de/schildbach/wallet/data/WalletLock.java, wallet/src/de/schildbach/wallet/ui/UnlockWalletDialogFragment.java, wallet/src/de/schildbach/wallet/ui/WalletActivity.java, wallet/src/de/schildbach/wallet/ui/preference/PinRetryController.java, wallet/src/de/schildbach/wallet/ui/send/SendCoinsFragment.java
This reverts commit 9f9706df0bdfda500df92f80a8c797bae4ca061d.
found a bug.
=> Revert "Add Wallet Lock Timer"

wallet/res/values/strings.xml, wallet/src/de/schildbach/wallet/Constants.java, wallet/src/de/schildbach/wallet/ui/WalletActivity.java
=> Change support email and subject lines for issues/crash reports

wallet/src/de/schildbach/wallet/ActivitiesTracker.java, wallet/src/de/schildbach/wallet/WalletApplication.java, wallet/src/de/schildbach/wallet/ui/AbstractWalletActivity.java
Improved the way we handle closing all the activities when activating PIN protection.
=> DMD-727 Android: Prevent Brute Force Vectors II

build.gradle, common/src/main/res/values-tr/strings.xml, uphold-integration/src/main/res/values-tr/strings-uphold.xml, wallet/AndroidManifest.xml, wallet/CHANGES, wallet/res/layout/encrypt_new_key_chain_dialog.xml, wallet/res/values-fr/strings-extra.xml, wallet/res/values-fr/strings.xml, wallet/res/values-id/strings-extra.xml, wallet/res/values-id/strings.xml, wallet/res/values-it/strings-extra.xml, wallet/res/values-ko/strings-extra.xml, wallet/res/values-ko/strings.xml, wallet/res/values-nl/strings-extra.xml, wallet/res/values-nl/strings.xml, wallet/res/values-sk/strings-extra.xml, wallet/res/values-tr/strings-extra.xml, wallet/res/values-tr/strings.xml, wallet/res/xml/preference_about.xml, wallet/src/de/schildbach/wallet/ui/EncryptNewKeyChainDialogFragment.java
This is showing the 6.4.1 branch without the version bump.
=> Release 6.4.1

wallet/build.gradle
zxing = QR code "scanner"
moshi = json library
slf4j = logging
DMD-827
=> Update zxing, moshi and slf4j dependencies

wallet/src/de/schildbach/wallet/data/WalletLock.java, wallet/src/de/schildbach/wallet/ui/EncryptKeysDialogFragment.java, wallet/src/de/schildbach/wallet/ui/RestoreWalletActivity.java, wallet/src/de/schildbach/wallet/ui/WalletActivity.java
=> Fix crashes (DMD-1048 and 1049)

build.gradle, common/build.gradle, gradle/wrapper/gradle-wrapper.properties, sample-integration-android/build.gradle, uphold-integration/build.gradle, wallet/build.gradle, wallet/google-services.json, wallet/res/xml/preference_about.xml, wallet/src/de/schildbach/wallet/WalletApplication.java, wallet/src/de/schildbach/wallet/data/WalletLock.java, wallet/src/de/schildbach/wallet/rates/DashRatesFirstFallback.java, wallet/src/de/schildbach/wallet/rates/DashRatesSecondFallback.java, wallet/src/de/schildbach/wallet/rates/DashRetailClient.java, wallet/src/de/schildbach/wallet/rates/DashRetailRate.java, wallet/src/de/schildbach/wallet/rates/ExchangeRatesRepository.java, wallet/src/de/schildbach/wallet/rates/LocalBitcoinsClient.java, wallet/src/de/schildbach/wallet/rates/LocalBitcoinsRate.java, wallet/src/de/schildbach/wallet/rates/LocalBitcoinsResponse.java, wallet/src/de/schildbach/wallet/ui/AbstractWalletActivity.java, wallet/src/de/schildbach/wallet/ui/WalletActivity.java, wallet/src/de/schildbach/wallet/ui/preference/AboutFragment.java, wallet/src/de/schildbach/wallet/ui/preference/PreferenceActivity.java
This is currently WIP.
This will probably be changed/rebased,etc based on bugs and problems during the beta testing.
=> Release 6.6.0 (WIP)

wallet/src/de/schildbach/wallet/WalletApplication.java, wallet/src/de/schildbach/wallet/service/BootstrapReceiver.java
This code will lock the wallet by resetting the last unlock time to 0 when the device is rebooted or the app is upgraded.
=> DMD-1103 Wallet Lock Timer | Restart

wallet/res/values/strings-extra.xml, wallet/src/de/schildbach/wallet/ui/WalletTransactionsFragment.java, wallet/src/de/schildbach/wallet/util/FingerprintHelper.java
When device fingerprint key gets invalidated (by adding a new fingerprint, for instance), the fingerprint authentication will stop working.
This commit fixes this issue.
=> Fix issue when fingerprint key gets invalidated.

build.gradle, wallet/src/de/schildbach/wallet/Constants.java
Depends on https://github.com/dashevo/dashj/pull/53
=> MonetaryFormat grouping separator option

common/src/main/java/org/dash/wallet/common/Configuration.java, wallet/src/de/schildbach/wallet/WalletApplication.java, wallet/src/de/schildbach/wallet/ui/VerifySeedActivity.kt, wallet/src/de/schildbach/wallet/ui/WalletActivity.java
Depends on https://github.com/HashEngineering/dash-wallet/pull/231
=> Secure seed reminder

wallet/src/de/schildbach/wallet/Constants.java, wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java, wallet/src/de/schildbach/wallet/util/BlockchainStateUtils.java, wallet/testNet3/res/values/values.xml
Rebase this PR to keep the commits separated
DMD-1203
=> DMD-1203 Redesign:  Fix Syncing, update DNS Seeds and Testnet block explorers

wallet/build.gradle
Firebase documentation https://firebase.google.com/docs/android/setup#available-libraries
This is for the `redesign` branch only.
=> Replace obsolete firebase-core with firebase-analytics and firebase-inappmessaging

wallet/res/drawable/ic_import_key.xml, wallet/res/layout/quick_actions_layout.xml, wallet/res/values/strings-extra.xml, wallet/src/de/schildbach/wallet/ui/WalletActivity.java
Since we are not allowing shortcuts to be customized for MVP, let's replace the 4th configurable icon with the Import Private Key feature for now.
=> NMA-240 Default Shortcuts

wallet/res/values/strings-extra.xml, wallet/res/values/strings.xml
Replaced all variations of "Pay" with "Send"
=> NMA-251 Replace Pay with Send in UI

ui-redesign/src/main/java/org/dash/wallet/ui/widget/LockScreenButton.kt, ui-redesign/src/main/res/layout/lock_screen_button.xml, ui-redesign/src/main/res/values/attrs.xml, wallet/res/layout/activity_lock_screen.xml
The details can be found in the task description https://dashpay.atlassian.net/browse/NMA-216
=> NMA-216 buttons labels are cut off on locked screen

wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java, wallet/src/de/schildbach/wallet/ui/SettingsActivity.kt, wallet/src/de/schildbach/wallet/ui/TransactionResultActivity.kt
=> NMA-27: Redesign: rescan does nothing bis

wallet/res/values/strings-extra.xml, wallet/src/de/schildbach/wallet/livedata/EncryptWalletLiveData.kt, wallet/src/de/schildbach/wallet/ui/BaseMenuActivity.kt, wallet/src/de/schildbach/wallet/ui/SessionActivity.kt, wallet/src/de/schildbach/wallet/ui/SetPinActivity.kt, wallet/src/de/schildbach/wallet/ui/SetPinViewModel.kt
NMA-286 Wrong PIN! 7 attempts remaining” appearing on the Confirm PIN
NMA-288 locks the user out of the app when fails to do Confirm PIN
NMA-288 locks the user out of the app when fails to do Confirm PIN
=> Change spending PIN fixes

wallet/src/de/schildbach/wallet/WalletApplication.java, wallet/src/de/schildbach/wallet/ui/LockScreenActivity.kt
=> Lock Screen back close the app

common/build.gradle, wallet/build.gradle, wallet/src/de/schildbach/wallet/Constants.java, wallet/src/de/schildbach/wallet/data/DynamicFeeLoader.java, wallet/src/de/schildbach/wallet/offline/DirectPaymentTask.java, wallet/src/de/schildbach/wallet/rates/ExchangeRate.java, wallet/src/de/schildbach/wallet/rates/LocalBitcoinsClient.java, wallet/src/de/schildbach/wallet/rates/LocalBitcoinsRate.java, wallet/src/de/schildbach/wallet/rates/LocalBitcoinsResponse.java, wallet/src/de/schildbach/wallet/rates/RetrofitClient.java, wallet/src/de/schildbach/wallet/ui/send/RequestPaymentRequestTask.java, wallet/src/de/schildbach/wallet/ui/send/RequestWalletBalanceTask.java, wallet/src/de/schildbach/wallet/util/HttpGetThread.java
Missing _slash_ caused HTTP 301
Also USDC caption added because BitPay added USDC rate to the response
No need to update okhttp so far
=> Fix Localbitcoins fallback strategy

common/src/main/java/org/dash/wallet/common/Configuration.java, wallet/src/de/schildbach/wallet/ui/BackupWalletToSeedDialogFragment.java, wallet/src/de/schildbach/wallet/ui/LockScreenActivity.kt, wallet/src/de/schildbach/wallet/ui/SetPinActivity.kt, wallet/src/de/schildbach/wallet/ui/VerifySeedActivity.kt, wallet/src/de/schildbach/wallet/ui/WalletActivity.java
Fixed the issue that Verify Passphrase Reminder is being displayed more than once.
=> NMA-327 Verify Passphrase Reminder

build.gradle, wallet/cpp/dashj-bls/dashj-bls-signature-wrapper.cpp, wallet/src/de/schildbach/wallet/Constants.java
All of the relevant changes are in DashJ.
https://github.com/dashevo/dashj/pull/65
=> NMA-354 Resend tx if disconnected when sending

wallet/src/de/schildbach/wallet/ui/EnterAmountFragment.kt
Changed the decimal places limit for Dash to 8 digits
=> NMA-363 Send Screen - Increase Decimal Precision

common/src/main/java/org/dash/wallet/common/Configuration.java, wallet/src/de/schildbach/wallet/ui/AdvancedSecurityActivity.kt, wallet/src/de/schildbach/wallet/ui/SecurityActivity.kt, wallet/src/de/schildbach/wallet/ui/send/SendCoinsFragment.java
=> NMA-340 Disabled biometric limit when fingerprint disabled

wallet/src/de/schildbach/wallet/ui/BaseMenuActivity.kt, wallet/src/de/schildbach/wallet/ui/GlobalFooterActivity.kt, wallet/src/de/schildbach/wallet/ui/InteractionAwareActivity.kt, wallet/src/de/schildbach/wallet/ui/ReceiveActivity.kt, wallet/src/de/schildbach/wallet/ui/UpholdTransferActivity.kt, wallet/src/de/schildbach/wallet/ui/VerifySeedActivity.kt, wallet/src/de/schildbach/wallet/ui/ViewSeedActivity.kt
Fixed the issue with not resetting logout timer when touching some screens
=> Reset logout timer when touching the screen

wallet/res/layout/wallet_balance_widget_content.xml, wallet/res/values/strings-extra.xml, wallet/src/de/schildbach/wallet/WalletBalanceWidgetProvider.java, wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java
Fixed crash when using app appwidget before initializing the wallet.
Updating appwidget when receiving and sending funds.
=> NMA-376 App Shortcuts and Widget Crash Fixes

wallet/src/de/schildbach/wallet/WalletApplication.java, wallet/src/de/schildbach/wallet/ui/UpholdTransferActivity.kt, wallet/src/de/schildbach/wallet/ui/WalletActivity.java
=> NMA-469 Uphold Related Crashes

build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, ui-redesign/build.gradle, ui-redesign/src/main/res/values/attrs.xml, wallet/build.gradle
Fixed build failures after updating Android Gradle plugin to version 3.6.1 and Gradle to version 5.6.4
```
ui-redesign\build\intermediates\packaged_res\debug\values\values.xml:79:5-83:25: AAPT: error: resource attr/text not found.
constraintlayout-2.0.0-beta2\res\values\values.xml:268:5-4347: AAPT: error: resource attr/flow_horizontalSeparator not found.
constraintlayout-2.0.0-beta2\res\values\values.xml:268:5-4347: AAPT: error: resource attr/flow_verticalSeparator not found.
constraintlayout-2.0.0-beta2\res\values\values.xml:269:5-3548: AAPT: error: resource attr/flow_horizontalSeparator not found.
constraintlayout-2.0.0-beta2\res\values\values.xml:269:5-3548: AAPT: error: resource attr/flow_verticalSeparator not found.
constraintlayout-2.0.0-beta2\res\values\values.xml:271:5-4382: AAPT: …
```
=> Fixed build failures after updating Gradle

wallet/src/de/schildbach/wallet/ui/send/PaymentProtocolViewModel.kt
Changed the payment request problem message
=> NMA-416 Implement BIP70 Payment Protocol

wallet/src/de/schildbach/wallet/ui/ProgressDialogFragment.java, wallet/src/de/schildbach/wallet/ui/send/SweepWalletFragment.java
Replaced import `de.schildbach.wallet.ui.ProgressDialogFragment` with `android.app.ProgressDialog` in order to avoid crashes reported by google play
=> NMA-481 Import Private Key Crashes

wallet/build.gradle, wallet/src/de/schildbach/wallet/ui/CreateUsernameActivity.kt, wallet/src/de/schildbach/wallet/ui/UpholdTransferActivity.kt, wallet/src/de/schildbach/wallet/ui/WalletActivity.java, wallet/src/de/schildbach/wallet/ui/dashpay/DashPayViewModel.kt, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt, wallet/src/de/schildbach/wallet/ui/widget/ReceiveInfoView.kt
Delay the call of getUsernameViewModel.getUsername(username) until user stops typing
Update
Added some additional improvements:
- Replaced GetUsernameViewModel with less generic DashPayViewModel which can be used to handle multiple Platform-related LiveDates
- Moved the code related to retrieving the data from Platform into PlatformRepo (repository pattern)
- Finally replaced Handler based async processing of Platform requests with kotlin coroutines
=> Coroutines based Platform communication model

common/src/main/res/layout/alert_dialog_button_bar.xml, wallet/res/layout/fragment_enter_pin.xml, wallet/res/values/strings-extra.xml, wallet/src/de/schildbach/wallet/ui/CheckPinDialog.kt, wallet/src/de/schildbach/wallet/ui/SetupPinDuringUpgradeDialog.kt
Applied default Android dialog appearance to Authenticate dialog to be more consistent with Enable fingerprint dialog
=> NMA-397 adjust buttons on Auth Send dialog for German

wallet/res/layout/dialog_new_account_confirm.xml, wallet/res/values/strings-extra.xml, wallet/src/de/schildbach/wallet/ui/CreateUsernameActivity.kt, wallet/src/de/schildbach/wallet/ui/dashpay/NewAccountConfirmDialog.kt, wallet/src/de/schildbach/wallet/ui/dashpay/NewAccountConfirmDialogViewModel.kt
=> NMA-303  Fund New Account | Confirm Transaction (UI)

common/build.gradle, wallet/AndroidManifest.xml, wallet/build.gradle, wallet/res/values/strings-extra.xml, wallet/src/de/schildbach/wallet/AppDatabase.java, wallet/src/de/schildbach/wallet/Constants.java, wallet/src/de/schildbach/wallet/WalletApplication.java, wallet/src/de/schildbach/wallet/data/IdentityCreationState.kt, wallet/src/de/schildbach/wallet/data/IdentityCreationStateDaoAsync.kt, wallet/src/de/schildbach/wallet/ui/CreateUsernameActivity.kt, wallet/src/de/schildbach/wallet/ui/HeaderBalanceFragment.java, wallet/src/de/schildbach/wallet/ui/WalletActivity.java, wallet/src/de/schildbach/wallet/ui/WalletTransactionsFragment.java, wallet/src/de/schildbach/wallet/ui/dashpay/CreateIdentityNotification.kt, wallet/src/de/schildbach/wallet/ui/dashpay/CreateIdentityService.kt, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt, wallet/src/de/schildbach/wallet/ui/dashpay/ProcessingIdentityViewHolder.kt
Here is the complete code of proposed architecture of identity creation flow.
=> NMA-498: Connect UI to Backend, Part II - Create Username - foreground service

wallet/res/drawable/ic_username_requirement_x.xml, wallet/res/layout/create_username.xml, wallet/res/values/strings-extra.xml, wallet/src/de/schildbach/wallet/ui/CreateUsernameActivity.kt
=> Unified with the iOS way of displaying user validation progress on network

wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java
Moved calling BlockchainServiceImpl.startForeground(...) into main thread to avoid RemoteServiceExceptions
=> Another attempt to resolve RemoteServiceException's

README.md, wallet/README.md
Mobile Devnet Build Instructions are missing
Updated documentation
These instructions were used to set up my machine
None
=> Add Mobile Devnet Instructions

common/src/main/java/org/dash/wallet/common/InteractionAwareActivity.java, wallet/src/de/schildbach/wallet/livedata/Resource.kt, wallet/src/de/schildbach/wallet/livedata/Status.kt, wallet/src/de/schildbach/wallet/ui/CreateUsernameActivity.kt, wallet/src/de/schildbach/wallet/ui/dashpay/DashPayViewModel.kt
Fix a bug found by QA during validation of NMA-309. The issue allows the special character to be used in the DashPay username when it was entered before the validation of previously entered correct username ended.
Canceling the UI and business logic validation requests when entering any character in username text field.
Minor code refactoring.
Multiple manual attempts to use function characters and additional QA validation.
N/A
=> [NMA-309]:  Home Screen Status | Restart from Error (UI)

wallet/src/de/schildbach/wallet/WalletApplication.java, wallet/src/de/schildbach/wallet/service/BootstrapReceiver.java
Restarting the app after update in order to force updating process (setup PIN length, etc.)
Explanation of the issue:
https://drive.google.com/file/d/1P67CIOIG9UcXxbzBmQSfM6OhuWYExpoO
=> NMA-508 Long Pin Issue

wallet/src/de/schildbach/wallet/WalletApplication.java, wallet/src/de/schildbach/wallet/data/BlockchainIdentityData.kt, wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java, wallet/src/de/schildbach/wallet/ui/dashpay/CreateIdentityService.kt, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt
1. Update Contacts and Profiles from Platform in the database every block
2. Optimize the platform queries that update the database using PR (https://github.com/dashevo/android-dashpay/pull/9) and add a log for the timer on this method
This will fail the CI tests due to missing methods in the dashpay PR.
=> NMA-339 (2): Update Contact/Profile info in Database after each block

wallet/src/de/schildbach/wallet/data/DashPayContactRequest.kt, wallet/src/de/schildbach/wallet/ui/DashPayUserActivity.kt, wallet/src/de/schildbach/wallet/ui/SearchUserActivity.kt, wallet/src/de/schildbach/wallet/ui/WalletTransactionsFragment.java, wallet/src/de/schildbach/wallet/ui/dashpay/DashPayViewModel.kt, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt
=> Evonet send contact request backend

.travis.yml
CI is failing because dashj was changed but the bintray OSS build was not updated yet.
In the travis script build DashJ first since the other libraries depend on it.
The Travis CI tests must pass
None
=> Fix CI build order

.travis.yml, uphold-integration/src/main/java/org/dash/wallet/integration/uphold/data/UpholdApiException.java, uphold-integration/src/main/java/org/dash/wallet/integration/uphold/data/UpholdClient.java, uphold-integration/src/main/java/org/dash/wallet/integration/uphold/ui/UpholdWithdrawalHelper.java, uphold-integration/src/main/res/values/strings-uphold.xml
=> NMA-506 Uphold Error Handling - Funds Availability

.deploy/deploy.sh, .travis.yml
Added Travis config for automatic deploy of `evonet-develop` branch.
=> Automatic deploy of evonet-develop branch

wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java, wallet/src/de/schildbach/wallet/ui/dashpay/CreateIdentityService.kt, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt
Solves issues related to UNAVAILABLE platform nodes by retrying the request again with another node (default = 5 times)
1. Set the DMN List for the Platform object in BlockchainServiceImpl.onCreate
2. BlockchainIdentity will use the app's platform object instead of making its own (which would not use the DNM List)
3. If there are no contacts, don't look up related profiles or names.
Examples in the DashPay Library and testing with the app
None
https://github.com/dashevo/android-dashpay/pull/15 (some changes required for the app)
https://github.com/dashevo/dapi-client-android/pull/7 (most of the required changes)
https://github.com/dashevo/dashj/pull/79 (evonet related updates)
=> DashPay: Use the Deterministic Masternode List for Platform Requests

wallet/src/de/schildbach/wallet/ui/WalletTransactionsFragment.java
=> Fix: transaction dialog crash

wallet/src/de/schildbach/wallet/Constants.java, wallet/src/de/schildbach/wallet/ui/HeaderBalanceFragment.java, wallet/src/de/schildbach/wallet/ui/WalletBalanceFragment.java
Removed balance strike-out for devnet builds
=> NMA-555 Remove Balance Strike-out for Devnets

wallet/src/de/schildbach/wallet/ui/MainActivity.kt
=> Fix: Crashing when rescanning blockchain

wallet/src/de/schildbach/wallet/ui/CreateUsernameActivity.kt
=> Create Username: show keyboard

wallet/src/de/schildbach/wallet/ui/MainActivity.kt, wallet/src/de/schildbach/wallet/ui/SearchUserActivity.kt
=> NMA-560 | (Contact Request) Status not Persisting

.deploy/deploy.sh, .travis.yml
Add ability to generate evonet and palinka builds with the deployment system
N/A
N/A
=> Dashpay builds 4 palinka evonet

wallet/src/de/schildbach/wallet/ui/HeaderBalanceFragment.java
NMA-585 - The user avatar, if clicked will go to the Notifications screen.
None, but this depends on #471  and should be merged after.
N/A
=> DashPay: Notification Entry Point

wallet/res/menu-v21/sending_addresses_context.xml, wallet/res/menu-v21/sending_addresses_fragment_options.xml, wallet/res/menu-v21/wallet_addresses_context.xml
The crash on Android 4.4 was related to menus which specify an icon with `android:icon=` and prior to Android 21 vector drawables are not supported directly.  The solution chosen here was to copy these menus with icons into the `menu-v21` folder and then remove the icons from the menus that are in the `menu` folder.
This is an obsolete set of screens and is not necessarily worth doing too much work on.  An alternative solution was to replace references to the icons in the menus with indirect references like this:
```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
<item android:drawable="@drawable/ic_file_goes_here" />
</selector>
```
This method was going to take longer to write and debug as I had a new crash each time I …
=> NMA-554 - Android 4.4 crash on address screens

wallet/build.gradle, wallet/res/xml/preference_about.xml, wallet/src/de/schildbach/wallet/ui/preference/AboutFragment.java
Re-enabling Firebase In-App Messaging in DashPay.
=> NMA-452 Upgrade Crash (Firebase / Protobuf)

common/src/main/java/org/dash/wallet/common/data/CurrencyInfo.java, common/src/main/res/values/strings.xml, wallet/src/de/schildbach/wallet/rates/ExchangeRate.java, wallet/src/de/schildbach/wallet/ui/ExchangeRatesFragment.java
=> Move hard coded currency names to strings-extra to support translations

wallet/res/layout/activity_more.xml
=> Add scrolling to More menu

wallet/res/layout/wallet_transactions_fragment.xml
NMA-587
This addresses the clipped history filter text label, but also makes the dropdown expand across the screen.
none
Before:
After:
=> Fix clipping issue on history filter

wallet/res/layout/transaction_row.xml, wallet/src/de/schildbach/wallet/ui/TransactionsAdapter.java
NMA-587
- The primary status text will end with "..." if it is too long.  ConstraintLayout used to handle this.
- The date format was changed to a shorter format
none
=> Home Screen: Transaction Fixes

wallet/res/layout/activity_advanced_security.xml, wallet/res/layout/fragment_its_import_to_secure.xml, wallet/res/layout/verify_seed_verify.xml, wallet/res/values-hdpi/dimens.xml, wallet/res/values-xhdpi/dimens.xml, wallet/res/values/styles.xml, wallet/src/de/schildbach/wallet/ui/VerifySeedConfirmFragment.kt
=> NMA-588  | Small Screen Issues

wallet/proguard.cfg, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt
NMA-598 - Bug related to synchronization of contacts, profiles and usernames.
This will probably have merge conflicts with #482
https://github.com/dashevo/dashj/pull/88
https://github.com/dashevo/android-dpp/pull/8 (bug fix)
none
=> DashPay: Fix missing profiles -> empty Contacts/Notifications Screens

build.gradle, wallet/build.gradle, wallet/src/de/schildbach/wallet/WalletApplication.java, wallet/src/de/schildbach/wallet/ui/DashPayUserActivity.kt, wallet/src/de/schildbach/wallet/ui/SearchUserActivity.kt, wallet/src/de/schildbach/wallet/ui/dashpay/ContactsFragment.kt, wallet/src/de/schildbach/wallet/ui/dashpay/DashPayViewModel.kt, wallet/src/de/schildbach/wallet/ui/dashpay/NotificationsActivity.kt, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt, wallet/src/de/schildbach/wallet/ui/dashpay/work/DeriveKeyWorker.kt, wallet/src/de/schildbach/wallet/ui/dashpay/work/SendContactRequestOperation.kt, wallet/src/de/schildbach/wallet/ui/dashpay/work/SendContactRequestWorker.kt, wallet/src/de/schildbach/wallet/ui/send/SendCoinsFragment.java
=> Using WorkManager for sending contact requests

wallet/src/de/schildbach/wallet/ui/BackupWalletDialogFragment.java
NMA-595
Remove the wallet password from the backup file since v7 passwords are not the same as the user's PIN. 
none
none
=> NMA-595: Save backup file without PIN

wallet/res/values/strings-extra.xml, wallet/src/de/schildbach/wallet/data/PaymentIntent.java, wallet/src/de/schildbach/wallet/ui/InputParser.java, wallet/src/de/schildbach/wallet/ui/send/PaymentProtocolFragment.kt, wallet/src/de/schildbach/wallet/ui/send/PaymentProtocolViewModel.kt, wallet/src/de/schildbach/wallet/ui/send/SendCoinsBaseViewModel.kt, wallet/src/de/schildbach/wallet/ui/send/SendCoinsFragment.java, wallet/src/de/schildbach/wallet/ui/send/SendCoinsOfflineTask.java, wallet/src/de/schildbach/wallet/ui/send/SendCoinsViewModel.kt
NMA-593 BIP70 | Broadcast Transaction After Server
Performed few BIP70 payments and analysed operations order in logs.
Performed few regular transactions in order to make sure that nothing was accidentally broken.
=> BIP70 | Broadcast Transaction After Server Ack

wallet/src/de/schildbach/wallet/ui/DashPayUserActivity.kt, wallet/src/de/schildbach/wallet/ui/WalletFragment.kt, wallet/src/de/schildbach/wallet/ui/dashpay/DashPayViewModel.kt, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt, wallet/src/de/schildbach/wallet/ui/dashpay/work/BaseWorker.kt, wallet/src/de/schildbach/wallet/ui/dashpay/work/DeriveKeyWorker.kt, wallet/src/de/schildbach/wallet/ui/dashpay/work/SendContactRequestOperation.kt, wallet/src/de/schildbach/wallet/ui/dashpay/work/SendContactRequestWorker.kt
=> Simplified tracking of the progress of send contact request operation

build.gradle, wallet/cpp/dashj-bls/dashj-bls-signature-wrapper.cpp
NMA-592
Before merging, ensure that the dashj version is 0.17.4.
https://github.com/dashevo/dashj/pull/89
none
=> NMA-592: Use Chainlocks to determine main chain

wallet/src/de/schildbach/wallet/data/BlockchainIdentityBaseData.kt, wallet/src/de/schildbach/wallet/ui/MainActivityViewModel.kt
A == should have been >= otherwise the contacts screen was not displayed even though there were contacts.
None
N/A
=> DashPay: Fix bug preventing viewing contacts

.travis.yml, build.gradle, common/build.gradle, gradle/wrapper/gradle-wrapper.properties, integration-android/build.gradle, ui-redesign/build.gradle, uphold-integration/build.gradle, wallet/build.gradle, wallet/cpp/dashj-bls/dashj-bls-signature-wrapper.cpp, wallet/src/de/schildbach/wallet/ui/UpholdTransferActivity.kt, wallet/src/de/schildbach/wallet/ui/VerifySeedConfirmFragment.kt, wallet/src/de/schildbach/wallet/ui/VerifySeedWriteDownFragment.kt, wallet/src/de/schildbach/wallet/ui/preference/AboutFragment.java, wallet/src/de/schildbach/wallet/ui/widget/ReceiveInfoView.kt
NMA-597
Some lines of kotlin code had to be changed.
Travis config was changed also.  Let's see if the Travis CI tests pass.
This also will use dashj 0.17.5 (with protobuf-javalite)
None
None, no UI changes were made
=> Update to SDK 29

wallet/src/de/schildbach/wallet/ui/DashPayUserActivity.kt, wallet/src/de/schildbach/wallet/ui/DashPayUserActivityViewModel.kt, wallet/src/de/schildbach/wallet/ui/TransactionResultViewBinder.kt, wallet/src/de/schildbach/wallet/ui/TransactionsAdapter.java, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt
=> Clickable Profile Picture

wallet/res/layout/activity_payments.xml, wallet/src/de/schildbach/wallet/ui/PaymentsFragment.kt
=> Changed the alignment of title in PaymentsFragment to center

wallet/schemas/de.schildbach.wallet.AppDatabase/11.json, wallet/src/de/schildbach/wallet/AppDatabase.java, wallet/src/de/schildbach/wallet/data/BlockchainIdentityData.kt, wallet/src/de/schildbach/wallet/data/RoomConverters.kt, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt
NMA-651
Fix delays in blockchain identity initialization and fix a crash that occurs if Platform nodes are not available.
https://github.com/dashevo/android-dpp/pull/11
https://github.com/dashevo/dapi-client-android/pull/11
https://github.com/dashevo/android-dashpay/pull/27
=> DashPay: Fix BlockchainIdentity intialization delays and crashes

wallet/res/layout/activity_forgot_pin.xml, wallet/res/values/strings-extra.xml, wallet/src/de/schildbach/wallet/livedata/RecoverPinLiveData.kt, wallet/src/de/schildbach/wallet/livedata/VerifySeedLiveData.kt, wallet/src/de/schildbach/wallet/ui/ForgotPinActivity.kt, wallet/src/de/schildbach/wallet/ui/RestoreWalletFromSeedActivity.kt, wallet/src/de/schildbach/wallet/ui/RestoreWalletFromSeedViewModel.kt, wallet/src/de/schildbach/wallet/ui/SetPinActivity.kt, wallet/src/de/schildbach/wallet/ui/security/SecurityGuard.java, wallet/src/de/schildbach/wallet/ui/widget/PinPreviewView.kt
Removing multiple spaces from seed in order to avoid mistakes.
NMA-655 Forgot Pin Issue
=> PIN recovery functionality

wallet/build.gradle, wallet/res/layout/activity_advanced_security.xml, wallet/res/layout/activity_security.xml, wallet/res/values/styles.xml, wallet/src/de/schildbach/wallet/ui/SecurityActivity.kt
=> Fixed the issue with missing Auto Logout switch in Advanced Security screen

wallet/build.gradle
=> Downgrade zxing to avoid crash on Android 6

wallet/build.gradle
This is to see if a modification to build.gradle will allow Travis CI to build the app.
This is for https://github.com/dashevo/dash-wallet/pull/547
https://github.com/dashevo/dash-wallet/pull/547
=> load props if local.properties exists

wallet/build.gradle, wallet/src/de/schildbach/wallet/data/DashPayProfile.kt, wallet/src/de/schildbach/wallet/data/ImgurClient.kt, wallet/src/de/schildbach/wallet/data/ImgurImg.kt, wallet/src/de/schildbach/wallet/data/ImgurUploadResponse.kt, wallet/src/de/schildbach/wallet/ui/EditProfileActivity.kt, wallet/src/de/schildbach/wallet/ui/dashpay/EditProfileViewModel.kt
=> NMA-662 | Upload profile picture to ImgUr

wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java
NMA-677
Do not use specific hard coded masternodes for Platform calls.
N/A
N/A
=> DashPay: Ban Specific Bad Evonet masternodes

wallet/src/de/schildbach/wallet/data/ImgurImg.kt, wallet/src/de/schildbach/wallet/ui/EditProfileActivity.kt, wallet/src/de/schildbach/wallet/ui/dashpay/CropImageActivity.kt, wallet/src/de/schildbach/wallet/ui/dashpay/EditProfileViewModel.kt, wallet/src/de/schildbach/wallet/ui/dashpay/ExternalUrlProfilePictureDialog.kt, wallet/src/de/schildbach/wallet/ui/dashpay/GravatarProfilePictureDialog.kt
=> DashPay: Fix Improvements for Imgur, Public Url

wallet/res/layout/activity_more.xml, wallet/res/layout/join_dashpay_row.xml, wallet/res/values/strings-extra.xml, wallet/src/de/schildbach/wallet/ui/JoinDashPayViewHolder.kt, wallet/src/de/schildbach/wallet/ui/MainActivity.kt, wallet/src/de/schildbach/wallet/ui/MainActivityViewModel.kt, wallet/src/de/schildbach/wallet/ui/MoreFragment.kt, wallet/src/de/schildbach/wallet/ui/TransactionsAdapter.java, wallet/src/de/schildbach/wallet/ui/WalletFragment.kt, wallet/src/de/schildbach/wallet/ui/WalletTransactionsFragment.java, wallet/src/de/schildbach/wallet/ui/dashpay/UpgradeToEvolutionFragment.kt, wallet/src/de/schildbach/wallet/ui/widget/ShortcutsPane.kt
=> NMA-642 | Create Username | Entry Points

common/src/main/res/values/dimens.xml, wallet/res/layout/activity_create_username.xml, wallet/res/layout/identity_creation_state.xml, wallet/res/values-hdpi/dimens.xml, wallet/res/values/strings-extra.xml, wallet/src/de/schildbach/wallet/ui/CreateUsernameActivity.kt
=> Spanish/Krip Issues: Dash Pay Features

wallet/src/de/schildbach/wallet/ui/dashpay/utils/ProfilePictureDisplay.kt
=> Avoid "IllegalArgumentException: You cannot start a load for a destroyed activity" crash

common/src/main/java/org/dash/wallet/common/UserInteractionAwareCallback.java, wallet/src/de/schildbach/wallet/ui/AboutActivity.kt, wallet/src/de/schildbach/wallet/ui/MoreActivity.kt, wallet/src/de/schildbach/wallet/ui/ReportIssueDialogBuilder.java, wallet/src/de/schildbach/wallet/ui/WalletActivity.java
NMA-505
The app won't lockout the user when typing in a description when reporting an issue.
This PR doesn't cover other dialogs.
=> Make Report Issue interaction aware

wallet/src/de/schildbach/wallet/ui/scan/ScanActivity.java
This will allow recognizing inverted QR codes
(black background/white QR code)
NMA-624
Add ability to scan inverted QR codes
None
N/A
=> ScanActivity: Support Inverted QR Codes

wallet/evonet/res/values/values.xml, wallet/src/de/schildbach/wallet/ui/TransactionsAdapter.java
NMA-679 - incorrect balance 
These are minor UI fixes that are not related to incorrect balances but were found when trying to investigate the issue.
https://github.com/dashevo/dashj/pull/98
=> Dashpay transaction list fixes

wallet/src/de/schildbach/wallet/ui/TransactionResultViewBinder.kt
=> NMA-682 | Transaction Details | Touchable Usernames

wallet/src/de/schildbach/wallet/ui/AbstractBindServiceActivity.java
=> Fixed bug causing issue with resetting the blockchain etc.

wallet/src/de/schildbach/wallet/ui/dashpay/WalletBalanceBasedLiveData.kt
NMA-714
We just need to throttle the wallet listeners and limit UI updates.
None
None
=> DashPay: Fix ANR's that occur during sync / blockchain rescan

build.gradle, wallet/AndroidManifest.xml, wallet/build.gradle
=> DashPay: Add Crashlytics

wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java, wallet/src/de/schildbach/wallet/ui/dashpay/CreateIdentityService.kt, wallet/src/de/schildbach/wallet/ui/dashpay/OnPreBlockProgressListener.kt, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt, wallet/src/de/schildbach/wallet/ui/dashpay/WalletBalanceBasedLiveData.kt
NMA-690
Most of Download Blockchain Progress is handled by DashJ, but there is step called "PreBlockDownload" which happens entirely within the app that syncs Platform data.  The app must handle the % sync status of this step itself.
https://github.com/dashevo/dashj/pull/100
=> DashPay: Smoother Sync Status

wallet/src/de/schildbach/wallet/ui/AbstractWalletActivity.java, wallet/src/de/schildbach/wallet/ui/dashpay/CreateIdentityService.kt, wallet/src/de/schildbach/wallet/ui/dashpay/DashPayViewModel.kt, wallet/src/de/schildbach/wallet/ui/dashpay/EditProfileViewModel.kt, wallet/src/de/schildbach/wallet/ui/dashpay/work/SendContactRequestOperation.kt, wallet/src/de/schildbach/wallet/ui/dashpay/work/SendContactRequestWorker.kt, wallet/src/de/schildbach/wallet/ui/dashpay/work/UpdateProfileWorker.kt, wallet/src/de/schildbach/wallet/ui/send/SendCoinsViewModel.kt, wallet/src/de/schildbach/wallet/util/AnrException.java, wallet/src/de/schildbach/wallet/util/AnrSupervisor.java, wallet/src/de/schildbach/wallet/util/AnrSupervisorCallback.java, wallet/src/de/schildbach/wallet/util/AnrSupervisorRunnable.java
=> NMA-716 | Crashlytics | Log Captured Errors

wallet/build.gradle, wallet/schemas/de.schildbach.wallet.AppDatabase/12.json, wallet/src/de/schildbach/wallet/AppDatabase.java, wallet/src/de/schildbach/wallet/Constants.java, wallet/src/de/schildbach/wallet/data/DashPayContactRequest.kt, wallet/src/de/schildbach/wallet/data/DashPayContactRequestDao.kt, wallet/src/de/schildbach/wallet/data/DashPayContactRequestDaoAsync.kt, wallet/src/de/schildbach/wallet/data/DashPayProfile.kt, wallet/src/de/schildbach/wallet/ui/dashpay/DashPayViewModel.kt, wallet/src/de/schildbach/wallet/ui/dashpay/EditProfileViewModel.kt, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt, wallet/src/de/schildbach/wallet/ui/dashpay/work/UpdateProfileOperation.kt, wallet/src/de/schildbach/wallet/ui/dashpay/work/UpdateProfileWorker.kt, wallet/src/de/schildbach/wallet/ui/send/SendCoinsFragment.java
NMA-695 - Contact Request Versioning Support
for for multiple contact requests received, use the latest version.
https://github.com/dashevo/android-dashpay/pull/34
https://github.com/dashevo/dapi-client-android/pull/14
https://github.com/dashevo/android-dpp/pull/13
https://github.com/dashevo/dashj/pull/101
=> DashPay 0.17 Upgrade

wallet/res/layout/contacts_list_layout.xml, wallet/res/layout/contacts_suggestions_header.xml, wallet/res/layout/dashpay_contact_row_content.xml, wallet/res/layout/dashpay_contact_suggestion_row.xml, wallet/res/layout/no_contacts_results.xml, wallet/src/de/schildbach/wallet/ui/ContactViewHolder.kt, wallet/src/de/schildbach/wallet/ui/UsernameSearchResultsAdapter.kt, wallet/src/de/schildbach/wallet/ui/dashpay/ContactSearchResultsAdapter.kt, wallet/src/de/schildbach/wallet/ui/dashpay/ContactsFragment.kt, wallet/src/de/schildbach/wallet/ui/dashpay/DashPayViewModel.kt
=> NMA-734 | Search Contacts/BU Improvement

wallet/src/de/schildbach/wallet/ui/dashpay/NewAccountConfirmDialog.kt
=> NMA-751 | Fiat Symbol Placement

wallet/res/values/strings-extra.xml, wallet/src/de/schildbach/wallet/ui/ImportSharedImageActivity.kt
=> Replace Okay with ok (button_ok)

.travis.yml, wallet/res/layout/activity_dashpay_user.xml, wallet/res/layout/contact_request_view.xml, wallet/src/de/schildbach/wallet/ui/DashPayUserActivity.kt, wallet/src/de/schildbach/wallet/ui/DashPayUserActivityViewModel.kt, wallet/src/de/schildbach/wallet/ui/dashpay/NotificationsForUserLiveData.kt, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt, wallet/src/de/schildbach/wallet/ui/dashpay/widget/ContactRequestPane.kt
NMA-738
Some other unneeded code can still be removed.
None
=> NMA-738: DashPay: User Profile Screen update for Non-Contact

wallet/src/de/schildbach/wallet/ui/AdvancedSecurityActivity.kt, wallet/src/de/schildbach/wallet/ui/SecurityActivity.kt
NMA-768.  All security menu items were crashing
=> NMA-768: DashPay: Fix security menu crashes

wallet/res/layout/activity_security.xml, wallet/res/layout/dialog_select_storage_service.xml, wallet/src/de/schildbach/wallet/ui/SecurityActivity.kt, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt
Android 7 devices had some crashes with the Security Screen was displayed (usually a one time crash).
N/A
=> DashPay: Refactor Security Screen onClick to avoid Android 7 crashes (NMA-768)

wallet/res/layout/activity_create_username.xml, wallet/res/values/strings-extra.xml, wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java, wallet/src/de/schildbach/wallet/ui/CreateUsernameActivity.kt
NMA-763
Closer alignment with iOS and Designs.  Includes removing shadow around edit field and some changes to when the checkmark and x's are shown next to the rules.
=> NMA-763: DashPay: add hyphen validation for usernames

wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java
NMA-771 - in one case, it is possible for the sync percentage to be larger than 100% that will be fixed in this PR.
None
None
=> NMA-771: DashPay: Fix Sync Status > 100 issue

wallet/src/de/schildbach/wallet/ui/SearchUserActivity.kt, wallet/src/de/schildbach/wallet/ui/dashpay/ContactsFragment.kt
[NMA-735 Copy existing contact search string to user search](https://dashpay.atlassian.net/browse/NMA-735)
https://user-images.githubusercontent.com/8437401/105918711-af448000-6034-11eb-805a-52d2d7adde67.mp4
- [x ] I have performed a self-review of my own code and added comments where necessary
=> NMA-735 Copy existing contact search string to user search

wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java, wallet/src/de/schildbach/wallet/ui/MainActivity.kt, wallet/src/de/schildbach/wallet/ui/dashpay/ContactsFragment.kt, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt
=> Small fixes for NMA-781, 735, 777

wallet/src/de/schildbach/wallet/WalletApplication.java, wallet/src/de/schildbach/wallet/ui/LockScreenActivity.kt, wallet/src/de/schildbach/wallet/ui/WalletActivity.java
NMA-516: Fix Resume Crash
https://github.com/dashevo/dash-wallet/pull/617
=> Improvement proposal for NMA-516: Fix Resume Crash #617

wallet/src/de/schildbach/wallet/WalletApplication.java, wallet/src/de/schildbach/wallet/ui/LockScreenActivity.kt, wallet/src/de/schildbach/wallet/ui/WalletActivity.java
NMA-516
This is supposed to fix this crash, which also happens on DashPay:
```
java.lang.RuntimeException: 
at android.app.ActivityThread.performResumeActivity (ActivityThread.java:4062)
at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:4094)
at android.app.servertransaction.ResumeActivityItem.execute (ResumeActivityItem.java:51)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:145)
at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:70)
at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1993)
at android.os.Handler.dispatchMessage (Handler.java:106)
at android.os.Looper.loop (Looper.java:216)
at android.app.ActivityThread.main (ActivityThread.java:7266)
at …
```
=> NMA-516: Fix Resume Crash

wallet/res/layout/fragment_upgrade_to_evolution.xml, wallet/res/values/strings-extra.xml, wallet/src/de/schildbach/wallet/ui/dashpay/UpgradeToEvolutionFragment.kt
=> NMA-802 | Contacts | Upgrade instructions

wallet/res/layout/transaction_result_content.xml
=> NMA-791 | Small Screens | Transaction Details

wallet/src/de/schildbach/wallet/rates/DashRatesSecondFallback.java, wallet/src/de/schildbach/wallet/rates/ExchangeRatesRepository.java
=> Fix Exchange Rate Crash on many screens for Fallback #2 Price Source

wallet/res/values/strings-extra.xml, wallet/schemas/de.schildbach.wallet.AppDatabase/15.json, wallet/src/de/schildbach/wallet/AppDatabase.java, wallet/src/de/schildbach/wallet/Constants.java, wallet/src/de/schildbach/wallet/data/BlockchainIdentityBaseData.kt, wallet/src/de/schildbach/wallet/data/BlockchainIdentityData.kt, wallet/src/de/schildbach/wallet/data/BlockchainIdentityDataDao.kt, wallet/src/de/schildbach/wallet/data/BlockchainIdentityDataDaoAsync.kt, wallet/src/de/schildbach/wallet/data/InvitationLinkData.kt, wallet/src/de/schildbach/wallet/data/RoomConverters.kt, wallet/src/de/schildbach/wallet/livedata/Resource.kt, wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java, wallet/src/de/schildbach/wallet/ui/CreateUsernameActivity.kt, wallet/src/de/schildbach/wallet/ui/MainActivity.kt, wallet/src/de/schildbach/wallet/ui/MainActivityViewModel.kt, wallet/src/de/schildbach/wallet/ui/WalletTransactionsFragment.java, wallet/src/de/schildbach/wallet/ui/dashpay/CreateIdentityNotification.kt, wallet/src/de/schildbach/wallet/ui/dashpay/CreateIdentityService.kt, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt, wallet/src/de/schildbach/wallet/ui/dashpay/work/SendInviteWorker.kt, wallet/src/de/schildbach/wallet/ui/invite/InviteAlreadyClaimedDialog.kt
This will create a username from a valid invitation.  It also handles a few errors.
=> NMA-512 DashPay Create Username from Invitation

common/src/main/res/layout/lock_screen_button.xml, wallet/res/layout/dashpay_contact_row_content.xml, wallet/src/de/schildbach/wallet/ui/ContactViewHolder.kt, wallet/src/de/schildbach/wallet/ui/dashpay/DashPayViewModel.kt, wallet/src/de/schildbach/wallet/ui/dashpay/NotificationsActivity.kt, wallet/src/de/schildbach/wallet/ui/dashpay/NotificationsAdapter.kt, wallet/src/de/schildbach/wallet/ui/dashpay/notification/ContactViewHolder.kt
=> NMA-792-793-794 | Small Screen Fixes for Contacts, User Search and Notifications

build.gradle, wallet/build.gradle
Jcenter will be discontinued on Feb 1, 2022.
=> Add maven central

build.gradle, wallet/build.gradle
Jcenter will not be available starting Feb 1, 2022.
None
=> DashPay: Add maven central

wallet/src/de/schildbach/wallet/WalletApplication.java
This is a suggested improvement for #660
=> Uphold: Auto Logout Immediate

wallet/src/de/schildbach/wallet/ui/DashPayUserActivity.kt, wallet/src/de/schildbach/wallet/ui/DashPayUserActivityViewModel.kt, wallet/src/de/schildbach/wallet/ui/dashpay/TransactionsLiveData.kt
=> NMA-779 | User Payment Activity | Refresh

wallet/res/values/strings-extra.xml
=> NMA-853 | Create Invitation Message

common/src/main/java/org/dash/wallet/common/InteractionAwareActivity.java, common/src/main/java/org/dash/wallet/common/customtabs/CustomTabActivityHelper.java, common/src/main/java/org/dash/wallet/common/util/WalletDataProvider.kt, uphold-integration/src/main/java/org/dash/wallet/integration/uphold/ui/UpholdAccountActivity.java, uphold-integration/src/main/java/org/dash/wallet/integration/uphold/ui/UpholdSplashActivity.java, uphold-integration/src/main/res/layout/uphold_account_screen.xml, uphold-integration/src/main/res/layout/uphold_splash_screen.xml, wallet/AndroidManifest.xml, wallet/res/layout/activity_lock_screen_root.xml, wallet/src/de/schildbach/wallet/AutoLogout.java, wallet/src/de/schildbach/wallet/WalletApplication.java, wallet/src/de/schildbach/wallet/ui/MoreActivity.kt, wallet/src/de/schildbach/wallet/ui/WalletActivity.java
Final improvements of new lock screen architecture supporting StrandHogg vulnerability fix
NMA-865
=> NMA-865 Strandhogg Vulnerability | Uphold Issues

wallet/AndroidManifest.xml, wallet/src/de/schildbach/wallet/Constants.java
=> fix: Allow access to external storage on Android 10 (NMA-868)

build.gradle, common/src/main/java/org/dash/wallet/common/Configuration.java, common/src/main/java/org/dash/wallet/common/ui/FancyAlertDialog.kt, common/src/main/res/layout/fancy_alert_dialog.xml, wallet/res/drawable/ic_invitation_contact_request_error.xml, wallet/res/drawable/ic_invitation_contact_request_sent.xml, wallet/res/layout/invite_send_contact_request_view.xml, wallet/res/values/strings-extra.xml, wallet/src/de/schildbach/wallet/ui/MainActivity.kt, wallet/src/de/schildbach/wallet/ui/MainActivityViewModel.kt, wallet/src/de/schildbach/wallet/ui/dashpay/CreateIdentityService.kt, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt, wallet/src/de/schildbach/wallet/ui/invite/InviteSendContactRequestDialog.kt
NMA-271 Accept Invite | Send Contact Request
=> NMA-271 Accept Invite | Send Contact Request

wallet/src/de/schildbach/wallet/ui/dashpay/DashPayViewModel.kt, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt, wallet/src/de/schildbach/wallet/ui/dashpay/work/BaseWorker.kt
* put stack traces of exceptions related to errors in logs
* handle cases where profile has no username, which threw exception
=> NMA-858: DashPay: Failed to receive 

build.gradle, wallet/build.gradle
=> build: DashPay: Remove bintray/jfrog

wallet/build.gradle, wallet/src/de/schildbach/wallet/data/RoomConverters.kt
https://github.com/dashevo/android-dpp/pull/18
https://github.com/dashevo/dapi-client-android/pull/21
https://github.com/dashevo/android-dashpay/pull/46
=> feat: Update to DPP 0.19: NMA-882

wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java, wallet/src/de/schildbach/wallet/ui/dashpay/CreateIdentityService.kt, wallet/src/de/schildbach/wallet/ui/send/SendCoinsFragment.java, wallet/src/de/schildbach/wallet/ui/widget/ReceiveInfoView.kt
In addition to supporting the TestNet Network, this PR will also patch up two crashes that can happen when the User goes to other screens (Receive, Send payment flow) while the username registration process is in progress.
NMA-894
https://github.com/dashevo/android-dashpay/pull/47
https://github.com/dashevo/dapi-client-android/pull/22
=> fix: Support Testnet v19, NMA-891

wallet/src/de/schildbach/wallet/ui/TransactionsAdapter.java
=> fix: dashpay: don't associate internal tx's with usernames (NMA-880)

wallet/src/de/schildbach/wallet/ui/dashpay/ContactSearchResultsAdapter.kt
=> fix: show view all if pending contact requests > 3 (NMA-652)

liquid-integration/src/main/java/org/dash/wallet/integration/liquid/data/LiquidClient.kt, liquid-integration/src/main/java/org/dash/wallet/integration/liquid/ui/BuyDashWithCreditCardActivity.kt, uphold-integration/src/main/java/org/dash/wallet/integration/uphold/data/UpholdClient.java
Replaced custom implementation of logging interceptor with more reliable HttpLoggingInterceptor
N/A
=> Replaced custom logging interceptor with HttpLoggingInterceptor

liquid-integration/src/main/java/org/dash/wallet/integration/liquid/data/LiquidClient.kt, liquid-integration/src/main/java/org/dash/wallet/integration/liquid/ui/BuyDashWithCreditCardActivity.kt, liquid-integration/src/main/java/org/dash/wallet/integration/liquid/ui/BuyDashWithCryptoCurrencyActivity.kt, liquid-integration/src/main/java/org/dash/wallet/integration/liquid/ui/LiquidBuyAndSellDashActivity.kt, liquid-integration/src/main/java/org/dash/wallet/integration/liquid/ui/LiquidSplashActivity.kt, liquid-integration/src/main/java/org/dash/wallet/integration/liquid/ui/SellDashActivity.kt, uphold-integration/src/main/java/org/dash/wallet/integration/uphold/data/UpholdClient.java, wallet/src/de/schildbach/wallet/ui/BuyAndSellLiquidUpholdActivity.kt, wallet/src/de/schildbach/wallet/ui/OnboardingActivity.kt
Add logging to Liquid Integration
N/A
=> chore: add logging to liquid integration (NMA-903)

gradle/google-services.gradle, wallet/build.gradle
This will allow other developers to build from source without DCG's gradle services file.
=> build: make google-services optional

wallet/src/de/schildbach/wallet/ui/LockScreenActivity.kt, wallet/src/de/schildbach/wallet/ui/OnboardingActivity.kt
=> fix: prevent LockScreen from appearing if AutoLogout = OFF (NMA-926)

sample-integration-android/src/de/schildbach/wallet/integration/sample/SampleActivity.java, wallet/src/de/schildbach/wallet/ui/TransactionResultActivity.kt, wallet/src/de/schildbach/wallet/ui/send/SendCoinsActivity.java, wallet/src/de/schildbach/wallet/ui/send/SendCoinsFragment.java
=> fix: disable lock screen while going through deep link payment flow (NMA-294)

wallet/src/de/schildbach/wallet/ui/TransactionsAdapter.java
=> fix: use locale to format transaction dates (NMA-929)

liquid-integration/src/main/res/values/strings-liquid.xml, wallet/src/de/schildbach/wallet/ui/LockScreenActivity.kt, wallet/src/de/schildbach/wallet/ui/SecurityActivity.kt, wallet/src/de/schildbach/wallet/ui/backup/RestoreFromFileActivity.kt
=> fix: Remove obsolsete requests for file permissions

wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt
This fixes an NPE for cases where an invite has not been accepted or used.
```
14:44:06 [DefaultDispatcher-worker-4] DapiClient - RPC failed with 54.191.15.3: Status{code=NOT_FOUND, description=Identity not found, cause=null}: Metadata(server=nginx/1.19.10,date=Thu, 01 Jul 2021 14:44:06 GMT,content-type=application/grpc,content-length=0)
14:44:06 [DefaultDispatcher-worker-4] DapiClient -   for getIdentity(23YEXFwG5t4cmx2AkSMArSzA7roGRpSmJwCTP1dA3Zq6)
14:44:06 [DefaultDispatcher-worker-4] CrashReporter - crashing because of uncaught exception
java.lang.NullPointerException: null
at de.schildbach.wallet.ui.dashpay.PlatformRepo.updateDashPayProfile(PlatformRepo.kt:854) ~[na:0.0]
at de.schildbach.wallet.ui.invite.InvitationFragmentViewModel$updateInvitedUserProfile$1.invokeSuspend(InvitationFr …
```
=> fix: prevent crash if identity does not exist (NMA-933)

wallet/src/de/schildbach/wallet/ui/CheckPinDialog.kt, wallet/src/de/schildbach/wallet/ui/DecryptSeedWithPinDialog.kt, wallet/src/de/schildbach/wallet/ui/LockScreenActivity.kt, wallet/src/de/schildbach/wallet/ui/LockScreenViewModel.kt, wallet/src/de/schildbach/wallet/ui/send/SendCoinsInternalActivity.java
The goal of this PR is to prevent this:
=> fix: dismiss PIN entry dialogs upon autologout (NMA-940)

common/src/main/java/org/dash/wallet/common/InteractionAwareActivity.java
This is a possible fix for this crash:
```java
java.lang.IllegalArgumentException: 
at android.app.LoadedApk.forgetReceiverDispatcher (LoadedApk.java:1293)
at android.app.ContextImpl.unregisterReceiver (ContextImpl.java:1531)
at android.content.ContextWrapper.unregisterReceiver (ContextWrapper.java:659)
at android.content.ContextWrapper.unregisterReceiver (ContextWrapper.java:659)
at org.dash.wallet.common.InteractionAwareActivity.finish (InteractionAwareActivity.java:60)
at de.schildbach.wallet.ui.VerifySeedActivity.finish (VerifySeedActivity.kt:157)
at de.schildbach.wallet.ui.VerifySeedActivity.goHome (VerifySeedActivity.kt:153)
at de.schildbach.wallet.ui.VerifySeedActivity.skipSeedVerification (VerifySeedActivity.kt:118)
at de.schildbach.wallet.ui.VerifySeedSecureNowFragment$onViewCreat …
```
=> fix: prevent crashes from unregistering receiver (NMA-983)

wallet/src/de/schildbach/wallet/ui/send/PaymentProtocolFragment.kt
This will make exchange rates live on the BIP70 related screens (`PaymentProtocolFragment`)
No changes were made to when the rates are queried.  The goal is ensure that the exchange rates used on this screen are up to date rather than using the last values stored in the Room database in the past.
=> BIP70 live exchange rates (NMA-949)

wallet/res/values/strings-extra.xml, wallet/src/de/schildbach/wallet/ui/CreateUsernameActivity.kt, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformPaymentConfirmDialog.kt, wallet/src/de/schildbach/wallet/ui/invite/InviteCreatedFragment.kt
This also resolves two problems with the LockScreen appearing during onboarding (even before a PIN is set)
https://github.com/dashevo/dapi-client-android/pull/27 (fixes a bug when submitting ST's)
=> fix: resolve some DashPay Issues (NMA-970, 973)

wallet/AndroidManifest.xml, wallet/res/values/strings-extra.xml, wallet/src/de/schildbach/wallet/ui/CreateUsernameActivity.kt, wallet/src/de/schildbach/wallet/ui/InviteHandlerActivity.kt, wallet/src/de/schildbach/wallet/ui/InviteHandlerViewModel.kt, wallet/src/de/schildbach/wallet/ui/OnboardingActivity.kt, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformPaymentConfirmDialog.kt, wallet/src/de/schildbach/wallet/ui/invite/InviteCreatedFragment.kt, wallet/src/de/schildbach/wallet/ui/invite/InviteHandler.kt
=> [NMA-965] the invitation is not verified if it has been claimed before an attempt to register user( when the wallet is not initialized)

wallet/src/de/schildbach/wallet/ui/MainActivity.kt
NMA-836 Low Storage Authentication / Old Dialogue messages
=> [NMA-836] Low Storage Authentication / Old Dialogue messages

wallet/AndroidManifest.xml
=> fix: prevent duplicate instance for import private key (NMA-953)

wallet/src/de/schildbach/wallet/ui/EditProfileActivity.kt, wallet/src/de/schildbach/wallet/ui/LockScreenActivity.kt
=> fix: disable autologout timer when selecting photos or taking pictures

wallet/res/layout/activity_about.xml, wallet/res/layout/activity_crop_image.xml, wallet/res/layout/activity_search_dashpay_profile_root.xml, wallet/res/layout/activity_set_pin.xml, wallet/res/values/strings-extra.xml, wallet/src/de/schildbach/wallet/ui/AboutActivity.kt, wallet/src/de/schildbach/wallet/ui/OnboardingActivity.kt, wallet/src/de/schildbach/wallet/ui/TransactionResultActivity.kt, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt, wallet/src/de/schildbach/wallet/ui/dashpay/work/SendInviteWorker.kt, wallet/src/de/schildbach/wallet/ui/invite/InviteHandler.kt
=> NMA-968 - fix (dashpay): hide restore from file when onboarding if using invite

build.gradle, common/build.gradle, common/src/main/java/org/dash/wallet/common/services/AnalyticsService.kt, common/src/main/java/org/dash/wallet/common/services/analytics/AnalyticsConstants.kt, common/src/main/java/org/dash/wallet/common/services/analytics/AnalyticsService.kt, wallet/build.gradle, wallet/res/layout/activity_about.xml, wallet/res/layout/activity_settings.xml, wallet/res/layout/activity_tools.xml, wallet/src/de/schildbach/wallet/ui/AboutActivity.kt, wallet/src/de/schildbach/wallet/ui/SettingsActivity.kt, wallet/src/de/schildbach/wallet/ui/ToolsActivity.kt
Firebase events for Tools & Settings
=> [NMA-995] Firebase Settings & Tools events

.github/workflows/manual_distribution.yml
=> fix: remove trailing comma from manual_distribution.yml

.github/workflows/manual_distribution.yml
See https://github.com/dashevo/dash-wallet/pull/751
https://github.com/dashevo/dash-wallet/pull/751
=> Actions fix: Dashpay build number fix

liquid-integration/src/main/java/org/dash/wallet/integration/liquid/data/LiquidClient.kt, uphold-integration/src/main/java/org/dash/wallet/integration/uphold/data/UpholdClient.java
This will enable us to determine the causes of failures for users who have issues with Uphold and Liquid
=> fix: use the apps logger instead of the default HttpLoggingIntercepter logger

common/src/main/java/org/dash/wallet/common/services/analytics/AnalyticsConstants.kt, wallet/build.gradle, wallet/res/layout/dialog_transactions_filter.xml, wallet/res/layout/wallet_transactions_fragment.xml, wallet/src/de/schildbach/wallet/ui/GlobalFooterActivity.kt, wallet/src/de/schildbach/wallet/ui/HeaderBalanceFragment.java, wallet/src/de/schildbach/wallet/ui/TransactionsFilterDialog.kt, wallet/src/de/schildbach/wallet/ui/WalletActivity.java, wallet/src/de/schildbach/wallet/ui/WalletTransactionsFragment.java
Firebase events for the home screen. Also moved [TransactionsFilterDialog](https://github.com/dashevo/dash-wallet/blob/master/wallet/src/de/schildbach/wallet/ui/TransactionsFilterDialog.kt) to view bindings and did some cleanup in there.
https://github.com/dashevo/dash-wallet/pull/724
https://github.com/dashevo/dash-wallet/pull/737
https://github.com/dashevo/dash-wallet/pull/742
https://github.com/dashevo/dash-wallet/pull/753
=> [NMA-1017] Firebase events for the home screen

wallet/src/de/schildbach/wallet/ui/MoreFragment.kt, wallet/src/de/schildbach/wallet/ui/SearchUserActivity.kt, wallet/src/de/schildbach/wallet/ui/dashpay/ContactsFragment.kt, wallet/src/de/schildbach/wallet/ui/dashpay/NotificationsActivity.kt, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt
Invite features do not depend on developer mode.
None
=> feat (dashpay): enable invites for all builds

common/src/main/java/org/dash/wallet/common/services/analytics/AnalyticsConstants.kt, common/src/main/java/org/dash/wallet/common/services/analytics/AnalyticsService.kt, wallet/res/layout/activity_payments.xml, wallet/res/layout/enter_amount_fragment.xml, wallet/src/de/schildbach/wallet/ui/EnterAmountFragment.kt, wallet/src/de/schildbach/wallet/ui/PaymentsPayFragment.kt, wallet/src/de/schildbach/wallet/ui/PaymentsReceiveFragment.kt, wallet/src/de/schildbach/wallet/ui/widget/ReceiveInfoView.kt
Firebase events for Send, Receive, and Enter Amount screens. Additionally, I turned off event and crash logging for debug builds so that developer activity doesn't clutter the statistic.
https://github.com/dashevo/dash-wallet/pull/724
https://github.com/dashevo/dash-wallet/pull/737
https://github.com/dashevo/dash-wallet/pull/742
https://github.com/dashevo/dash-wallet/pull/753
https://github.com/dashevo/dash-wallet/pull/756
=> [NMA-1018] Send & Receive firebase events

wallet/src/de/schildbach/wallet/adapter/ExchangeRatesAdapter.java, wallet/src/de/schildbach/wallet/ui/EnterAmountFragment.kt, wallet/src/de/schildbach/wallet/ui/SettingsActivity.kt
=> fix search exchange rate using currency symbol and currency code

wallet/AndroidManifest.xml, wallet/src/de/schildbach/wallet/ui/ExchangeRatesFragment.java, wallet/src/de/schildbach/wallet/ui/WalletTransactionsFragment.java, wallet/src/de/schildbach/wallet/ui/send/SweepWalletFragment.java
We have some retained fragments which don't play well with Hilt.
=> [NMA-1035] Bugfix: Hilt crash in rescan blockchain

build.gradle, wallet/AndroidManifest.xml, wallet/src/de/schildbach/wallet/ui/SettingsActivity.kt, wallet/src/de/schildbach/wallet/ui/dashpay/CreateIdentityService.kt
Updating Firebase BOM to 28.4.2 also requires updating DashJ to use protobuf-javalite 3.14.0
https://github.com/dashevo/dashj/pull/137
=> DashPay: update firebase (NMA-1064)

build.gradle, wallet/build.gradle
This removes the need for JCenter.
=> DashWallet: Remove JCenter (NMA-890)

build.gradle, common/src/main/java/org/dash/wallet/common/ui/orbitview/OrbitView.kt, common/src/main/java/org/dash/wallet/common/ui/orbitview/PlanetView.kt, common/src/main/res/values/attrs.xml, common/src/main/res/values/colors.xml, wallet/build.gradle, wallet/res/layout/users_orbit.xml
This PR removes all JCenter usage
none
=> DashPay:  remove JCenter (NMA-890)

.github/workflows/dashwallet.yml
This will make our CI pipelines run when PRs are made to feature-* and bugfix-* branches.
=> feat: CI for feature-* and bugfix-* branches

wallet/res/values/strings-extra.xml, wallet/src/de/schildbach/wallet/WalletApplication.java, wallet/src/de/schildbach/wallet/livedata/SeriousErrorLiveData.kt, wallet/src/de/schildbach/wallet/ui/MainActivity.kt, wallet/src/de/schildbach/wallet/ui/MainActivityViewModel.kt, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt, wallet/src/de/schildbach/wallet/ui/security/ModernEncryptionProvider.java, wallet/src/de/schildbach/wallet/ui/security/SecurityGuard.java
Add logging to trace missing encryptionIv that prevents receiving contact requests.
Other critical functions may be affected by this bug.
Restarting the app seems to resolve the problem.
Additionally, we will add logging to track when activities are created and destroyed to help identify other bugs found during testing.
=> feat(dashpay): add tracking of a missing encryptionIv and alert user - NMA-1083

.github/workflows/dashwallet.yml, .github/workflows/manual_distribution.yml, wallet/README.md, wallet/build.gradle, wallet/src/de/schildbach/wallet/Constants.java
=> feat: use local.properties for support email (NMA-1071)

wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt, wallet/src/de/schildbach/wallet/ui/dashpay/work/SendInviteWorker.kt
This will fix invitation creation bugs
Fix rate cases of invitation creation failures
=> fix: propagate Context into current thread during invite creation (NMA-1090)

wallet/build.gradle, wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java
DashJ PR's:
https://github.com/dashevo/dashj/pull/142 (allow lower protocols, to support DashPay)
https://github.com/dashevo/dashj/pull/141
https://github.com/dashevo/dashj/pull/140 (extract BLS to its own library/repo)
https://github.com/dashevo/dashj/pull/139
https://github.com/dashevo/dashj/pull/120
https://github.com/dashevo/dashj/pull/106
https://github.com/dashevo/dashj/pull/143
DashJ-BLS:
https://github.com/dashevo/dashj-bls (this is not a PR, but where the code removed in https://github.com/dashevo/dashj/pull/140 went)
DashJ-Android PR:
https://github.com/dashevo/dashj-android/pull/3 (aligning versions with DashJ-BLS)
=> Updates for Dash Core 0.18 Phase Two (NMA-1078)

wallet/src/de/schildbach/wallet/ui/invite/InviteCreatedFragment.kt
=> Bugfix: dashpay invite save tag on maybe later button (NMA-1097)

wallet/src/de/schildbach/wallet/ui/dashpay/NotificationsActivity.kt, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt
The below criteria are not being fulfilled.
- This should not visible unless the chain is fully synced
- This should be hidden/dismissed after the user enters the flow from this notification
=> Bugfix: dashpay notification alert bugs (NMA-1098)

.github/workflows/dashpay.yml, .github/workflows/dashwallet.yml, .github/workflows/manual_distribution.yml
Fixing ruby action in github actions pipelines.
`actions/setup-ruby` isn't maintained anymore and needs to be replaced with `ruby/setup-ruby`.
=> fix (dashpay): migrating from actions/setup-ruby to ruby/setup-ruby

build.gradle, common/build.gradle, liquid-integration/build.gradle, uphold-integration/build.gradle, wallet/build.gradle, wallet/src/de/schildbach/wallet/Constants.java, wallet/src/de/schildbach/wallet/WalletApplication.java, wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java, wallet/src/de/schildbach/wallet/ui/InputParser.java, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt, wallet/src/de/schildbach/wallet/ui/send/SendCoinsActivity.java, wallet/src/de/schildbach/wallet/util/WalletUtils.java
Code in this PR for the most part is removing an obsolete reference in DashJ.
see: 
https://github.com/dashevo/dashj/pull/144
https://github.com/dashevo/android-dpp/pull/29
https://github.com/dashevo/dapi-client-android/pull/34
https://github.com/dashevo/android-dashpay/pull/56
https://github.com/dashevo/android-dpp/pull/26
=> DashPay: Support Core 0.18 (NMA-1025)

build.gradle, wallet/src/de/schildbach/wallet/ui/MainActivityViewModel.kt, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt
Prevent crashes when loading blockchain information from the database and updating profiles when there are problems connecting to platform to get Identity information.
https://github.com/dashevo/android-dashpay/pull/57
=> fix(dashpay): prevent network unavailability crashes with Platform

features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/ExploreMapFragment.kt, features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/ExploreViewModel.kt, features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/SearchFragment.kt, features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/dialogs/FiltersDialog.kt
Any change in the `radius` filter was not reflected zoom level of the map
=> fix: update map zoom level as per radius filter change

features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/SearchFragment.kt
There is a problem I missed with https://github.com/dashevo/dash-wallet/pull/835: if we select a territory, the bottom sheet stays expanded for physical locations. This shouldn't be the case, we should always show the map for a point with coordinates (unless opened from the Online tab).
Changed the `setBottomSheetState` method and simplified conditions check to make it more clear.
The logic that we have for the bottom sheet and some other components in explore-dash got quite complicated and not too intuitive, as evident from difficulties other developers have while changing it. This is the result of having multiple different logical screens that live in a single physical one. I have some ideas for refactoring this to make it less convoluted, but for now, we just need a fix for the …
=> bugfix (Explore Dash): expanded bottom sheet in details mode

common/src/main/java/org/dash/wallet/common/services/analytics/AnalyticsConstants.kt, common/src/main/java/org/dash/wallet/common/services/analytics/AnalyticsService.kt, uphold-integration/src/main/java/org/dash/wallet/integration/uphold/data/UpholdApiException.java, uphold-integration/src/main/java/org/dash/wallet/integration/uphold/data/UpholdClient.java, uphold-integration/src/main/java/org/dash/wallet/integration/uphold/ui/UpholdAccountActivity.java, uphold-integration/src/main/java/org/dash/wallet/integration/uphold/ui/UpholdSplashActivity.java, wallet/src/de/schildbach/wallet/di/AppModule.kt, wallet/src/de/schildbach/wallet/ui/BuyAndSellLiquidUpholdActivity.kt
Logging firebase events for Uphold.
=> [NMA-1121] Uphold events

common/src/main/java/org/dash/wallet/common/Constants.java, common/src/main/java/org/dash/wallet/common/util/GenericUtils.java, integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/ui/CoinbaseServicesFragment.kt, wallet/src/de/schildbach/wallet/adapter/BuyAndSellDashServicesAdapter.kt, wallet/src/de/schildbach/wallet/ui/BuyAndSellLiquidUpholdActivity.kt
Fix the Local currency format to match figma
=> NMA-1134 : fix the local currency

common/src/main/java/org/dash/wallet/common/services/analytics/AnalyticsConstants.kt, wallet/src/de/schildbach/wallet/ui/MainActivity.kt, wallet/src/de/schildbach/wallet/ui/WalletTransactionsFragment.java, wallet/src/de/schildbach/wallet/ui/dashpay/CreateIdentityService.kt
=> fix(dashpay): add missing create username, payments, tx details events (NMA-1118)

common/src/main/java/org/dash/wallet/common/services/analytics/AnalyticsConstants.kt, wallet/src/de/schildbach/wallet/ui/WalletActivity.java
=> fix: rename event for More -> Buy/Sell Dash (NMA-1118, 1129)

features/exploredash/src/main/java/org/dash/wallet/features/exploredash/data/ExploreDataSource.kt, features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/ExploreViewModel.kt, features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/SearchFragment.kt, features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/adapters/MerchantsAtmsResultAdapter.kt, features/exploredash/src/test/java/org/dash/wallet/features/exploredash/MerchantAtmDataSourceTest.kt, wallet/src/de/schildbach/wallet/ExploreSyncWorker.kt
Online merchants should not have a distance showing up in the search results, and should not appear in the Nearby tab if the location is disabled.
Also, there were some issues with synchronization that lead to `last_updated` being saved locally even if some of the data sources had failed to synchronize.
=> [NMA-1144] (Explore Dash) Distance for online-only merchants & sync fixes

wallet/src/de/schildbach/wallet/ui/send/SweepWalletFragment.java
=> fix: save decryptDialog to allow closing it later based on the state (NMA-1136)

common/src/main/java/org/dash/wallet/common/services/analytics/AnalyticsConstants.kt, common/src/main/java/org/dash/wallet/common/services/analytics/AnalyticsService.kt, common/src/main/java/org/dash/wallet/common/ui/FancyAlertDialog.kt, uphold-integration/src/main/java/org/dash/wallet/integration/uphold/data/UpholdApiException.java, uphold-integration/src/main/java/org/dash/wallet/integration/uphold/data/UpholdClient.java, uphold-integration/src/main/java/org/dash/wallet/integration/uphold/ui/UpholdAccountActivity.java, uphold-integration/src/main/java/org/dash/wallet/integration/uphold/ui/UpholdSplashActivity.java, wallet/src/de/schildbach/wallet/di/AppModule.kt, wallet/src/de/schildbach/wallet/ui/BuyAndSellLiquidUpholdActivity.kt, wallet/src/de/schildbach/wallet/ui/EnterAmountFragment.kt, wallet/src/de/schildbach/wallet/ui/ExchangeRatesActivity.java, wallet/src/de/schildbach/wallet/ui/ExchangeRatesFragment.java, wallet/src/de/schildbach/wallet/ui/FancyListFragment.java, wallet/src/de/schildbach/wallet/ui/LockScreenActivity.kt, wallet/src/de/schildbach/wallet/ui/SettingsActivity.kt, wallet/src/de/schildbach/wallet/ui/WalletActivity.java, wallet/src/de/schildbach/wallet/ui/send/SweepWalletFragment.java
According to the https://github.com/dashevo/dash-wallet/pull/850#discussion_r775573551 we need to resolve merge conflicts between uphold events logging and coinbase-integration changes.
=> Fix: master-coinbase merge conflicts

features/exploredash/src/main/java/org/dash/wallet/features/exploredash/data/model/AtmFTS.kt, wallet/res/layout/activity_about.xml, wallet/res/values-ar/strings-extra.xml, wallet/res/values-bg/strings-extra.xml, wallet/res/values-cs/strings-extra.xml, wallet/res/values-de/strings-extra.xml, wallet/res/values-el/strings-extra.xml, wallet/res/values-es/strings-extra.xml, wallet/res/values-fil/strings-extra.xml, wallet/res/values-fr/strings-extra.xml, wallet/res/values-id/strings-extra.xml, wallet/res/values-it/strings-extra.xml, wallet/res/values-ja/strings-extra.xml, wallet/res/values-ko/strings-extra.xml, wallet/res/values-nl/strings-extra.xml, wallet/res/values-pl/strings-extra.xml, wallet/res/values-pt/strings-extra.xml, wallet/res/values-ru/strings-extra.xml, wallet/res/values-sk/strings-extra.xml, wallet/res/values-th/strings-extra.xml, wallet/res/values-tr/strings-extra.xml, wallet/res/values-vi/strings-extra.xml, wallet/res/values-zh-rTW/strings-extra.xml, wallet/res/values-zh/strings-extra.xml, wallet/res/values/strings-extra.xml, wallet/src/de/schildbach/wallet/AppDatabase.java, wallet/src/de/schildbach/wallet/ExploreSyncWorker.kt, wallet/src/de/schildbach/wallet/data/AppDatabaseMigrations.kt, wallet/src/de/schildbach/wallet/ui/AboutActivity.kt
We want to show the time of the last data load and last sync in the About section. I have also added logging of non-fatal crashes so that we can see sync problems in Firebase immediately.
Additionally, I've updated most of the strings with 2022 copyright year and added manufacturer as a field for searching over ATMs as we wanted but didn't do for the last build.
=> [NMA-1157] Last sync times in about screen

features/exploredash/src/main/java/org/dash/wallet/features/exploredash/repository/ExploreRepository.kt, wallet/build.gradle
We're getting NPE when using `!!` operator in firebase repository when fetching last_update field and then doing `dataSnapshot.getValue<Long>()!!`. 
Why does last_update returns null in the first place is unclear and should be investigated, but for now we should catch this problem and log it as non-fatal crash.
=> [NMA-1160] NPE in fireabase repository

wallet/README.md, wallet/build.gradle, wallet/schnapps/res/values/strings-extra.xml, wallet/schnapps/res/values/values.xml, wallet/src/de/schildbach/wallet/Constants.java, wallet/src/de/schildbach/wallet/ui/dashpay/CreateIdentityService.kt, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt, wallet/src/de/schildbach/wallet/ui/invite/InvitesHistoryFragment.kt
=> DPP 0.22 Updates

wallet/build.gradle, wallet/schnapps/res/values/values.xml, wallet/src/de/schildbach/wallet/Constants.java, wallet/src/de/schildbach/wallet/ui/dashpay/CreateIdentityService.kt, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt, wallet/src/de/schildbach/wallet/ui/explore/ExploreTestNetFragment.kt, wallet/src/de/schildbach/wallet/ui/invite/InviteHandler.kt
Since this PR only pertains to the 0.22 devnet (krupniks), it will be merged to a feature branch.  The dashpay branch will continue to work with 0.21 Platform on Testnet only.
dpp: https://github.com/dashevo/android-dpp/pull/31 (queries, error handling, contract updates)
dapi-client: https://github.com/dashevo/dapi-client-android/pull/36 (new permanent contract id's)
dashpay: https://github.com/dashevo/android-dashpay/pull/60
dashj: https://github.com/dashevo/dashj/pull/153
dashj-merk: https://github.com/dashevo/dashj-merk/pull/3
dashj-merk-android: https://github.com/dashevo/dashj-merk-android/pull/3
=> feat(dashpay): update for DPP 0.22 (queries, error handling, etc)

features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/ExploreViewModel.kt, features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/SearchFragment.kt, features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/adapters/SearchHeaderAdapter.kt, features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/dialogs/FiltersDialog.kt, features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/extensions/LocationFragmentExt.kt, features/exploredash/src/main/res/layout/dialog_filters.xml, features/exploredash/src/main/res/layout/fragment_search.xml, features/exploredash/src/main/res/layout/manage_gps_view.xml, features/exploredash/src/main/res/layout/search_header_view.xml, features/exploredash/src/test/java/org/dash/wallet/features/exploredash/ExploreViewModelTest.kt
When we don't have location permission, there is no point in the Nearby tab as it's hardly different from the All tab in this case. 
Instead of showing search results, we display a message and a button that initiates a location request flow - the same as in the filters dialog.
=> [NMA-1154] (Explore Dash) Nearby search results shouldn't show if location is disabled

build.gradle
Bumping dashj to the version that supports version 3 transactions.
=> [NMA-1187] Version 3 Transactions Are Standard

wallet/src/de/schildbach/wallet/ExploreSyncWorker.kt
=> fix: force preloading explore.db if exploreRepository.localTimestamp is not set

wallet/src/de/schildbach/wallet/AppDatabase.java, wallet/src/de/schildbach/wallet/data/AppDatabaseMigrations.kt
in v7.4.6 the Explore Dash Sync System was improved and the Explore Dash data was moved to its own database.
A conversation here was about which versions should be used to remove the Explore Dash data from the primary database:
https://github.com/dashevo/dash-wallet/pull/881#discussion_r804623660
The PR originally had 4 to 9.
However, it was discovered in testing that the explore dash data was not removed after upgrading.
These are the database versions used in previous releases:
v7.4.6 - version 9 - https://github.com/dashevo/dash-wallet/blob/v7.4.6/wallet/src/de/schildbach/wallet/AppDatabase.java#L21
v7.4.5 - version 8 - https://github.com/dashevo/dash-wallet/blob/v7.4.5/wallet/src/de/schildbach/wallet/AppDatabase.java#L32
v7.4.1 - version 8 - …
=> fix: change migration from 8to10 to 9to10 since v7.4.1-5 were version 8

wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java, wallet/src/de/schildbach/wallet/util/AllowLockTimeRiskAnalysis.kt
=> feat: allow v2 transactions with absolute locktime to appear before being mined

wallet/build.gradle
I was trying out a means of requiring the support email be set on a release build.  Unfortunately this was commited on the last version bump commit and it breaks CI.  Let's remove it.
=> chore: remove requirements for setting email (breaks ci actions)

integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/di/CoinBaseModule.kt, integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/network/RemoteDataSource.kt, integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/network/ResponseResource.kt, integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/repository/CoinBaseRepository.kt, integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/repository/remote/TokenAuthenticator.kt, integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/service/CloseCoinbasePortalBroadcaster.kt, integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/service/CoinBaseServicesApi.kt, integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/service/CoinBaseTokenRefreshApi.kt, integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/viewmodels/CoinbaseBuyDashOrderReviewViewModel.kt, integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/viewmodels/CoinbaseBuyDashViewModel.kt, integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/viewmodels/CoinbaseConversionPreviewViewModel.kt, integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/viewmodels/CoinbaseConvertCryptoViewModel.kt, integrations/coinbase-integration/src/test/java/org/dash/wallet/integration/coinbase_integration/CoinBaseRepositoryTest.kt, wallet/src/de/schildbach/wallet/ui/coinbase/CoinbaseActivity.kt
=> feat: logout coinbase user with invalid token

common/src/main/java/org/dash/wallet/common/services/analytics/AnalyticsConstants.kt, features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/ExploreViewModel.kt, features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/dialogs/FiltersDialog.kt
Track firebase events in explore dash for flows related to the ATM filter
=> feat: explore dash firebase atm filter

common/src/main/java/org/dash/wallet/common/Constants.java, features/exploredash/src/main/java/org/dash/wallet/features/exploredash/repository/ExploreRepository.kt, wallet/src/de/schildbach/wallet/Constants.java, wallet/src/de/schildbach/wallet/ui/ReportIssueDialogBuilder.java
=> [NMA-1222] Google Cloud | Testnet DB

common/src/main/java/org/dash/wallet/common/services/analytics/AnalyticsConstants.kt, common/src/main/java/org/dash/wallet/common/services/analytics/AnalyticsTimer.kt, wallet/build.gradle, wallet/src/de/schildbach/wallet/ui/HeaderBalanceFragment.java, wallet/src/de/schildbach/wallet/ui/HeaderBalanceViewModel.kt, wallet/src/de/schildbach/wallet/ui/SearchUserActivity.kt, wallet/src/de/schildbach/wallet/ui/dashpay/CreateIdentityService.kt, wallet/src/de/schildbach/wallet/ui/dashpay/DashPayViewModel.kt, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt
https://github.com/dashevo/dapi-client-android/pull/41
=> Feat(dashpay): log event timing for platform functions (NMA-1249)

common/src/main/java/org/dash/wallet/common/services/SecurityModel.kt, wallet/src/de/schildbach/wallet/di/AppModule.kt, wallet/src/de/schildbach/wallet/ui/CheckPinDialog.kt, wallet/src/de/schildbach/wallet/ui/security/PinCodeRequestLauncher.kt
CrowdNode has some changes with the `CheckPinDialog` to be able to request pin-code with callback or coroutine. Additionally, there is a service to do that from other modules but `wallet`. We can use this in other branches.
=> feat: an interface for requesting pin code from feature modules

wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt
Changes are related to starting the Blockchain Service if the app is in the background.  This problem may be a result of a race condition if a Contact Request is received when the app is in the background as the Blockchain Service is shutting down.
When the Blockchain Service is shutting down, that should also stop the Job that is pulling Contact Request Updates.
Though QA has passed, the problem of trying to start the Blockchain service while in the background was rare, so we don't actually know if this fix works.  We have to wait for the Alpha Program feedback.
This PR is being merged into the Release 5.2 branch, though it also needs to be merged into the `dashpay` branch in some way.
=> fix: don't start blockchain service if the app is in the background

common/src/main/java/org/dash/wallet/common/services/SendPaymentService.kt, integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/model/CoinBaseUserAccountInfo.kt, integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/ui/TransferDashFragment.kt, integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/viewmodels/EnterAmountToTransferViewModel.kt, integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/viewmodels/TransferDashViewModel.kt, wallet/src/de/schildbach/wallet/payments/SendCoinsTaskRunner.kt, wallet/src/de/schildbach/wallet/ui/BuyAndSellViewModel.kt, wallet/src/de/schildbach/wallet/ui/send/ConfirmTransactionDialog.kt, wallet/src/de/schildbach/wallet/ui/send/SendCoinsFragment.java
We want the user to be able to transfer dash from the wallet to Coinbase
The work related to this story has originally been started and almost completed in [this PR](https://github.com/dashevo/dash-wallet/pull/940)
The main improvement brought here was the implementation to get the blockchain fee used in the transaction
=> feat: transfer dash from wallet to coinbase

wallet/res/values/strings.xml, wallet/src/de/schildbach/wallet/util/WalletUtils.java
=> Bugfix: export csv fixes (NMA-1261)

build.gradle
DashJ 0.17.11 includes a fix for xpubs and for allowing Version 3 transactions to be seen immediately upon receiving them.
=> chore: use dashj 0.17.11

integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/ui/EnterTwoFaCodeFragment.kt
=> feat: resume coinbase portal from 2FA UI on autologout

common/src/main/java/org/dash/wallet/common/ui/dialogs/AdaptiveDialog.kt, wallet/src/de/schildbach/wallet/ui/LockScreenActivity.kt
This PR will only apply the fixes for 2 of the crashes that are to be fixed with https://github.com/dashevo/dash-wallet/pull/937.
=> Bugfix lockscreen crashes part 1

wallet/src/de/schildbach/wallet/Constants.java
If the iOS DashPay Id's are not set correctly, then invites crated by this app will not be accepted by DashPay iOS.
=> fix(dashpay): support iOS acceptance of invites

build.gradle
Update DashJ to improve connectivity for new installs
=> chore: use dashj 0.17.12

integrations/crowdnode/src/main/java/org/dash/wallet/integrations/crowdnode/api/CrowdNodeApi.kt, integrations/crowdnode/src/main/java/org/dash/wallet/integrations/crowdnode/api/CrowdNodeBlockchainApi.kt, integrations/crowdnode/src/main/res/values/strings-crowdnode.xml, wallet/src/de/schildbach/wallet/util/AllowLockTimeRiskAnalysis.kt
=> fix: crowdnode feedback (NMA-1300)

integrations/crowdnode/src/main/res/values/strings-crowdnode.xml, translations/compare-strings.py
=> fix: CrowdNode text and update translations

common/src/main/java/org/dash/wallet/common/Configuration.java, common/src/main/java/org/dash/wallet/common/ui/dialogs/AdaptiveDialog.kt, common/src/main/java/org/dash/wallet/common/ui/enter_amount/EnterAmountFragment.kt, common/src/main/java/org/dash/wallet/common/ui/enter_amount/EnterAmountViewModel.kt, integrations/crowdnode/src/main/java/org/dash/wallet/integrations/crowdnode/api/CrowdNodeBlockchainApi.kt, integrations/crowdnode/src/main/java/org/dash/wallet/integrations/crowdnode/ui/portal/PortalFragment.kt, integrations/crowdnode/src/main/java/org/dash/wallet/integrations/crowdnode/ui/portal/TransferFragment.kt, wallet/src/de/schildbach/wallet/WalletApplication.java, wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java, wallet/src/de/schildbach/wallet/ui/OnboardingActivity.kt, wallet/src/de/schildbach/wallet/ui/backup/RestoreWalletDialogFragment.java
Minor CrowdNode-related fixes and a couple of other low-hanging stuff.
=> [NMA-1315] Crowdnode minor fixes

common/src/main/java/org/dash/wallet/common/Configuration.java, common/src/main/java/org/dash/wallet/common/ui/dialogs/AdaptiveDialog.kt, common/src/main/java/org/dash/wallet/common/ui/enter_amount/EnterAmountFragment.kt, common/src/main/java/org/dash/wallet/common/ui/enter_amount/EnterAmountViewModel.kt, common/src/main/res/values/colors.xml, integrations/crowdnode/src/main/java/org/dash/wallet/integrations/crowdnode/api/CrowdNodeApi.kt, integrations/crowdnode/src/main/java/org/dash/wallet/integrations/crowdnode/api/CrowdNodeBlockchainApi.kt, integrations/crowdnode/src/main/java/org/dash/wallet/integrations/crowdnode/model/ApiStatuses.kt, integrations/crowdnode/src/main/java/org/dash/wallet/integrations/crowdnode/ui/portal/PortalFragment.kt, integrations/crowdnode/src/main/java/org/dash/wallet/integrations/crowdnode/ui/portal/TransferFragment.kt, integrations/crowdnode/src/main/res/layout/fragment_portal.xml, integrations/crowdnode/src/main/res/values/styles.xml, integrations/crowdnode/src/test/java/org/dash/wallet/integrations/crowdnode/CrowdNodeApiAggregatorTest.kt, wallet/src/de/schildbach/wallet/WalletApplication.java, wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java, wallet/src/de/schildbach/wallet/ui/OnboardingActivity.kt, wallet/src/de/schildbach/wallet/ui/backup/RestoreWalletDialogFragment.java
We'll be releasing 7.5.2 with the transaction grouping and the new UI for transactions and details, so no need for a separate branch.
=> feat: CrowdNode bugfixes for 7.5.2

integrations/crowdnode/build.gradle, integrations/crowdnode/src/main/java/org/dash/wallet/integrations/crowdnode/api/CrowdNodeApi.kt, integrations/crowdnode/src/test/java/org/dash/wallet/integrations/crowdnode/CrowdNodeTxFilterTest.kt, wallet/res/layout/home_activity.xml, wallet/res/layout/home_content.xml, wallet/src/de/schildbach/wallet/WalletApplication.java, wallet/src/de/schildbach/wallet/ui/GlobalFooterActivity.kt, wallet/src/de/schildbach/wallet/ui/main/MainViewModel.kt, wallet/src/de/schildbach/wallet/ui/main/WalletActivity.java, wallet/src/de/schildbach/wallet/ui/main/WalletFragment.kt, wallet/src/de/schildbach/wallet/ui/preference/PinRetryController.java, wallet/src/de/schildbach/wallet/ui/scan/ScanActivity.java, wallet/src/de/schildbach/wallet/ui/widget/ShortcutButton.kt, wallet/src/de/schildbach/wallet/ui/widget/ShortcutsPane.kt, wallet/test/de/schildbach/wallet/util/ui/WalletFragmentTest.kt, wallet/test/de/schildbach/wallet/util/viewModels/MainViewModelTest.kt
To simplify the master - dashpay merge in the future, we can bring the codebase a bit closer to each other.
Major changes are:
- WalletActivity is broken down into activity + WalletFragment similar to dashpay
- ShortcutPane improvements are backported to master so that we don't start to extend the old logic again.
- Some cleanup in the MainActivity
=> [NMA-1311] Improvements for DashPay merge

common/src/main/java/org/dash/wallet/common/WalletDataProvider.kt, common/src/main/java/org/dash/wallet/common/transactions/CoinsFromAddressTxFilter.kt, common/src/main/java/org/dash/wallet/common/transactions/CoinsReceivedTxFilter.kt, integrations/crowdnode/src/main/java/org/dash/wallet/integrations/crowdnode/api/CrowdNodeApi.kt, integrations/crowdnode/src/main/java/org/dash/wallet/integrations/crowdnode/api/CrowdNodeBlockchainApi.kt, integrations/crowdnode/src/main/java/org/dash/wallet/integrations/crowdnode/transactions/CrowdNodeWelcomeToApiResponse.kt, integrations/crowdnode/src/main/java/org/dash/wallet/integrations/crowdnode/transactions/FullCrowdNodeSignUpTxSet.kt, integrations/crowdnode/src/main/java/org/dash/wallet/integrations/crowdnode/transactions/PossibleAcceptTermsResponse.kt, integrations/crowdnode/src/main/java/org/dash/wallet/integrations/crowdnode/transactions/PossibleWelcomeResponse.kt, integrations/crowdnode/src/main/java/org/dash/wallet/integrations/crowdnode/ui/CrowdNodeViewModel.kt, integrations/crowdnode/src/test/java/org/dash/wallet/integrations/crowdnode/CrowdNodeApiAggregatorTest.kt, integrations/crowdnode/src/test/java/org/dash/wallet/integrations/crowdnode/CrowdNodeTxFilterTest.kt, wallet/CHANGES, wallet/build.gradle, wallet/res/layout/activity_staking.xml, wallet/src/de/schildbach/wallet/ui/staking/StakingActivity.kt, wallet/src/de/schildbach/wallet/ui/transactions/CrowdNodeTxResourceMapper.kt
Changing detection logic for CrowdNode responses to fix some sign-up issues.
We don't know if we're gonna go ahead with this solution yet.
=> [NMA-1317] fix for detecting CrowdNode transactions

wallet/res/layout/fragment_enter_pin.xml, wallet/res/layout/pin_preview_view.xml, wallet/src/de/schildbach/wallet/ui/CheckPinDialog.kt, wallet/src/de/schildbach/wallet/ui/CheckPinViewModel.kt, wallet/src/de/schildbach/wallet/ui/SetPinActivity.kt, wallet/src/de/schildbach/wallet/ui/preference/PinRetryController.java
…Screens
There is a change for testing where the PIN limit is set to 3.
None
=> feat: show last pin attempt warning on CheckPinDialog and Change PIN Screen (NMA-1271)

common/src/main/java/org/dash/wallet/common/WalletDataProvider.kt, common/src/main/res/layout/vertical_segmented_picker_option_view.xml, integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/ui/CoinbaseConvertCryptoFragment.kt, integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/ui/EnterAmountToTransferFragment.kt, integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/ui/TransferDashFragment.kt, integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/ui/convert_currency/ConvertViewFragment.kt, integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/ui/convert_currency/model/SwapRequest.kt, integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/ui/convert_currency/model/SwapValueErrorType.kt, integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/viewmodels/CoinbaseConversionPreviewViewModel.kt, integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/viewmodels/ConvertViewViewModel.kt, integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/viewmodels/TransferDashViewModel.kt, integrations/coinbase-integration/src/main/res/layout/dialog_coinbase_buy_dash.xml, integrations/coinbase-integration/src/main/res/layout/transfer_dash_fragment.xml, integrations/crowdnode/src/main/java/org/dash/wallet/integrations/crowdnode/utils/CrowdNodeBalanceCondition.kt, integrations/crowdnode/src/test/java/org/dash/wallet/integrations/crowdnode/CrowdNodeBalanceConditionTest.kt, wallet/src/de/schildbach/wallet/WalletApplication.java, wallet/src/de/schildbach/wallet/ui/BuyAndSellIntegrationsActivity.kt
Coinbase needs a warning in the case the user has balance on CrowdNode and he tryies to empty his wallet.
- Some minor refactorings are also done
=> [NMA-1314] Minimum balance warning for coinbase

wallet/src/de/schildbach/wallet/ui/coinbase/CoinBaseWebClientActivity.kt
This may have been easier than I thought originally.
=> fix(coinbase): disable autologout for coinbase login / 2FA

common/src/main/java/org/dash/wallet/common/data/AddressMetadata.kt, common/src/main/java/org/dash/wallet/common/data/ServiceName.kt, common/src/main/java/org/dash/wallet/common/data/TaxCategory.kt, common/src/main/java/org/dash/wallet/common/data/TransactionMetadata.kt, common/src/main/java/org/dash/wallet/common/services/TransactionMetadataProvider.kt, common/src/main/java/org/dash/wallet/common/transactions/TransactionCategory.kt, wallet/androidTest/de/schildbach/wallet/database/DatabaseMigrationTest.kt, wallet/schemas/de.schildbach.wallet.AppDatabase/1.json, wallet/schemas/de.schildbach.wallet.AppDatabase/11.json, wallet/schemas/de.schildbach.wallet.AppDatabase/12.json, wallet/schemas/de.schildbach.wallet.AppDatabase/17.json, wallet/src/de/schildbach/wallet/AppDatabase.java, wallet/src/de/schildbach/wallet/WalletApplication.java, wallet/src/de/schildbach/wallet/data/AddressMetadataDao.kt, wallet/src/de/schildbach/wallet/data/AppDatabaseMigrations.kt, wallet/src/de/schildbach/wallet/data/TransactionMetadataDao.kt, wallet/src/de/schildbach/wallet/di/DataProviderModule.kt, wallet/src/de/schildbach/wallet/di/DatabaseModule.kt, wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java, wallet/src/de/schildbach/wallet/service/WalletTransactionMetadataProvider.kt
Add minimal tx metadata support
=> feat: add tx metadata support (NMA-1321)

common/src/main/java/org/dash/wallet/common/data/ServiceName.kt, common/src/main/java/org/dash/wallet/common/services/TransactionMetadataProvider.kt, integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/viewmodels/CoinbaseBuyDashOrderReviewViewModel.kt, integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/viewmodels/CoinbaseConversionPreviewViewModel.kt, integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/viewmodels/TransferDashViewModel.kt, wallet/src/de/schildbach/wallet/service/WalletTransactionMetadataProvider.kt
=> feat(coinbase): add transfer defaults

build.gradle
This will address some issues with syncing the masternode list and also InstantSend
https://github.com/dashevo/dashj/pull/167
=> chore: update dashj-core to 0.17.13

integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/ui/EnterTwoFaCodeFragment.kt
Verify button state should be updated on every change to the 2FA field
=> [NMA-1361] Enable Cointinue button after pasting into 2FA field

.tx/config
=> chore: add coinbase strings to transifex config

integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/repository/CoinBaseRepository.kt, integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/service/CoinBaseServicesApi.kt, integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/ui/EnterTwoFaCodeFragment.kt, integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/viewmodels/EnterTwoFaCodeViewModel.kt, wallet/CHANGES, wallet/build.gradle
=> NMA-1367 :  SMS 2FA

build.gradle
Use RC11 SNAPSJOT of DashJ
https://github.com/dashevo/dashj/pull/169
=> Dash Core 18: update dashj to 0.18.0-RC11-SNAPSHOT

build.gradle, wallet/src/de/schildbach/wallet/ui/dashpay/CreateIdentityService.kt, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt, wallet/test/de/schildbach/wallet/util/viewModels/MainViewModelTest.kt
=> fix(dashpay): fix key issue on create identity, restore identity

wallet/src/de/schildbach/wallet/payments/RequestWalletBalanceTask.java, wallet/testNet3/res/values/values.xml
This will fix the testnet Import Private Key function.
=> fix: update testnet block explorer url's

.github/workflows/dashwallet.yml, .github/workflows/manual_distribution.yml, exploredata.rb, features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ExploreDatabase.kt, features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ExploreSyncWorker.kt, features/exploredash/src/main/java/org/dash/wallet/features/exploredash/repository/ExploreRepository.kt, integrations/crowdnode/src/main/java/org/dash/wallet/integrations/crowdnode/api/CrowdNodeConfirmationTxHandler.kt, wallet/src/de/schildbach/wallet/WalletApplication.java, wallet/src/de/schildbach/wallet/ui/more/AboutActivity.kt, wallet/src/de/schildbach/wallet/ui/more/AboutViewModel.kt
- Download and detect the testnet database for testnet builds
- Run the cloud update even if the preloaded database was unpacked
- Don't update the timestamp if it's invalid
=> [NMA-1414] Explore fixes

wallet/src/de/schildbach/wallet/service/BlockchainStateDataProvider.kt
=> fix: prevent division by zero from empty valid masternode list (NMA-1393)

build.gradle, wallet/src/de/schildbach/wallet/Constants.java, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt, wallet/src/de/schildbach/wallet/ui/send/DecodePrivateKeyTask.java
=> feat (dashpay): support dpp 0.23 with new fee structure

wallet/src/de/schildbach/wallet/ui/send/SendCoinsBaseViewModel.kt
- Ignore address assignment for an intent without address
=> fix: BIP70 payment request crash [NMA-1443]

wallet/res/layout/address_book_onepane.xml, wallet/res/layout/network_monitor_onepane.xml, wallet/res/layout/peer_list_fragment.xml, wallet/src/de/schildbach/wallet/ui/AddressBookActivity.java, wallet/src/de/schildbach/wallet/ui/NetworkMonitorActivity.java, wallet/src/de/schildbach/wallet/ui/payments/SweepWalletActivity.kt
- Restored back buttons and titles for the Network Monitor, Address Book, and Import private key (last one missed the title).
=> fix: back button for tools screens

wallet/src/de/schildbach/wallet/ui/send/UpholdTransferActivity.kt
Prevent a crash from an uninitialized `lateinit var`
=> fix: prevent uphold crash and center text

wallet/src/de/schildbach/wallet/Constants.java
Thus far 0.24 is the same as 0.23 as far as DashPay is concerned (31 January)
=> feat(dashpay): Support dpp 0.24

wallet/src/de/schildbach/wallet/service/AndroidActionsService.kt, wallet/src/de/schildbach/wallet/ui/staking/StakingActivity.kt
=> fix(crowdnode): prevent Android 12 crash and close online linking screen

wallet/src/de/schildbach/wallet/Constants.java
DashJ 19-SNAPSHOT is what supports the HPMN features
=> feat:  support core 19 hpmn features

.github/workflows/dashwallet.yml, .github/workflows/manual_distribution.yml, build.gradle, features/exploredash/build.gradle, features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/DashDirectUserAuthFragment.kt, features/exploredash/src/main/java/org/dash/wallet/features/exploredash/utils/DashDirectConfig.kt, integrations/coinbase/build.gradle
`ktfmt` is a code formatting tool. To run, execute `./gradlew ktfmtFormat` from the console, or as gradle action from Android Studio.
- For now, the gradle plugin will be installed in the `explore-dash` module only.
- Kotlin upgraded to 1.7.10 to avoid `ktfmt` compatibility issues.
- `ktfmtCheck` added to the CI pipeline for pull requests.
=> feat(explore-dash): formatting tool for the explore module

build.gradle, common/src/main/java/org/dash/wallet/common/data/NetworkStatus.kt, common/src/main/java/org/dash/wallet/common/services/BlockchainStateProvider.kt, common/src/main/java/org/dash/wallet/common/transactions/filters/CoinsReceivedTxFilter.kt, integrations/crowdnode/src/test/java/org/dash/wallet/integrations/crowdnode/CrowdNodeTxFilterTest.kt, wallet/build.gradle, wallet/res/values/strings-extra.xml, wallet/res/values/strings.xml, wallet/schnapps/res/values/values.xml, wallet/src/de/schildbach/wallet/WalletApplication.java, wallet/src/de/schildbach/wallet/data/BlockchainIdentityData.kt, wallet/src/de/schildbach/wallet/di/DashPayModule.kt, wallet/src/de/schildbach/wallet/livedata/EncryptWalletLiveData.kt, wallet/src/de/schildbach/wallet/service/BlockchainService.java, wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java, wallet/src/de/schildbach/wallet/service/BlockchainStateDataProvider.kt, wallet/src/de/schildbach/wallet/service/CoinJoinService.kt, wallet/src/de/schildbach/wallet/service/platform/PlatformSyncService.kt, wallet/src/de/schildbach/wallet/ui/CreateUsernameActivity.kt, wallet/src/de/schildbach/wallet/ui/OnboardingViewModel.kt, wallet/src/de/schildbach/wallet/ui/dashpay/CreateIdentityService.kt, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformPaymentConfirmDialog.kt, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt, wallet/src/de/schildbach/wallet/ui/dashpay/UpgradeToEvolutionFragment.kt, wallet/src/de/schildbach/wallet/ui/invite/InviteFriendFragment.kt, wallet/src/de/schildbach/wallet/util/WalletUtils.java, wallet/test/de/schildbach/wallet/util/transactions/TransactionWrapperHelperTest.kt
Create a username by first mixing the funds used for it.
https://github.com/dashpay/dashj/pull/196
=> feat(dashpay): use coinjoin to create username

translations/compare-strings.py
=> feat: add coinbase to translation comparison tool

.tx/config
transifex changed the config schema.
=> chore: upgrade transifex config

common/src/main/java/org/dash/wallet/common/ui/enter_amount/EnterAmountFragment.kt, wallet/src/de/schildbach/wallet/ui/LockScreenActivity.kt, wallet/src/de/schildbach/wallet/ui/main/MainViewModel.kt, wallet/src/de/schildbach/wallet/ui/send/SendCoinsFragment.kt
See title.
- Added PIN code check.
- Fixed Dash format for the balance header - it was showing trailing zeros which we don't want.
=> fix: request PIN code for balance if launched from the lock screen

wallet/src/de/schildbach/wallet/ui/transactions/TxError.kt
Remove test code for previous story related to TX errors
=> fix: remove TxError code for test cases

build.gradle, wallet/CHANGES, wallet/build.gradle
update to dashj 19.0.1 to fix some issues
=> Release 9.0.1

integrations/coinbase/src/main/res/layout/fragment_coinbase_services.xml
hide “Transfer Dash“ when connection gone
=> Coinbase Transfer button (Network unavailable)

features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/ExploreMapFragment.kt, features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/ItemDetails.kt, features/exploredash/src/main/res/drawable/ic_atm_marker.xml
Coin ATM Radar data doesn't have cover images and the icons aren't suitable for map markers.
- Hide the cover image if not present.
- Replace the map marker with a generic ATM icon.
=> fix(explore): ATM UI issues

.github/workflows/dashwallet.yml, .github/workflows/manual_distribution.yml, build.gradle, common/src/main/java/org/dash/wallet/common/util/HttpClientExt.kt, wallet/build.gradle, wallet/res/values/strings.xml, wallet/src/de/schildbach/wallet/ui/backup/RestoreFromFileActivity.kt, wallet/src/de/schildbach/wallet/ui/backup/RestoreFromFileHelper.java, wallet/src/de/schildbach/wallet/ui/backup/RestoreWalletDialogFragment.java, wallet/src/de/schildbach/wallet/ui/main/MainViewModel.kt, wallet/src/de/schildbach/wallet/ui/main/WalletActivity.java, wallet/src/de/schildbach/wallet/ui/main/WalletActivityExt.kt, wallet/src/de/schildbach/wallet/ui/main/WalletTransactionsFragment.kt
Our "low storage" warning uses deprecated APIs and needs upgrading.
- Upgraded to the new storage APIs for Android 8+
- Restored Time Skew dialog
- Removed other unused dialogs
- Fixed duplicated MainViewModel instance
- Upgraded some dependencies
=> chore: upgrade low storage warning

common/build.gradle, integrations/uphold/build.gradle, integrations/uphold/src/main/java/org/dash/wallet/integration/uphold/api/RemoteDataSource.kt, integrations/uphold/src/main/java/org/dash/wallet/integration/uphold/api/UpholdClient.java, integrations/uphold/src/main/java/org/dash/wallet/integration/uphold/api/UpholdClientExt.kt, integrations/uphold/src/main/java/org/dash/wallet/integration/uphold/data/UpholdAccessToken.java, integrations/uphold/src/main/java/org/dash/wallet/integration/uphold/data/UpholdCardAddress.kt, integrations/uphold/src/main/java/org/dash/wallet/integration/uphold/data/UpholdCryptoCardAddress.java, integrations/uphold/src/main/java/org/dash/wallet/integration/uphold/ui/UpholdAccountActivity.java, wallet/build.gradle, wallet/res/layout/activity_uphold_tranfser.xml, wallet/src/de/schildbach/wallet/adapter/BigDecimalAdapter.java, wallet/src/de/schildbach/wallet/rates/BitPayClient.java, wallet/src/de/schildbach/wallet/rates/CryptoCompareClient.java, wallet/src/de/schildbach/wallet/rates/DashCasaClient.java, wallet/src/de/schildbach/wallet/rates/DashRetailClient.java, wallet/src/de/schildbach/wallet/rates/LocalBitcoinsClient.java, wallet/src/de/schildbach/wallet/rates/PoloniexClient.java
Seems like the issue with the incorrect balance is that we're taking the first DASH card we see, while there could be more than one.
- Return a list of DASH cards from GetCards instead of the first card.
- For the total balance, sum over all balances. For the active card, take the first one with balance or just the first one if all are empty.
- Move Uphold from Moshi to Gson.
=> fix(uphold): wrong balance

integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/di/CoinBaseModule.kt, integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/network/RemoteDataSource.kt, integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/repository/CoinBaseRepository.kt, integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/repository/remote/TokenAuthenticator.kt, integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/service/CoinBaseAuthApi.kt, integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/ui/TransferDashFragment.kt, integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/utils/CoinbaseConfig.kt, integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/viewmodels/CoinbaseActivityViewModel.kt, integrations/coinbase/src/main/java/org/dash/wallet/integration/coinbase_integration/viewmodels/TransferDashViewModel.kt, integrations/coinbase/src/main/res/values/strings.xml, wallet/src/de/schildbach/wallet/ui/coinbase/CoinbaseActivity.kt
=> Coinbase: Transfer Dash: You will receive amount

build.gradle
=> chore: update dashj to 19.0.3-SNAPSHOT

wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java, wallet/src/de/schildbach/wallet/ui/staking/StakingActivity.kt
see #1148 
- Use accumulated amount for the fiat calculations
=> fix: fiat balance in the 'coins received' notification

wallet/src/de/schildbach/wallet/ui/send/AddressInputFragment.kt, wallet/src/de/schildbach/wallet/ui/send/ConfirmTransactionDialog.kt
- Trim the address input to allow for trailing spaces/newlines.
- Fix the Confirmation dialog background.
=> fix: minor Send flow issues

common/src/main/java/org/dash/wallet/common/services/analytics/AnalyticsConstants.kt, integrations/uphold/src/main/java/org/dash/wallet/integration/uphold/ui/UpholdPortalFragment.kt, wallet/src/de/schildbach/wallet/ui/buy_sell/BuyAndSellIntegrationsFragment.kt, wallet/src/de/schildbach/wallet/ui/buy_sell/BuyAndSellViewModel.kt
We want to log a couple of events for Topper.
=> feat(topper): Firebase events

wallet/src/de/schildbach/wallet/WalletApplication.java, wallet/src/de/schildbach/wallet/service/BootstrapReceiver.java, wallet/src/de/schildbach/wallet/ui/more/masternode_keys/MasternodeKeyChainAdapter.kt
Fixes for Masternode Key Usage
=> fix: handle app upgrades and properly display masternode key usage

build.gradle, wallet/res/values/strings-extra.xml
=> chore: update to dashj-19.0.4

wallet/README.md, wallet/README.recover.md
=> docs: update README.md to include fastlane and transifex changes

common/src/main/java/org/dash/wallet/common/services/analytics/AnalyticsConstants.kt, wallet/src/de/schildbach/wallet/ui/explore/ExploreFragment.kt, wallet/src/de/schildbach/wallet/ui/more/MoreFragment.kt, wallet/src/de/schildbach/wallet/ui/send/AddressInputFragment.kt, wallet/src/de/schildbach/wallet/ui/send/AddressInputViewModel.kt
Add some events, fix some names, and remove some others.
=> fix: firebase events

integrations/uphold/src/main/java/org/dash/wallet/integration/uphold/ui/UpholdPortalFragment.kt, wallet/src/de/schildbach/wallet/data/BuyAndSellDashServicesModel.kt
This reverts commit f5cd3b080125152b48caee2a8bf012455447e755 and restores Topper entry points.
=> chore: revert "chore: disable Topper (#1164)"

build.gradle
This changes how tx's are handled after being sent.
https://github.com/dashpay/dashj/pull/227
=> chore: update to dashj 19.0.5-SNAPSHOT for tx error fixes

wallet/res/layout/activity_settings.xml, wallet/res/layout/fragment_request_username.xml, wallet/res/values/strings.xml, wallet/src/de/schildbach/wallet/WalletUIConfig.kt, wallet/src/de/schildbach/wallet/ui/CreateUsernameActivity.kt, wallet/src/de/schildbach/wallet/ui/SettingsActivity.kt, wallet/src/de/schildbach/wallet/ui/SettingsViewModel.kt, wallet/src/de/schildbach/wallet/ui/dashpay/DashPayViewModel.kt
Add Voting toggle to setting screen ,To enable/ disable voting flow
=> Toggle username voting period 

integrations/uphold/src/main/java/org/dash/wallet/integration/uphold/ui/UpholdPortalFragment.kt, wallet/src/de/schildbach/wallet/data/BuyAndSellDashServicesModel.kt
This reverts commit ca011d2fc2ce7d2fe5f0fc61767f5cedf3c9f5cd.
Revert the Revert the disable!
=> chore: disable Topper

build.gradle
Use the published DashJ 19.0.5
=> chore: use dashj 19.0.5

wallet/CHANGES, wallet/build.gradle
=> chore: bump version & changelog

wallet/res/values/strings.xml, wallet/src/de/schildbach/wallet/data/CoinJoinConfig.kt, wallet/src/de/schildbach/wallet/payments/SendCoinsTaskRunner.kt, wallet/src/de/schildbach/wallet/service/CoinJoinService.kt, wallet/src/de/schildbach/wallet/ui/dashpay/CreateIdentityService.kt, wallet/src/de/schildbach/wallet/ui/transactions/TxResourceMapper.java, wallet/staging/res/values/values.xml, wallet/test/de/schildbach/wallet/util/services/SendCoinsTaskRunnerTest.kt
Use updated dashJ to fix CoinJoin Send issues
* username creation uses fully mixed coins only
* regular send uses unmixed coins only
https://github.com/dashpay/dashj/pull/228
=> fix(dashpay): coinjoin send fix

integrations/crowdnode/src/main/java/org/dash/wallet/integrations/crowdnode/api/CrowdNodeApi.kt, wallet/CHANGES, wallet/build.gradle, wallet/src/de/schildbach/wallet/transactions/WalletObserver.kt
Some users experience CrowdNode signup being stuck, and the logs indicate the context is missing. 
- Propagate context in `USER_THREAD` where transaction observers are invoked.
=> fix: stuck CrowdNode signup

build.gradle
=> chore: update to dashj 19.0.6

wallet/schemas/de.schildbach.wallet.database.AppDatabase/18.json, wallet/src/de/schildbach/wallet/database/AppDatabase.kt, wallet/src/de/schildbach/wallet/database/BlockchainStateRoomConverters.kt, wallet/src/de/schildbach/wallet/database/entity/BlockchainIdentityData.kt, wallet/src/de/schildbach/wallet/di/DashPayModule.kt, wallet/src/de/schildbach/wallet/service/CoinJoinService.kt, wallet/src/de/schildbach/wallet/service/platform/PlatformBroadcastService.kt, wallet/src/de/schildbach/wallet/service/platform/PlatformService.kt, wallet/src/de/schildbach/wallet/service/platform/PlatformSyncService.kt, wallet/src/de/schildbach/wallet/ui/DashPayUserActivityViewModel.kt, wallet/src/de/schildbach/wallet/ui/InviteHandlerViewModel.kt, wallet/src/de/schildbach/wallet/ui/OnboardingViewModel.kt, wallet/src/de/schildbach/wallet/ui/dashpay/BaseProfileViewModel.kt, wallet/src/de/schildbach/wallet/ui/dashpay/CreateIdentityNotification.kt, wallet/src/de/schildbach/wallet/ui/dashpay/CreateIdentityService.kt, wallet/src/de/schildbach/wallet/ui/dashpay/DashPayViewModel.kt, wallet/src/de/schildbach/wallet/ui/dashpay/EditProfileViewModel.kt, wallet/src/de/schildbach/wallet/ui/dashpay/NotificationsLiveData.kt, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt, wallet/src/de/schildbach/wallet/ui/dashpay/notification/NotificationsViewModel.kt, wallet/src/de/schildbach/wallet/ui/dashpay/work/SendContactRequestWorker.kt, wallet/src/de/schildbach/wallet/ui/dashpay/work/SendInviteWorker.kt, wallet/src/de/schildbach/wallet/ui/dashpay/work/UpdateProfileWorker.kt, wallet/src/de/schildbach/wallet/ui/invite/CreateInviteViewModel.kt, wallet/src/de/schildbach/wallet/ui/invite/InvitationFragmentViewModel.kt, wallet/src/de/schildbach/wallet/ui/invite/InviteHandler.kt, wallet/src/de/schildbach/wallet/ui/main/MainViewModel.kt, wallet/src/de/schildbach/wallet/ui/payments/PaymentsPayFragment.kt, wallet/src/de/schildbach/wallet/ui/transactions/TxResourceMapper.java
* If the app is force closed, then the coinjoin process will not resume when the app is restarted.
https://github.com/dashpay/dashj/pull/232
=> fix(dashpay):  fix issue when restarting coinjoin

build.gradle, wallet/src/de/schildbach/wallet/Constants.java
=> chore: update to dashj 20.0.0-SNAPSHOT to support Core v20

Gemfile.lock
=> chore: add x86_64-linux to Gemfile.lock

common/build.gradle, features/exploredash/build.gradle, integrations/coinbase/build.gradle, integrations/crowdnode/build.gradle, integrations/uphold/build.gradle, sample-integration-android/build.gradle, wallet/build.gradle, wallet/res/layout/activity_lock_screen.xml, wallet/src/de/schildbach/wallet/service/BlockchainSyncJobService.kt
remove all android 6 and 7 references, though none were found.  2 Lollipop references were removed.
=> fix: deprecate Android 6 support

build.gradle
Fixes for several issues related to syncing, including crashes
=> fix: update to dashj 20.0.3-SNAPSHOT

wallet/res/layout/fragment_masternode_key_chain.xml, wallet/res/layout/fragment_masternode_key_types.xml
=> chore: specify correct classes for tools:context

integrations/uphold/src/main/java/org/dash/wallet/integrations/uphold/api/TopperClient.kt, integrations/uphold/src/main/java/org/dash/wallet/integrations/uphold/data/SupportedTopperPaymentMethods.kt, integrations/uphold/src/test/java/org/dash/wallet/integrations/uphold/TopperClientTest.kt, integrations/uphold/src/test/resources/org/dash/wallet/integrations/uphold/payment-methods.json, wallet/src/de/schildbach/wallet/ui/buy_sell/BuyAndSellViewModel.kt
=> feat(topper): set default amount to 10 time the minimum (about $100)

integrations/uphold/src/main/java/org/dash/wallet/integrations/uphold/api/TopperClient.kt
Some logging was not removed in the original PR.
=> fix(topper): remove logging of JWT token

features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/explore/SearchFragment.kt, integrations/coinbase/src/main/java/org/dash/wallet/integrations/coinbase/ui/CoinbaseConversionPreviewFragment.kt, integrations/coinbase/src/main/java/org/dash/wallet/integrations/coinbase/ui/CoinbaseOrderReviewFragment.kt, integrations/coinbase/src/main/java/org/dash/wallet/integrations/coinbase/ui/EnterTwoFaCodeFragment.kt, integrations/coinbase/src/main/java/org/dash/wallet/integrations/coinbase/ui/TransferDashFragment.kt
Remove memory leaks related never unsubscribing from:
1. `setOnApplyWindowInsetsListener`
2. `onBackPressedDispatcher.addCallback`
=> fix: remove memoryleaks in Coinbase and Explore

features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/ctxspend/dialogs/CTXSpendTermsDialog.kt, features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/explore/SearchFragment.kt, features/exploredash/src/main/res/values/strings-explore-dash.xml
Translators found a misspelled word: "bellow" instead of "below"
=> fix(dashspend): fix typo and rename dash_direct resource strings

build.gradle, wallet/src/de/schildbach/wallet/WalletApplication.java
Add deadlock detection.
https://github.com/dashpay/dashj/pull/250
=> feat: add deadlock detection support

wallet/build.gradle, wallet/proguard.cfg, wallet/src/de/schildbach/wallet/Constants.java, wallet/src/de/schildbach/wallet/ui/dashpay/PlatformRepo.kt
https://github.com/HashEngineering/kotlin-platform/pull/2
Others:
1. https://github.com/pankcuf/rs-x11-hash/pull/6
2. https://github.com/dashpay/bls-signatures/pull/88
3. https://github.com/dashpay/platform/pull/1828
=> feat: support for making DAPI calls via dash sdk

wallet/AndroidManifest.xml
=> feat: support devices without a flash

features/exploredash/build.gradle, features/exploredash/src/main/java/org/dash/wallet/features/exploredash/services/UserLocationState.kt, features/exploredash/src/test/java/org/dash/wallet/features/exploredash/ExploreDatabaseTest.kt
=> chore: update play-services dependencies for maps

wallet/AndroidManifest.xml, wallet/CHANGES, wallet/build.gradle, wallet/src/de/schildbach/wallet/WalletApplication.java
* remove read images permission which is not needed in Dash Wallet and will be replaced in DashPay using the Android Picture Picker.
* Fix upgrade crash
N/A
=> v10.3.1: remove read images permission and fix upgrade crash

wallet/src/de/schildbach/wallet/util/TimeUtils.kt
fix off by one bug with the Time Check code for CoinJoin
=> fix: fix time check logic for coinjoin

build.gradle, wallet/src/de/schildbach/wallet/ui/dashpay/CreateIdentityService.kt, wallet/src/de/schildbach/wallet/ui/more/MoreFragment.kt, wallet/src/de/schildbach/wallet/ui/username/voting/VerifyIdentityFragment.kt
=> fix(dashpay): username request fixes

wallet/AndroidManifest.xml, wallet/src/de/schildbach/wallet/WalletApplication.java, wallet/src/de/schildbach/wallet/service/BlockchainServiceImpl.java
=> fix: foreground service fixes regarding sdk 14
